#!/usr/bin/env python3
"""Generate the SDK's data model and REST layer from spec.json + naming.json.

Reads the machine-extracted documentation dump (``spec.json``), applies endpoint hygiene (drops the
concrete example paths the docs repeat next to their templated form), looks every retained operation
up in the curated ``naming.json`` and writes Java 17 sources under ``src/main/java``:

  io.github.skiesworld.qqbot.model           shared payload types plus the response types of the operations
  io.github.skiesworld.qqbot.model.request   the request bodies of the operations
  io.github.skiesworld.qqbot.model.constant  int constant holders for the docs' value tables
  io.github.skiesworld.qqbot.event.model     the event payloads, named the way EventModels looks them up
  io.github.skiesworld.qqbot.api             one class per resource group, plus the Api facade
  io.github.skiesworld.qqbot.api.endpoint    Endpoints, one Endpoint constant per operation

Stdlib only, byte-for-byte reproducible, and it refuses to write anything when an operation has no
curated name. stdout stays ASCII because Windows consoles default to GBK; Chinese only ever reaches
UTF-8 files.

naming.json schema:

  apiGroups        group key -> generated class name; the accessors on Api follow API_ACCESSORS here
  typeAliases      doc type name -> java class name (Data -> UrlLinkData, DMS -> Dms, ...)
  skipTypes        registry entries that are not types at all (HTTP status tables, section rows, ...)
  scalarTypeNames  doc type tokens that are prose for a scalar ("ISO8601 timestamp" -> String)
  typeFieldOverrides  {type: {field: documented type}} fixes for tables the docs got wrong
  constants        value tables -> int constant holders; `values` curates the ones keyed by number
  endpoints        "METHOD /path-template" -> {title, group, method, doc, request, response,
                 requestFields?, responseFields?, noRequestFields?}
                 `request`/`response` name a generated DTO, an existing model, 'void' or a
                 fully qualified type; the *Fields keys replace what the crawler extracted, and
                 `noRequestFields` drops a table that documents a response rather than the call.

Usage: python tools/docgen/gen_java.py
"""

import json
import os
import re
import sys
import textwrap
import collections

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SPEC_PATH = os.path.join(HERE, 'spec.json')
NAMING_PATH = os.path.join(HERE, 'naming.json')
SRC_ROOT = os.path.join(REPO, 'src', 'main', 'java')

MODEL_PKG = 'io.github.skiesworld.qqbot.model'
REQUEST_PKG = 'io.github.skiesworld.qqbot.model.request'
CONSTANT_PKG = 'io.github.skiesworld.qqbot.model.constant'
EVENT_PKG = 'io.github.skiesworld.qqbot.event.model'
EVENT_ROOT_PKG = 'io.github.skiesworld.qqbot.event'
API_PKG = 'io.github.skiesworld.qqbot.api'
ENDPOINT_PKG = 'io.github.skiesworld.qqbot.api.endpoint'

BANNER = ('// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.\n'
          '// Regenerate instead of editing.\n')

SERIALIZED = 'com.google.gson.annotations.SerializedName'
HTTP_TRANSPORT = 'io.github.skiesworld.qqbot.http.HttpTransport'
PARAMS = 'io.github.skiesworld.qqbot.http.Params'
ENDPOINT = 'io.github.skiesworld.qqbot.http.Endpoint'
ENDPOINTS = 'io.github.skiesworld.qqbot.api.endpoint.Endpoints'
OBJECTS = 'java.util.Objects'

IDENT_RE = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')
LOWER_IDENT_RE = re.compile(r'^[a-z_][a-z0-9_]*$')
PATH_ARG_RE = re.compile(r'\{([^{}]+)\}')
UPPER_RE = re.compile(r'^[A-Z][A-Z0-9_]*$')
TOKEN_RE = re.compile(r'[A-Za-z_][A-Za-z0-9_]*')

JAVA_KEYWORDS = {
    'abstract', 'assert', 'boolean', 'break', 'byte', 'case', 'catch', 'char', 'class', 'const',
    'continue', 'default', 'do', 'double', 'else', 'enum', 'extends', 'final', 'finally', 'float',
    'for', 'goto', 'if', 'implements', 'import', 'instanceof', 'int', 'interface', 'long', 'native',
    'new', 'package', 'private', 'protected', 'public', 'return', 'record', 'short', 'static',
    'strictfp', 'super', 'switch', 'synchronized', 'this', 'throw', 'throws', 'transient', 'try',
    'var', 'void', 'volatile', 'while', 'yield',
}

# row headers the docs reuse inside parameter tables; they never name a field
META_INFO_KEYS = {'HTTP URL', 'HTTP Method', 'Code', 'Value'}

SCALAR_KEYWORDS = {
    'string': 'String', 'str': 'String',
    'integer': 'Long', 'int': 'Long', 'int32': 'Long', 'int64': 'Long', 'uint': 'Long',
    'uint32': 'Long', 'uint64': 'Long', 'long': 'Long',
    'number': 'Double', 'float': 'Double', 'double': 'Double',
    'boolean': 'Boolean', 'bool': 'Boolean',
    'object': 'Map<String, Object>', 'any': 'Map<String, Object>',
    'json': 'Map<String, Object>', 'struct': 'Map<String, Object>',
}

SCALAR_TYPES = {'String', 'Long', 'Boolean', 'Double'}
BODY_METHODS = {'POST', 'PUT', 'PATCH'}
MAX_FLATTENED_BODY_FIELDS = 2
LONG_LINE = 116
WRAP_AT = 108
JDK_TYPES = {'List', 'Map', 'String', 'Long', 'Boolean', 'Double', 'Integer', 'Object', 'Endpoint'}

# the group classes and their accessors on Api are part of the published shape of the SDK
API_ACCESSORS = {
    'me': 'me', 'c2c': 'c2c', 'group': 'group', 'guild': 'guild', 'channel': 'channel',
    'channelMessages': 'channelMessages', 'channelContent': 'channelContent',
    'channelPermissions': 'channelPermissions', 'menu': 'menu', 'panels': 'panels',
    'interactions': 'interactions', 'gateway': 'gateway',
}

API_DOCS = {
    'me': 'Bot identity: its own profile, the guilds it joined and direct message sessions.',
    'c2c': 'One-to-one chat with a user: messages, streaming replies and rich media uploads.',
    'group': 'QQ group chats: messages, members, mutes, join requests and approval strategies.',
    'guild': 'Guilds the bot serves: profile, members, mutes and API permissions.',
    'channel': 'Sub-channels: read, create, update, delete and live member counts.',
    'channelMessages': 'Messages inside sub-channels and inside direct message sessions.',
    'channelContent': 'Content of a sub-channel: pins, schedules, forum threads, audio, announces.',
    'channelPermissions': 'Roles and the sub-channel permission bit maps of members and roles.',
    'menu': 'The bot global custom menu.',
    'panels': 'Command panels and the users or groups they are bound to.',
    'interactions': 'Responses to INTERACTION_CREATE events.',
    'gateway': 'WebSocket gateway urls.',
}


class Error(Exception):
    """Fatal generation problem: better to write nothing than a half known SDK."""


# The four envelopes a dispatch can be built into, and the javadoc each one earns. Order is the order of the
# generated enum, so PLAIN — the row a name absent from the table gets — reads as the last resort.
EVENT_ENVELOPES = collections.OrderedDict((
    ('MESSAGE', 'Carries message text and an author, so it reads as one turn in a conversation.'),
    ('NOTICE', 'Something happened somewhere: no text here, and no answer owed to it.'),
    ('REQUEST', 'Something happened that the bot owes an answer to, and the platform stops waiting.'),
    ('PLAIN', 'Session lifecycle plus anything this table does not place: the bare envelope.'),
))
ENVELOPES = tuple(EVENT_ENVELOPES)

RoutingRow = collections.namedtuple('RoutingRow', 'name envelope actor subject doc')


# --------------------------------------------------------------------------------------
# names, mirroring io.github.skiesworld.qqbot.util.Strings
# --------------------------------------------------------------------------------------

def _cased_segment(segment):
    """Mirror of Strings.casedSegment: shouty segments keep the capitals after a digit."""
    stripped = segment.replace('$', '')
    letters = [c for c in stripped if c.isalpha()]
    shouty = len(letters) > 1 and all(c.isupper() for c in letters)
    out, previous = [], ''
    for index, char in enumerate(stripped):
        if not char.isalpha():
            out.append(char)
            previous = char
            continue
        if index == 0:
            out.append(char.upper())
        elif shouty and previous.isdigit():
            out.append(char)
        else:
            out.append(char.lower())
        previous = char
    return ''.join(out)


def upper_camel(snake):
    """Port of io.github.skiesworld.qqbot.util.Strings.snakeToUpperCamel, which EventModels resolves with."""
    return ''.join(_cased_segment(s) for s in re.split(r'[_\- ]', snake) if s)


def lower_camel(snake):
    name = upper_camel(snake)
    return (name[:1].lower() + name[1:]) if name else name


def words(camel):
    """Split a java name into words, keeping acronym runs such as C2C in one piece."""
    out, current = [], ''
    for index, char in enumerate(camel):
        if char.isupper() and current:
            previous = current[-1]
            boundary = previous.islower()
            if previous.isupper() and index + 1 < len(camel) and camel[index + 1].islower():
                boundary = True
            if boundary:
                out.append(current)
                current = char
                continue
        current += char
    if current:
        out.append(current)
    return out


def const_name(method):
    return '_'.join(words(method)).upper()


def java_field(wire):
    """lowerCamel of the wire name; java keywords gain a Value suffix, the wire name never moves."""
    name = lower_camel(wire)
    return name + 'Value' if name in JAVA_KEYWORDS else name


def decapitalize(name):
    """lowerCamel of a java type name: only the leading acronym letters move."""
    index = 0
    while index < len(name) and name[index].isupper():
        index += 1
    if index == 0:
        return name
    if index == 1 or index == len(name):
        return name[:1].lower() + name[1:]
    return name[:index - 1].lower() + name[index - 1:]


def pretty(java_name):
    return ' '.join(words(java_name))


# --------------------------------------------------------------------------------------
# documented type strings -> java types
# --------------------------------------------------------------------------------------

def parse_type(raw):
    """Read the free-form type column: ``[]UploadPart``, ``Channel 对象``, ``string 数组``, ``uint64``."""
    text = (raw or '').strip()
    if not text:
        return {'kind': 'object'}
    if text.startswith('[]'):
        return {'kind': 'array', 'item': parse_type(text[2:])}
    match = re.match(r'^(?:map|Map|object)\s*<\s*(\w+)\s*,\s*(.+)>$', text)
    if match:
        return {'kind': 'map', 'key': parse_type(match.group(1)), 'value': parse_type(match.group(2))}
    match = re.match(r'^(.*?)\[\]$', text)
    if match:
        return {'kind': 'array', 'item': parse_type(match.group(1))}
    if '数组' in text:
        return {'kind': 'array', 'item': parse_type(text.split('数组')[0])}
    text = re.sub(r'[（(].*?[）)]', ' ', text).strip()
    low = text.lower()
    if low in ('array', 'list'):
        return {'kind': 'array', 'item': {'kind': 'unknown'}}
    if low == 'file':
        return {'kind': 'file'}
    if low in SCALAR_KEYWORDS:
        return {'kind': 'scalar', 'java': SCALAR_KEYWORDS[low]}
    match = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)', text)
    if not match:
        return {'kind': 'scalar', 'java': 'String'}
    token = match.group(1)
    if token.lower() in SCALAR_KEYWORDS:
        return {'kind': 'scalar', 'java': SCALAR_KEYWORDS[token.lower()]}
    if token.lower() in ('array', 'list'):
        return {'kind': 'array', 'item': {'kind': 'unknown'}}
    return {'kind': 'ref', 'name': token}


class Klass(object):
    """One java class: the doc name it came from, its package and its (wire name, type) fields."""

    def __init__(self, java, pkg, wire, doc):
        self.java = java
        self.pkg = pkg
        self.wire = wire
        self.doc = doc
        self.generated = False
        self.fields = []     # [(wire name, parsed type)]
        self.members = []    # [(wire name, java name, java type)]

    @property
    def fqn(self):
        return '%s.%s' % (self.pkg, self.java)

    def resolve(self, registry):
        self.members = []
        seen = {}
        for wire, parsed in self.fields:
            name = java_field(wire)
            if name in seen:
                raise Error('%s: fields %s and %s both map to java field %s'
                            % (self.java, seen[name], wire, name))
            seen[name] = wire
            self.members.append((wire, name, registry.java_of(parsed, self)))


class Registry(object):
    """Every java class the generator may reference, plus doc type resolution."""

    def __init__(self, naming):
        self.alias = naming.get('typeAliases', {})
        self.scalar_names = naming.get('scalarTypeNames', {})
        self.classes = collections.OrderedDict()
        self.constant_refs = {}     # doc type name -> constant holder class
        self.unresolved = collections.OrderedDict()
        self.untyped = collections.OrderedDict()

    def add(self, klass):
        clash = self.classes.get(klass.java)
        if clash is not None and clash is not klass:
            raise Error('duplicate java class name %s (%s and %s)' % (klass.java, clash.fqn, klass.fqn))
        self.classes[klass.java] = klass
        return klass

    def java_name_of(self, doc_name):
        return self.alias.get(doc_name, doc_name)

    def ref_name(self, doc_name):
        """A doc type in a type column: a model class, a scalar, or nothing we can map."""
        name = self.java_name_of(doc_name)
        if name in self.constant_refs:
            return 'Long'
        if name in self.scalar_names:
            return self.scalar_names[name]
        return name if name in self.classes else None

    def java_of(self, parsed, owner):
        kind = parsed.get('kind')
        if kind == 'scalar':
            return parsed['java']
        if kind == 'map':
            return 'Map<String, %s>' % self.java_of(parsed['value'], owner)
        if kind == 'object':
            return 'Map<String, Object>'
        if kind == 'array':
            return 'List<%s>' % self.java_of(parsed['item'], owner)
        if kind == 'unknown':
            self.untyped[owner.java] = self.untyped.get(owner.java, 0) + 1
            return 'Map<String, Object>'
        if kind != 'ref':
            return 'String'
        name = self.ref_name(parsed['name'])
        if name in SCALAR_TYPES:
            return name
        if name is None:
            self.unresolved[parsed['name']] = owner.java
            return 'Map<String, Object>'
        return name


def imports_for(java_type, registry, owner=None):
    """Imports a declaration needs: every named type inside it that lives in another package."""
    out = set()
    for token in TOKEN_RE.findall(java_type):
        if token in JDK_TYPES:
            continue
        klass = registry.classes.get(token)
        if klass is not None:
            out.add(klass.fqn)
        elif '.' in token:
            out.add(token)
    if 'List<' in java_type:
        out.add('java.util.List')
    if 'Map<' in java_type:
        out.add('java.util.Map')
    if owner is not None:
        out.discard(owner.fqn)
    return {i for i in out if i}


# --------------------------------------------------------------------------------------
# spec reading and endpoint hygiene
# --------------------------------------------------------------------------------------

def segments(path):
    return [s for s in path.split('/') if s]


def shape_matches(template, concrete):
    return (len(template) == len(concrete)
            and all(part.startswith('{') and part.endswith('}') or part == other
                    for part, other in zip(template, concrete)))


def hygiene(spec):
    """Split the crawled endpoints into templated operations and their repeated example paths."""
    endpoints = spec['endpoints']
    templates = [(e['method'], segments(e['path'])) for e in endpoints if '{' in e['path']]
    keep, dropped = [], []
    for endpoint in endpoints:
        concrete = segments(endpoint['path'])
        if '{' not in endpoint['path'] and any(m == endpoint['method'] and shape_matches(t, concrete)
                                               for m, t in templates):
            dropped.append(endpoint)
        else:
            keep.append(endpoint)
    order = lambda e: (e['path'], e['method'])
    return sorted(keep, key=order), sorted(dropped, key=order)


def path_params(endpoint):
    return PATH_ARG_RE.findall(endpoint['path'])


def usable_field(field):
    name = (field.get('name') or '').strip()
    if not LOWER_IDENT_RE.match(name) or name in META_INFO_KEYS:
        return False
    return parse_type(field.get('type')).get('kind') != 'file'


def info_fields(endpoint):
    """The server-inter pages keep their parameter table in `info`, not in body/queryParams."""
    out = []
    for name, value in (endpoint.get('info') or {}).items():
        if not LOWER_IDENT_RE.match(name) or not isinstance(value, str) or '\t' not in value:
            continue
        head, _, tail = value.partition('\t')
        out.append({'name': name, 'type': head.strip(), 'required': False, 'desc': tail.strip()})
    return out


def dedupe(fields, taken=()):
    out, seen = [], set(taken)
    for field in fields:
        name = field['name'].strip()
        if name in seen or not usable_field(field):
            continue
        seen.add(name)
        out.append(field)
    return out


def request_fields_of(endpoint, entry):
    if entry.get('noRequestFields'):
        # the page's parameter table documents a response object, not the call
        return []
    override = entry.get('requestFields')
    if override:
        return dedupe([dict(f) for f in override])
    raw = dedupe(list(endpoint.get('body') or []) + list(endpoint.get('queryParams') or []))
    if not raw:
        raw = dedupe(info_fields(endpoint))
    return [f for f in raw if f['name'].strip() not in set(path_params(endpoint))]


def response_fields_of(endpoint, entry):
    override = entry.get('responseFields')
    if override:
        return dedupe([dict(f) for f in override])
    return dedupe(list(endpoint.get('response') or []))


def parse_fields(fields):
    return [(f['name'].strip(), parse_type(f.get('type'))) for f in fields]


def signature_of(fields):
    return [(wire, parsed.get('kind'), parsed.get('java'), parsed.get('name'))
            for wire, parsed in fields]


# --------------------------------------------------------------------------------------
# value tables, shared models, event payloads
# --------------------------------------------------------------------------------------

def build_constants(naming, spec, registry):
    out = []
    for doc_name, cfg in sorted(naming.get('constants', {}).items()):
        java = cfg['java']
        values = collections.OrderedDict(cfg.get('values') or {})
        if not values:
            for field in spec['types'].get(doc_name, []):
                name = field['name'].strip()
                if not UPPER_RE.match(name):
                    continue
                number = re.match(r'^(0[xX][0-9a-fA-F]+|\d+)', field['type'].strip())
                if not number:
                    continue
                values[name] = int(number.group(1), 0)
            if not values:
                raise Error('constant %s has neither curated values nor parsable rows' % doc_name)
        doc = cfg.get('doc', 'Values of the %s table in the official API v2 docs.' % doc_name)
        out.append((java, doc, values))
        registry.constant_refs[doc_name] = java
    return out


def build_shared_models(spec, naming, registry):
    skip = set(naming.get('skipTypes', []))
    overrides = naming.get('typeFieldOverrides', {})
    constants = set(naming.get('constants', {}))

    def fields_for(doc_name, raw_fields):
        fields = [dict(f) for f in raw_fields]
        for name, java_type in sorted(overrides.get(doc_name, {}).items()):
            matched = False
            for field in fields:
                if field['name'].strip() == name:
                    field['type'] = java_type
                    matched = True
            if not matched:
                raise Error('typeFieldOverrides: %s documents no field %s' % (doc_name, name))
        return parse_fields(dedupe(fields))

    def register(doc_name, fields, doc):
        if doc_name in skip or doc_name in constants or not IDENT_RE.match(doc_name):
            return
        java = registry.java_name_of(doc_name)
        existing = registry.classes.get(java)
        if existing is not None:
            if not existing.fields and fields:
                existing.fields = fields
            return
        registry.add(Klass(java, MODEL_PKG, doc_name, doc)).fields = fields

    for doc_name in sorted(spec['types']):
        register(doc_name, fields_for(doc_name, spec['types'][doc_name]),
                 'Shared %s object from the official API v2 docs.' % doc_name)
    for source in list(spec['endpoints']) + list(spec['events']):
        for doc_name, raw in (source.get('types') or {}).items():
            register(doc_name, fields_for(doc_name, raw),
                     'Shared %s object from the official API v2 docs.' % doc_name)
    for klass in registry.classes.values():
        if not klass.fields:
            raise Error('model %s (%s) documents no usable field' % (klass.java, klass.wire))


def build_events(spec, registry):
    out = []
    for event in spec['events']:
        name = (event.get('info') or {}).get(u'\u4e8b\u4ef6\u540d')
        if not name:
            raise Error('an event page documents no event name (%s)' % event['file'])
        java = upper_camel(name)
        intent = (event.get('info') or {}).get('Intent') or ''
        doc = u'%s, the payload of the %s event (intent {@code %s}).' % (java, name, intent)
        klass = registry.add(Klass(java, EVENT_PKG, name, doc))
        klass.fields = parse_fields(dedupe(event.get('body') or []))
        out.append(klass)
    return out


def role_keys(entry, role):
    raw = entry.get(role) or []
    if isinstance(raw, str):
        raw = [raw]
    for key in raw:
        if not LOWER_IDENT_RE.match(key):
            raise Error('eventRoles %s: %s must name one payload key, got %r' % (entry.get('_name'), role, key))
    return list(dict.fromkeys(raw))


def build_event_roles(naming, crawled):
    """naming.json's eventRoles, checked against the crawled event names.

    Every event the gateway can push is listed here rather than derived: the envelope a dispatch is built into
    is what a handler's parameter type means, so it has be a decided fact, not a prefix match.
    """
    roles = naming.get('eventRoles')
    if not roles:
        raise Error('naming.json must curate eventRoles: the envelope of each event plus its actor/subject keys')
    rows = []
    for name, entry in roles.items():
        if name.startswith('_'):
            continue
        if not UPPER_RE.match(name):
            raise Error('eventRoles: %r is not an event name' % name)
        unknown = set(entry) - set(('envelope', 'actor', 'subject', 'doc'))
        if unknown:
            raise Error('eventRoles %s: unknown keys %s' % (name, ', '.join(sorted(unknown))))
        envelope = entry.get('envelope', 'PLAIN')
        if envelope not in ENVELOPES:
            raise Error('eventRoles %s: envelope must be one of %s, got %r'
                        % (name, ' '.join(ENVELOPES), envelope))
        entry = dict(entry, _name=name)
        rows.append(RoutingRow(name, envelope, role_keys(entry, 'actor'), role_keys(entry, 'subject'),
                               (entry.get('doc') or '').strip()))
    missing = sorted(k.wire for k in crawled if k.wire not in roles)
    if missing:
        raise Error('eventRoles has no row for the crawled events: %s' % ', '.join(missing))
    return rows


# --------------------------------------------------------------------------------------
# operations
# --------------------------------------------------------------------------------------

class Operation(object):

    def __init__(self, key, endpoint, entry, group_class):
        self.key = key
        self.endpoint = endpoint
        self.entry = entry
        self.title = entry.get('title') or endpoint.get('title') or ''
        self.doc = entry['doc']
        self.name = entry['method']
        self.group = entry['group']
        self.group_class = group_class
        self.const = const_name(entry['method'])
        self.http_method = endpoint['method']
        self.path = endpoint['path']
        self.path_names = path_params(endpoint)
        self.request_fields = request_fields_of(endpoint, entry)
        self.response_fields = response_fields_of(endpoint, entry)
        self.args = []              # [(java type, java name)] in signature order
        self.queries = []           # [(wire name, java name)] flattened into query parameters
        self.body_var = None        # java expression handed to execute() as the body
        self.body_locals = []       # statements that build a flattened body
        self.returns = 'void'
        self.response_literal = 'Void.class'
        self.response_generic = 'Void'
        self.request_class = None
        self.response_class = None

    def signature_imports(self):
        out = {PARAMS, ENDPOINTS}
        for java_type, _name in self.args:
            out |= imports_for(java_type, REGISTRY)
        out |= imports_for(self.returns, REGISTRY)
        for klass in (self.request_class, self.response_class):
            if klass is not None and klass.pkg != API_PKG:
                out.add(klass.fqn)
        return out


class DtoIndex(object):
    """Generated DTOs, so two operations may share one when their documented shape matches."""

    def __init__(self, registry):
        self.registry = registry
        self.seen = {}

    def get(self, pkg, java, op, fields, doc):
        slot = (pkg, java)
        shape = signature_of(fields)
        existing = self.seen.get(slot)
        if existing is not None:
            if existing['shape'] and shape and existing['shape'] != shape:
                raise Error('%s.%s is built for %s from %s but %s documents %s'
                            % (pkg, java, existing['key'], [s[0] for s in existing['shape']],
                               op.key, [s[0] for s in shape]))
            if not existing['shape'] and shape:
                existing['shape'] = shape
                self.registry.classes[java].fields = fields
            return self.registry.classes[java]
        klass = self.registry.classes.get(java)
        if klass is not None and klass.pkg != pkg:
            raise Error('%s %s clashes with %s' % (op.key, java, klass.fqn))
        if klass is not None:
            current = signature_of(klass.fields)
            if shape and current and shape != current:
                raise Error('%s: model %s already exists with fields %s'
                            % (op.key, java, [s[0] for s in current]))
            if not current:
                raise Error('%s: model %s is empty and cannot be reused as a dto' % (op.key, java))
            self.seen[slot] = {'key': op.key, 'shape': current}
            return klass
        created = self.registry.add(Klass(java, pkg, op.key, doc))
        created.fields = fields
        created.generated = True
        if not fields:
            raise Error('%s: dto %s documents no field' % (op.key, java))
        self.seen[slot] = {'key': op.key, 'shape': shape}
        return created


def _group_by_path(endpoints):
    groups = collections.OrderedDict()
    for endpoint in endpoints:
        groups.setdefault('%s %s' % (endpoint['method'], endpoint['path']), []).append(endpoint)
    return groups


def build_operations(spec, naming, keep):
    entries = naming['endpoints']
    groups = naming['apiGroups']
    known = collections.OrderedDict()
    for base, recs in _group_by_path(keep).items():
        if len(recs) == 1:
            known[base] = recs[0]
            continue
        # one path can carry several operations (guild mute vs batch member mute); the naming key of
        # the later ones is suffixed with the request fields that make them distinct
        shapes = [set(f['name'] for f in (r.get('body') or [])) for r in recs]
        common = set.intersection(*shapes)
        for rec, shape in zip(recs, shapes):
            extra = sorted(shape - common)
            key = base if not extra else base + '#' + '_'.join(extra)
            if key in known:
                raise Error('%s is documented twice with an identical request shape' % key)
            known[key] = rec
    missing = sorted(set(known) - set(entries))
    stale = sorted(set(entries) - set(known))
    if missing:
        raise Error('\n'.join(['naming.json has no entry for %d operation(s):' % len(missing)]
                              + ['  %s' % key for key in missing]))
    if stale:
        raise Error('\n'.join(['naming.json names %d operation(s) spec.json does not have:' % len(stale)]
                              + ['  %s' % key for key in stale]))
    counter = collections.Counter(entry['method'] for entry in entries.values())
    clash = sorted(name for name, count in counter.items() if count > 1)
    if clash:
        raise Error('method names reused across operations: %s' % ', '.join(clash))
    for key, entry in entries.items():
        for required in ('method', 'group', 'doc'):
            if not entry.get(required):
                raise Error('%s: %s is required' % (key, required))
        if not IDENT_RE.match(entry['method']):
            raise Error('%s: bad method name %r' % (key, entry['method']))
        if entry['group'] not in groups:
            raise Error('%s: unknown group %r' % (key, entry['group']))
    order = sorted(entries, key=lambda k: (list(groups).index(entries[k]['group']),
                                           known[k]['path'], known[k]['method']))
    return [Operation(key, known[key], entries[key], groups[entries[key]['group']]) for key in order]


def shape_operation(op, registry, dtos):
    op.args = [('String', java_field(name)) for name in op.path_names]
    shape_request(op, registry, dtos)
    shape_response(op, registry, dtos)


def shape_request(op, registry, dtos):
    fields = parse_fields(op.request_fields)
    named = op.entry.get('request')
    sends_body = op.http_method in BODY_METHODS
    if named:
        java = registry.java_name_of(named)
        target = registry.classes.get(java)
        if target is not None and target.pkg == MODEL_PKG:
            if fields and signature_of(fields) != signature_of(target.fields):
                raise Error('%s documents %s which do not match the model %s'
                            % (op.key, [w for w, _ in fields], java))
            op.args.append((java, decapitalize(java)))
            op.request_class = target
            op.body_var = decapitalize(java)
            return
        klass = dtos.get(REQUEST_PKG, java, op, fields,
                         'Request body of %s.' % _operation_doc_label(op))
        op.args.append((java, 'request'))
        op.request_class = klass
        op.body_var = 'request'
        return
    if not fields:
        return
    scalars = [(wire, parsed) for wire, parsed in fields
               if parsed.get('kind') == 'scalar' and parsed['java'] in SCALAR_TYPES]
    if len(scalars) != len(fields):
        raise Error('%s: parameters %s are not all scalar, name a request or query class'
                    % (op.key, [w for w, _ in fields if (w, ) not in [(s[0], ) for s in scalars]]))
    if not sends_body:
        for wire, parsed in scalars:
            op.args.append((parsed['java'], java_field(wire)))
            op.queries.append((wire, java_field(wire)))
        op.body_var = 'null'
        return
    if len(scalars) > MAX_FLATTENED_BODY_FIELDS:
        raise Error('%s: %d body fields are too many to flatten, name a request class'
                    % (op.key, len(scalars)))
    java = op.name[:1].upper() + op.name[1:] + 'Request'
    klass = dtos.get(REQUEST_PKG, java, op, scalars,
                     'Request body of %s.' % _operation_doc_label(op))
    op.request_class = klass
    var = 'request'
    op.body_var = var
    op.body_locals = ['        %s %s = new %s();' % (java, var, java)]
    for wire, parsed in scalars:
        op.args.append((parsed['java'], java_field(wire)))
        op.body_locals.append('        %s.%s = %s;' % (var, java_field(wire), java_field(wire)))


def _operation_doc_label(op):
    return '%s %s' % (op.http_method, op.path)


def shape_response(op, registry, dtos):
    named = op.entry.get('response')
    if not named or named == 'void':
        if op.entry.get('responseFields'):
            raise Error('%s: responseFields curated but the response is void' % op.key)
        return
    if '.' in named:
        op.returns = op.response_generic = named
        op.response_literal = named + '.class'
        return
    if named.startswith('[]'):
        inner = registry.java_name_of(named[2:])
        if inner not in registry.classes:
            raise Error('%s: unknown response element %s' % (op.key, named))
        op.returns = op.response_generic = 'List<%s>' % inner
        op.response_literal = 'Endpoint.listOf(%s.class)' % inner
        op.response_class = registry.classes[inner]
        return
    java = registry.java_name_of(named)
    fields = parse_fields(op.response_fields)
    existing = registry.classes.get(java)
    if existing is not None and existing.pkg == MODEL_PKG:
        if fields and signature_of(fields) != signature_of(existing.fields):
            raise Error('%s: response %s is a shared model but documents %s instead of %s'
                        % (op.key, java, [w for w, _ in fields], [w for w, _ in existing.fields]))
        op.returns = op.response_generic = java
        op.response_literal = '%s.class' % java
        op.response_class = existing
        return
    if existing is not None:
        raise Error('%s: response %s resolves to %s, which is not a model'
                    % (op.key, java, existing.fqn))
    if not fields:
        raise Error('%s: response %s is not a documented type and no responseFields were curated'
                    % (op.key, named))
    klass = dtos.get(MODEL_PKG, java, op, fields,
                     '%s: response of %s.' % (pretty(java), _operation_doc_label(op)))
    op.returns = op.response_generic = java
    op.response_literal = '%s.class' % java
    op.response_class = klass


# --------------------------------------------------------------------------------------
# java emission
# --------------------------------------------------------------------------------------

def package_dir(pkg):
    return os.path.join(SRC_ROOT, *pkg.split('.'))


def write_java(pkg, java_name, text):
    if 'package %s;\n' % pkg not in text:
        raise Error('%s.%s was emitted without its package declaration' % (pkg, java_name))
    directory = package_dir(pkg)
    if not os.path.isdir(directory):
        os.makedirs(directory)
    path = os.path.join(directory, java_name + '.java')
    with open(path, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(BANNER + text)
    return path


def clean_generated_packages(packages):
    for pkg in packages:
        directory = package_dir(pkg)
        if not os.path.isdir(directory):
            os.makedirs(directory)
            continue
        for name in os.listdir(directory):
            if name.endswith('.java'):
                os.remove(os.path.join(directory, name))


def docstring(text, indent=''):
    text = (text or '').strip().replace('\r', ' ').replace('\n', ' ')
    text = text.replace('*/', '* /')
    text = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    if not text:
        return ''
    if not text.endswith('.'):
        text += '.'
    if len(text) + len(indent) <= WRAP_AT:
        return '%s/** %s */\n' % (indent, text)
    lines = textwrap.wrap(text, width=max(40, WRAP_AT - len(indent)))
    out = '%s/**\n' % indent
    out += ''.join('%s * %s\n' % (indent, line) for line in lines)
    return out + '%s */\n' % indent


def imports_block(imports, pkg):
    keep = sorted(i for i in imports if i and i.rsplit('.', 1)[0] != pkg
                  and not i.startswith('java.lang.'))
    if not keep:
        return ''
    third = [i for i in keep if not i.startswith('java.')]
    jdk = [i for i in keep if i.startswith('java.')]
    out = ''.join('import %s;\n' % i for i in third)
    if third and jdk:
        out += '\n'
    return out + ''.join('import %s;\n' % i for i in jdk) + '\n'


def emit_model(klass):
    imports = {SERIALIZED}
    for _wire, _name, java_type in klass.members:
        imports |= imports_for(java_type, REGISTRY, klass)
    fields = ''
    for wire, name, java_type in klass.members:
        fields += '\n    @SerializedName("%s")\n    public %s %s;\n' % (wire, java_type, name)
    text = ('package %s;\n\n%s%spublic class %s {\n%s\n    public %s() {\n    }\n}\n'
            % (klass.pkg, imports_block(imports, klass.pkg), docstring(klass.doc), klass.java,
               fields, klass.java))
    return write_java(klass.pkg, klass.java, text)


def emit_constant(java, doc, values):
    lines = ['package %s;\n\n' % CONSTANT_PKG, docstring(doc), 'public final class %s {\n' % java]
    for name, value in sorted(values.items(), key=lambda kv: (kv[1], kv[0])):
        lines.append('\n    public static final int %s = %d;\n' % (name, value))
    lines.append('\n    private %s() {\n    }\n}\n' % java)
    return write_java(CONSTANT_PKG, java, ''.join(lines))


EVENT_ROVALS_DOC = (
    'Routing facts docgen writes from naming.json\u0027s eventRoles: the envelope each event name is built into, '
    'and the payload keys that name the people taking part in it. A handler parameter type means one of these '
    'envelopes, so adding an event is a row here rather than a guess somewhere in the bus.')


def emit_event_roles(rows):
    out = ['package %s;\n\n' % EVENT_ROOT_PKG]
    out.append(imports_block(['java.util.ArrayList', 'java.util.Collections', 'java.util.LinkedHashMap',
                              'java.util.List', 'java.util.Map'], EVENT_ROOT_PKG))
    out.append(docstring(EVENT_ROVALS_DOC))
    out.append('public final class EventRouting {\n')
    out.append('\n    /** The envelope a dispatch is built into. */\n    public enum Envelope {\n')
    for envelope, doc in EVENT_ENVELOPES.items():
        out.append('\n' + docstring(doc, '        '))
        out.append('        %s,\n' % envelope)
    out = ''.join(out).rsplit(',\n', 1)[0] + '\n    }\n'
    out += '\n' + docstring('One event: its envelope plus the payload keys that name the people taking part.')
    out += '''    public static final class Row {

        static final Row UNKNOWN = new Row("UNKNOWN", Envelope.PLAIN, List.of(), List.of());

        private final String name;
        private final Envelope envelope;
        private final List<String> actorKeys;
        private final List<String> subjectKeys;

        Row(String name, Envelope envelope, List<String> actorKeys, List<String> subjectKeys) {
            this.name = name;
            this.envelope = envelope;
            this.actorKeys = actorKeys;
            this.subjectKeys = subjectKeys;
        }

        /** The {@code t} value of this row, or {@code UNKNOWN} for a name the table does not place. */
        public String name() {
            return name;
        }

        public Envelope envelope() {
            return envelope;
        }

        /** Who set the event off, by payload key in preference order; empty when no key names one. */
        public List<String> actorKeys() {
            return actorKeys;
        }

        /** Who the event happened to, by payload key in preference order; empty when no key names one. */
        public List<String> subjectKeys() {
            return subjectKeys;
        }
    }

    private static final Map<String, Row> BY_NAME = rows();

    private static Map<String, Row> rows() {
        Map<String, Row> rows = new LinkedHashMap<>();
'''
    for row in rows:
        doc = (' ' + row.doc) if row.doc else ''
        out += '        // %s%s\n' % (row.envelope, doc)
        out += '        rows.put("%s", new Row("%s", Envelope.%s, %s, %s));\n' % (
            row.name, row.name, row.envelope, java_list(row.actor), java_list(row.subject))
    out += '''        return Collections.unmodifiableMap(rows);
    }

    /** {@code eventName}'s row; a {@link Envelope#PLAIN} row for names newer than this table. */
    public static Row of(String eventName) {
        return eventName == null ? Row.UNKNOWN : BY_NAME.getOrDefault(eventName, Row.UNKNOWN);
    }

    /** The modelled events built into {@code envelope}, in the order this table lists them. */
    public static List<EventType> eventTypes(Envelope envelope) {
        List<EventType> types = new ArrayList<>();
        for (Row row : BY_NAME.values()) {
            if (row.envelope == envelope) {
                EventType type = EventType.from(row.name);
                if (type != EventType.UNKNOWN) {
                    types.add(type);
                }
            }
        }
        return List.copyOf(types);
    }

    private EventRouting() {
    }
}
'''
    return write_java(EVENT_ROOT_PKG, 'EventRouting', out)


def java_list(keys):
    return 'List.of(%s)' % ', '.join('"%s"' % key for key in keys) if keys else 'List.of()'



def params_steps(op):
    steps = ['.pathValue("%s", %s)' % (name, java_field(name)) for name in op.path_names]
    steps += ['.queryValue("%s", %s)' % (wire, name) for wire, name in op.queries]
    return steps


def params_chain(op, indent=''):
    """The Params expression of a call, one step per line once it stops fitting on one."""
    steps = params_steps(op)
    one_line = 'Params.of()' + ''.join(steps)
    if not steps or len(indent) + len(one_line) <= LONG_LINE:
        return one_line
    return 'Params.of()' + ''.join('\n%s        %s' % (indent, step) for step in steps)


def emit_method(op):
    params = ['%s %s' % pair for pair in op.args]
    head = '    public %s %s(%s) {' % (op.returns, op.name, ', '.join(params))
    if len(head) > LONG_LINE and len(params) > 1:
        head = ('    public %s %s(\n            %s) {'
                % (op.returns, op.name, ',\n            '.join(params)))
    body_arg = op.body_var or 'null'
    call = 'http.execute(Endpoints.%s, %s, %s);' % (op.const, params_chain(op), body_arg)
    if len('        ' + call) > LONG_LINE:
        call = ('http.execute(Endpoints.%s,\n                %s,\n                %s);'
                % (op.const, params_chain(op, ' ' * 16), body_arg))
    statements = list(op.body_locals)
    statements.append('        %s%s' % ('return ' if op.returns != 'void' else '', call))
    return '\n' + docstring(op.doc, '    ') + head + '\n' + '\n'.join(statements) + '\n    }\n'


def emit_api(java_name, doc, operations):
    imports = {HTTP_TRANSPORT, OBJECTS}
    for op in operations:
        imports |= op.signature_imports()
    text = ('package %s;\n\n%s%s'
            'public final class %s {\n\n'
            '    private final HttpTransport http;\n\n'
            '    public %s(HttpTransport http) {\n'
            '        this.http = Objects.requireNonNull(http, "http");\n'
            '    }\n%s\n}\n'
            % (API_PKG, imports_block(imports, API_PKG), docstring(doc), java_name, java_name,
               ''.join(emit_method(op) for op in operations)))
    return write_java(API_PKG, java_name, text)


def emit_endpoints(operations):
    imports = {ENDPOINT}
    lines = []
    current = None
    for op in operations:
        if op.group_class != current:
            current = op.group_class
            lines.append('\n    // ---- %s ----\n' % current)
        imports |= imports_for(op.response_generic, REGISTRY)
        if op.request_class is not None:
            imports.add(op.request_class.fqn)
        lines.append('    public static final Endpoint<%s> %s = Endpoint.of(Endpoint.Method.%s, "%s", %s);\n'
                     % (op.response_generic, op.const, op.http_method, op.path, op.response_literal))
    text = ('package %s;\n\n%s'
            '/** One constant per documented operation; they are the vocabulary of the API classes. */\n'
            'public final class Endpoints {\n\n'
            '    private Endpoints() {\n    }\n%s\n}\n'
            % (ENDPOINT_PKG, imports_block(imports, ENDPOINT_PKG), ''.join(lines)))
    return write_java(ENDPOINT_PKG, 'Endpoints', text)


def emit_facade(api_groups):
    imports = {HTTP_TRANSPORT, OBJECTS}
    fields, ctor, accessor_out = [], [], []
    for group, java_name in api_groups.items():
        accessor = API_ACCESSORS[group]
        imports.add('%s.%s' % (API_PKG, java_name))
        fields.append('    private final %s %s;\n' % (java_name, accessor))
        ctor.append('        %s = new %s(http);\n' % (accessor, java_name))
        accessor_out.append('\n' + docstring('%s operations.' % pretty(java_name[:-3]), '    ')
                            + '    public %s %s() {\n        return %s;\n    }\n'
                              % (java_name, accessor, accessor))
    accessor_out.append('\n' + docstring('The transport every group class shares.', '    ')
                        + '    public HttpTransport http() {\n        return http;\n    }\n')
    text = ('package %s;\n\n%s%s'
            'public final class Api {\n\n'
            '    private final HttpTransport http;\n\n'
            '%s'
            '    public Api(HttpTransport http) {\n'
            '        this.http = Objects.requireNonNull(http, "http");\n'
            '%s    }\n%s\n}\n'
            % (API_PKG, imports_block(imports, API_PKG),
               docstring('Typed entry point to every REST operation of the QQ Open Platform v2 API.'),
               ''.join(fields) + '\n', ''.join(ctor), ''.join(accessor_out)))
    return write_java(API_PKG, 'Api', text)


# --------------------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------------------

REGISTRY = None


def main():
    global REGISTRY
    with open(SPEC_PATH, encoding='utf-8') as handle:
        spec = json.load(handle)
    with open(NAMING_PATH, encoding='utf-8') as handle:
        naming = json.load(handle)

    keep, dropped = hygiene(spec)
    print('spec endpoints        : %d' % len(spec['endpoints']))
    print('retained operations   : %d' % len(keep))
    for endpoint in keep:
        print('  KEEP  %-6s %s' % (endpoint['method'], endpoint['path']))
    print('dropped example paths : %d' % len(dropped))
    for endpoint in dropped:
        print('  DROP  %-6s %s' % (endpoint['method'], endpoint['path']))

    if set(naming['apiGroups']) != set(API_ACCESSORS) or set(naming['apiGroups']) != set(API_DOCS):
        raise Error('naming.json apiGroups must be exactly %s' % ', '.join(sorted(API_ACCESSORS)))
    registry = Registry(naming)
    REGISTRY = registry
    constants = build_constants(naming, spec, registry)
    build_shared_models(spec, naming, registry)
    events = build_events(spec, registry)
    roles = build_event_roles(naming, events)
    operations = build_operations(spec, naming, keep)
    dtos = DtoIndex(registry)
    for op in operations:
        shape_operation(op, registry, dtos)
    for klass in list(registry.classes.values()):
        klass.resolve(registry)
    if registry.unresolved:
        detail = ', '.join('%s (%s)' % pair for pair in sorted(registry.unresolved.items()))
        raise Error('unresolved doc type refs: %s' % detail)
    if registry.untyped:
        raise Error('the docs leave the element type of these arrays empty, curate them in '
                    'naming.json: %s'
                    % ', '.join('%s x%d' % pair for pair in sorted(registry.untyped.items())))

    packages = [MODEL_PKG, REQUEST_PKG, CONSTANT_PKG, EVENT_PKG, API_PKG, ENDPOINT_PKG]
    clean_generated_packages(packages)
    written = 0
    for java, doc, values in constants:
        emit_constant(java, doc, values)
        written += 1
    buckets = collections.OrderedDict((pkg, []) for pkg in packages)
    for klass in registry.classes.values():
        emit_model(klass)
        buckets[klass.pkg].append(klass)
        written += 1
    for group, java_name in naming['apiGroups'].items():
        emit_api(java_name, API_DOCS[group], [op for op in operations if op.group == group])
        written += 1
    emit_endpoints(operations)
    written += 1
    emit_facade(naming['apiGroups'])
    written += 1
    emit_event_roles(roles)
    written += 1

    counts = collections.Counter(op.group for op in operations)
    shared = [k for k in buckets[MODEL_PKG] if not k.generated]
    responses = [k for k in buckets[MODEL_PKG] if k.generated]
    print('')
    print('java files written    : %d' % written)
    print('  shared models       : %d' % len(shared))
    print('  response types      : %d' % len(responses))
    print('  request types       : %d' % len(buckets[REQUEST_PKG]))
    print('  constant holders    : %d  %s'
          % (len(constants), ' '.join(java for java, _, _ in constants)))
    print('  event payloads      : %d  %s'
          % (len(buckets[EVENT_PKG]), ' '.join(k.java for k in buckets[EVENT_PKG])))
    print('  routing rows        : %d  %s'
          % (len(roles), ' '.join('%s=%s' % (env, sum(1 for r in roles if r.envelope == env))
                                  for env in ENVELOPES)))
    print('  api classes         : %d  %s' % (len(naming['apiGroups']) + 2,
                                              'Api Endpoints ' + ' '.join(naming['apiGroups'].values())))
    print('  operations          : %d' % len(operations))
    for group, java_name in sorted(naming['apiGroups'].items(), key=lambda kv: kv[1]):
        print('    %-24s %2d' % (java_name, counts[group]))


if __name__ == '__main__':
    try:
        main()
    except Error as error:
        sys.stderr.write('gen_java: %s\n' % str(error))
        sys.exit(1)
