// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.event.model;

import com.google.gson.annotations.SerializedName;

/** C2CMsgReject, the payload of the C2C_MSG_REJECT event (intent {@code GROUP_AND_C2C_EVENT (1&lt;&lt;25)}). */
public class C2CMsgReject {

    @SerializedName("timestamp")
    public Long timestamp;

    @SerializedName("openid")
    public String openid;

    public C2CMsgReject() {
    }
}
