// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.event.model;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.ArkData;
import io.github.skiesworld.qqbot.model.MessageAttachment;
import io.github.skiesworld.qqbot.model.MessageScene;
import io.github.skiesworld.qqbot.model.MsgElement;
import io.github.skiesworld.qqbot.model.User;

import java.util.List;

/**
 * C2CMessageCreate, the payload of the C2C_MESSAGE_CREATE event (intent {@code GROUP_AND_C2C_EVENT
 * (1&lt;&lt;25)}).
 */
public class C2CMessageCreate {

    @SerializedName("id")
    public String id;

    @SerializedName("author")
    public User author;

    @SerializedName("content")
    public String content;

    @SerializedName("timestamp")
    public String timestamp;

    @SerializedName("message_type")
    public Long messageType;

    @SerializedName("message_scene")
    public MessageScene messageScene;

    @SerializedName("attachments")
    public List<MessageAttachment> attachments;

    @SerializedName("ark_data")
    public ArkData arkData;

    @SerializedName("msg_elements")
    public List<MsgElement> msgElements;

    public C2CMessageCreate() {
    }
}
