// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.event.model;

import com.google.gson.annotations.SerializedName;

/** ChannelUpdate, the payload of the CHANNEL_UPDATE event (intent {@code GUILDS (1&lt;&lt;0)}). */
public class ChannelUpdate {

    @SerializedName("id")
    public String id;

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("name")
    public String name;

    @SerializedName("type")
    public Long type;

    @SerializedName("sub_type")
    public Long subType;

    @SerializedName("owner_id")
    public String ownerId;

    @SerializedName("op_user_id")
    public String opUserId;

    public ChannelUpdate() {
    }
}
