// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.event.model;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.FriendAuthor;

/** FriendDel, the payload of the FRIEND_DEL event (intent {@code GROUP_AND_C2C_EVENT (1&lt;&lt;25)}). */
public class FriendDel {

    @SerializedName("timestamp")
    public Long timestamp;

    @SerializedName("openid")
    public String openid;

    @SerializedName("author")
    public FriendAuthor author;

    public FriendDel() {
    }
}
