// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.event.model;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.FriendAuthor;

/** FriendAdd, the payload of the FRIEND_ADD event (intent {@code GROUP_AND_C2C_EVENT (1&lt;&lt;25)}). */
public class FriendAdd {

    @SerializedName("timestamp")
    public Long timestamp;

    @SerializedName("openid")
    public String openid;

    @SerializedName("scene")
    public Long scene;

    @SerializedName("scene_param")
    public String sceneParam;

    @SerializedName("author")
    public FriendAuthor author;

    @SerializedName("short_code")
    public String shortCode;

    public FriendAdd() {
    }
}
