// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.event.model;

import com.google.gson.annotations.SerializedName;

/**
 * GroupMemberRemove, the payload of the GROUP_MEMBER_REMOVE event (intent {@code GROUP_MEMBER_EVENT
 * (1&lt;&lt;24)}).
 */
public class GroupMemberRemove {

    @SerializedName("timestamp")
    public Long timestamp;

    @SerializedName("group_openid")
    public String groupOpenid;

    @SerializedName("member_openid")
    public String memberOpenid;

    @SerializedName("user_openid")
    public String userOpenid;

    public GroupMemberRemove() {
    }
}
