// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.event.model;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.AutoAppproved;
import io.github.skiesworld.qqbot.model.VerifyInfo;

/**
 * GroupJoinRequest, the payload of the GROUP_JOIN_REQUEST event (intent {@code GROUP_MEMBER_EVENT
 * (1&lt;&lt;24)}).
 */
public class GroupJoinRequest {

    @SerializedName("group_openid")
    public String groupOpenid;

    @SerializedName("join_request_id")
    public String joinRequestId;

    @SerializedName("risk_tips")
    public String riskTips;

    @SerializedName("union_openid")
    public String unionOpenid;

    @SerializedName("member_openid")
    public String memberOpenid;

    @SerializedName("username")
    public String username;

    @SerializedName("apply_at")
    public String applyAt;

    @SerializedName("apply_source")
    public String applySource;

    @SerializedName("invited_by")
    public String invitedBy;

    @SerializedName("bot")
    public Boolean bot;

    @SerializedName("verify_info")
    public VerifyInfo verifyInfo;

    @SerializedName("auto_approved")
    public AutoAppproved autoApproved;

    public GroupJoinRequest() {
    }
}
