// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.event.model;

import com.google.gson.annotations.SerializedName;

/**
 * GroupMsgReject, the payload of the GROUP_MSG_REJECT event (intent {@code GROUP_AND_C2C_EVENT
 * (1&lt;&lt;25)}).
 */
public class GroupMsgReject {

    @SerializedName("timestamp")
    public Long timestamp;

    @SerializedName("group_openid")
    public String groupOpenid;

    @SerializedName("op_member_openid")
    public String opMemberOpenid;

    public GroupMsgReject() {
    }
}
