// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.event.model;

import com.google.gson.annotations.SerializedName;

/** GuildCreate, the payload of the GUILD_CREATE event (intent {@code GUILDS (1&lt;&lt;0)}). */
public class GuildCreate {

    @SerializedName("id")
    public String id;

    @SerializedName("name")
    public String name;

    @SerializedName("icon")
    public String icon;

    @SerializedName("owner_id")
    public String ownerId;

    @SerializedName("member_count")
    public Long memberCount;

    @SerializedName("max_members")
    public Long maxMembers;

    @SerializedName("description")
    public String description;

    @SerializedName("joined_at")
    public String joinedAt;

    @SerializedName("op_user_id")
    public String opUserId;

    public GuildCreate() {
    }
}
