// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.event.model;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.InteractionData;

/** InteractionCreate, the payload of the INTERACTION_CREATE event (intent {@code INTERACTION (1&lt;&lt;26)}). */
public class InteractionCreate {

    @SerializedName("id")
    public String id;

    @SerializedName("type")
    public Long type;

    @SerializedName("scene")
    public String scene;

    @SerializedName("chat_type")
    public Long chatType;

    @SerializedName("timestamp")
    public String timestamp;

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("user_openid")
    public String userOpenid;

    @SerializedName("group_openid")
    public String groupOpenid;

    @SerializedName("group_member_openid")
    public String groupMemberOpenid;

    @SerializedName("data")
    public InteractionData data;

    @SerializedName("version")
    public Long version;

    @SerializedName("application_id")
    public String applicationId;

    public InteractionCreate() {
    }
}
