// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.event.model;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.SubscribeMsgTemplateResult;

import java.util.List;

/**
 * SubscribeMessageStatus, the payload of the SUBSCRIBE_MESSAGE_STATUS event (intent {@code GROUP_AND_C2C_EVENT
 * (1&lt;&lt;25)}).
 */
public class SubscribeMessageStatus {

    @SerializedName("group_openid")
    public String groupOpenid;

    @SerializedName("openid")
    public String openid;

    @SerializedName("result")
    public List<SubscribeMsgTemplateResult> result;

    public SubscribeMessageStatus() {
    }
}
