// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared Permission object from the official API v2 docs. */
public class ActionPermission {

    @SerializedName("type")
    public Long type;

    @SerializedName("specify_user_ids")
    public List<String> specifyUserIds;

    @SerializedName("specify_role_ids")
    public List<String> specifyRoleIds;

    public ActionPermission() {
    }
}
