// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared Modal object from the official API v2 docs. */
public class ActionModal {

    @SerializedName("content")
    public String content;

    @SerializedName("confirm_text")
    public String confirmText;

    @SerializedName("cancel_text")
    public String cancelText;

    public ActionModal() {
    }
}
