// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared Announces object from the official API v2 docs. */
public class Announces {

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("message_id")
    public String messageId;

    @SerializedName("announces_type")
    public Long announcesType;

    @SerializedName("recommend_channels")
    public List<RecommendChannel> recommendChannels;

    public Announces() {
    }
}
