// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared APIPermissionDemandIdentify object from the official API v2 docs. */
public class ApiPermissionDemandIdentify {

    @SerializedName("path")
    public String path;

    @SerializedName("method")
    public String method;

    public ApiPermissionDemandIdentify() {
    }
}
