// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared APIPermissionDemand object from the official API v2 docs. */
public class ApiPermissionDemand {

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("api_identify")
    public ApiPermissionDemandIdentify apiIdentify;

    @SerializedName("title")
    public String title;

    @SerializedName("desc")
    public String desc;

    public ApiPermissionDemand() {
    }
}
