// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared APIPermission object from the official API v2 docs. */
public class ApiPermission {

    @SerializedName("path")
    public String path;

    @SerializedName("method")
    public String method;

    @SerializedName("desc")
    public String desc;

    @SerializedName("auth_status")
    public Long authStatus;

    public ApiPermission() {
    }
}
