// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.Map;

/** Shared ARKData object from the official API v2 docs. */
public class ArkData {

    @SerializedName("prompt")
    public String prompt;

    @SerializedName("ark_type")
    public String arkType;

    @SerializedName("ark_name")
    public String arkName;

    @SerializedName("fields")
    public Map<String, Object> fields;

    public ArkData() {
    }
}
