// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared AtGuildInfo object from the official API v2 docs. */
public class AtGuildInfo {

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("guild_name")
    public String guildName;

    public AtGuildInfo() {
    }
}
