// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared AtInfo object from the official API v2 docs. */
public class AtInfo {

    @SerializedName("type")
    public Long type;

    @SerializedName("user_info")
    public AtUserInfo userInfo;

    @SerializedName("role_info")
    public AtRoleInfo roleInfo;

    @SerializedName("guild_info")
    public AtGuildInfo guildInfo;

    public AtInfo() {
    }
}
