// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared AtRoleInfo object from the official API v2 docs. */
public class AtRoleInfo {

    @SerializedName("role_id")
    public Long roleId;

    @SerializedName("name")
    public String name;

    @SerializedName("color")
    public Long color;

    public AtRoleInfo() {
    }
}
