// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared AudioControl object from the official API v2 docs. */
public class AudioControl {

    @SerializedName("audio_url")
    public String audioUrl;

    @SerializedName("text")
    public String text;

    @SerializedName("status")
    public Long status;

    public AudioControl() {
    }
}
