// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared AuditResult object from the official API v2 docs. */
public class AuditResult {

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("author_id")
    public String authorId;

    @SerializedName("thread_id")
    public String threadId;

    @SerializedName("post_id")
    public String postId;

    @SerializedName("reply_id")
    public String replyId;

    @SerializedName("type")
    public Long type;

    @SerializedName("result")
    public Long result;

    @SerializedName("err_msg")
    public String errMsg;

    public AuditResult() {
    }
}
