// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared AudioAction object from the official API v2 docs. */
public class AudioAction {

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("audio_url")
    public String audioUrl;

    @SerializedName("text")
    public String text;

    public AudioAction() {
    }
}
