// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared AuthorizeData object from the official API v2 docs. */
public class AuthorizeData {

    @SerializedName("opt_scene")
    public String optScene;

    @SerializedName("scope")
    public String scope;

    public AuthorizeData() {
    }
}
