// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared AutoAppproved object from the official API v2 docs. */
public class AutoAppproved {

    @SerializedName("strategy_id")
    public String strategyId;

    public AutoAppproved() {
    }
}
