// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Batch Remove Group Members Response: response of POST /v2/groups/{group_openid}/batch_remove_members. */
public class BatchRemoveGroupMembersResponse {

    @SerializedName("remove_members_result")
    public String removeMembersResult;

    @SerializedName("add_to_member_blacklist_fail_openids")
    public List<String> addToMemberBlacklistFailOpenids;

    public BatchRemoveGroupMembersResponse() {
    }
}
