// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared BlacklistUser object from the official API v2 docs. */
public class BlacklistUser {

    @SerializedName("union_openid")
    public String unionOpenid;

    @SerializedName("member_openid")
    public String memberOpenid;

    @SerializedName("username")
    public String username;

    @SerializedName("banned_at")
    public String bannedAt;

    @SerializedName("bot")
    public Boolean bot;

    public BlacklistUser() {
    }
}
