// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Bot Profile: response of GET /users/@me. */
public class BotProfile {

    @SerializedName("id")
    public String id;

    @SerializedName("username")
    public String username;

    @SerializedName("avatar")
    public String avatar;

    @SerializedName("bot")
    public Boolean bot;

    @SerializedName("union_openid")
    public String unionOpenid;

    @SerializedName("union_user_account")
    public String unionUserAccount;

    @SerializedName("share_url")
    public String shareUrl;

    @SerializedName("welcome_msg")
    public String welcomeMsg;

    public BotProfile() {
    }
}
