// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared Action object from the official API v2 docs. */
public class ButtonAction {

    @SerializedName("type")
    public Long type;

    @SerializedName("permission")
    public ActionPermission permission;

    @SerializedName("data")
    public String data;

    @SerializedName("click_limit")
    public Long clickLimit;

    @SerializedName("unsupport_tips")
    public String unsupportTips;

    @SerializedName("enter")
    public Boolean enter;

    @SerializedName("reply")
    public Boolean reply;

    @SerializedName("anchor")
    public Long anchor;

    @SerializedName("modal")
    public ActionModal modal;

    public ButtonAction() {
    }
}
