// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Channel Online Nums Response: response of GET /channels/{channel_id}/online_nums. */
public class ChannelOnlineNumsResponse {

    @SerializedName("online_nums")
    public Long onlineNums;

    public ChannelOnlineNumsResponse() {
    }
}
