// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Channel Role Permissions Response: response of GET /channels/{channel_id}/roles/{role_id}/permissions. */
public class ChannelRolePermissionsResponse {

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("role_id")
    public String roleId;

    @SerializedName("permissions")
    public String permissions;

    public ChannelRolePermissionsResponse() {
    }
}
