// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared ChannelInfo object from the official API v2 docs. */
public class ChannelInfo {

    @SerializedName("channel_id")
    public Long channelId;

    @SerializedName("channel_name")
    public String channelName;

    public ChannelInfo() {
    }
}
