// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Channel Member Permissions Response: response of GET /channels/{channel_id}/members/{user_id}/permissions. */
public class ChannelMemberPermissionsResponse {

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("user_id")
    public String userId;

    @SerializedName("permissions")
    public String permissions;

    public ChannelMemberPermissionsResponse() {
    }
}
