// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared Channel object from the official API v2 docs. */
public class Channel {

    @SerializedName("id")
    public String id;

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("name")
    public String name;

    @SerializedName("type")
    public Long type;

    @SerializedName("sub_type")
    public Long subType;

    @SerializedName("position")
    public Long position;

    @SerializedName("parent_id")
    public String parentId;

    @SerializedName("owner_id")
    public String ownerId;

    @SerializedName("private_type")
    public Long privateType;

    @SerializedName("speak_permission")
    public Long speakPermission;

    @SerializedName("application_id")
    public String applicationId;

    @SerializedName("permissions")
    public String permissions;

    public Channel() {
    }
}
