// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Create Join Approval Strategy Response: response of POST /v2/groups/join_approval_strategy. */
public class CreateJoinApprovalStrategyResponse {

    @SerializedName("strategy_id")
    public String strategyId;

    @SerializedName("is_enable")
    public String isEnable;

    @SerializedName("expire_at")
    public String expireAt;

    public CreateJoinApprovalStrategyResponse() {
    }
}
