// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Create Guild Role Response: response of POST /guilds/{guild_id}/roles. */
public class CreateGuildRoleResponse {

    @SerializedName("role_id")
    public String roleId;

    @SerializedName("role")
    public Role role;

    public CreateGuildRoleResponse() {
    }
}
