// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Create Panel Response: response of POST /v2/panels. */
public class CreatePanelResponse {

    @SerializedName("panel_id")
    public String panelId;

    public CreatePanelResponse() {
    }
}
