// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared DMS object from the official API v2 docs. */
public class Dms {

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("create_time")
    public String createTime;

    public Dms() {
    }
}
