// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared Emoji object from the official API v2 docs. */
public class Emoji {

    @SerializedName("id")
    public String id;

    @SerializedName("type")
    public Long type;

    public Emoji() {
    }
}
