// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared EmojiInfo object from the official API v2 docs. */
public class EmojiInfo {

    @SerializedName("id")
    public String id;

    @SerializedName("type")
    public String type;

    @SerializedName("name")
    public String name;

    @SerializedName("url")
    public String url;

    public EmojiInfo() {
    }
}
