// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared FriendAuthor object from the official API v2 docs. */
public class FriendAuthor {

    @SerializedName("union_openid")
    public String unionOpenid;

    public FriendAuthor() {
    }
}
