// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared GlobalMuteRule object from the official API v2 docs. */
public class GlobalMuteRule {

    @SerializedName("mode")
    public String mode;

    @SerializedName("schedule_rules")
    public List<MuteScheduleRule> scheduleRules;

    @SerializedName("recurring_rules")
    public List<MuteRecurringRule> recurringRules;

    public GlobalMuteRule() {
    }
}
