// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Group Mute State Response: response of GET /v2/groups/{group_openid}/restrict_chat_setting. */
public class GroupMuteStateResponse {

    @SerializedName("global_rule")
    public GlobalMuteRule globalRule;

    @SerializedName("members")
    public List<MemberMuteState> members;

    public GroupMuteStateResponse() {
    }
}
