// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared Member object from the official API v2 docs. */
public class GroupMember {

    @SerializedName("member_openid")
    public String memberOpenid;

    @SerializedName("username")
    public String username;

    @SerializedName("member_role")
    public String memberRole;

    @SerializedName("bot")
    public Boolean bot;

    @SerializedName("joined_at")
    public String joinedAt;

    @SerializedName("union_openid")
    public String unionOpenid;

    public GroupMember() {
    }
}
