// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Group Bot State: response of GET /v2/groups/{group_openid}/bot_state. */
public class GroupBotState {

    @SerializedName("member_openid")
    public String memberOpenid;

    @SerializedName("joined_at")
    public String joinedAt;

    @SerializedName("allow_proactive_msg")
    public Boolean allowProactiveMsg;

    @SerializedName("recv_msg_setting")
    public String recvMsgSetting;

    @SerializedName("member_role")
    public String memberRole;

    public GroupBotState() {
    }
}
