// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Group Member List Response: response of GET /v2/groups/{group_openid}/members. */
public class GroupMemberListResponse {

    @SerializedName("members")
    public List<GroupMember> members;

    @SerializedName("next_cursor")
    public String nextCursor;

    public GroupMemberListResponse() {
    }
}
