// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Group Blacklist Response: response of GET /v2/groups/{group_openid}/member_blacklist. */
public class GroupBlacklistResponse {

    @SerializedName("users")
    public List<BlacklistUser> users;

    @SerializedName("next_cursor")
    public String nextCursor;

    public GroupBlacklistResponse() {
    }
}
