// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared GroupAction object from the official API v2 docs. */
public class GroupAction {

    @SerializedName("op")
    public String op;

    @SerializedName("group_openids")
    public List<String> groupOpenids;

    @SerializedName("group_ids")
    public List<String> groupIds;

    public GroupAction() {
    }
}
