// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Group Blacklist Operation Response: response of POST /v2/groups/{group_openid}/member_blacklist. */
public class GroupBlacklistOperationResponse {

    @SerializedName("fail_openids")
    public List<String> failOpenids;

    public GroupBlacklistOperationResponse() {
    }
}
