// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Group Join Request List Response: response of GET /v2/groups/{group_openid}/join_request_list. */
public class GroupJoinRequestListResponse {

    @SerializedName("list")
    public List<JoinRequest> list;

    @SerializedName("next_cursor")
    public String nextCursor;

    public GroupJoinRequestListResponse() {
    }
}
