// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Group Info: response of GET /v2/groups/{group_openid}/info. */
public class GroupInfo {

    @SerializedName("group_openid")
    public String groupOpenid;

    @SerializedName("group_name")
    public String groupName;

    @SerializedName("group_finger_memo")
    public String groupFingerMemo;

    @SerializedName("group_class_text")
    public String groupClassText;

    @SerializedName("group_tags")
    public List<String> groupTags;

    @SerializedName("group_member_num")
    public Long groupMemberNum;

    public GroupInfo() {
    }
}
