// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared MemberWithGuildID object from the official API v2 docs. */
public class GuildMember {

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("user")
    public User user;

    @SerializedName("nick")
    public String nick;

    @SerializedName("roles")
    public List<String> roles;

    @SerializedName("joined_at")
    public String joinedAt;

    public GuildMember() {
    }
}
