// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared GuildInfo object from the official API v2 docs. */
public class GuildInfo {

    @SerializedName("id")
    public String id;

    @SerializedName("name")
    public String name;

    @SerializedName("icon")
    public String icon;

    @SerializedName("owner_id")
    public String ownerId;

    @SerializedName("owner")
    public Boolean owner;

    @SerializedName("joined_at")
    public String joinedAt;

    @SerializedName("member_count")
    public Long memberCount;

    @SerializedName("max_members")
    public Long maxMembers;

    @SerializedName("description")
    public String description;

    public GuildInfo() {
    }
}
