// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Guild Roles Response: response of GET /guilds/{guild_id}/roles. */
public class GuildRolesResponse {

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("roles")
    public List<Role> roles;

    @SerializedName("role_num_limit")
    public String roleNumLimit;

    public GuildRolesResponse() {
    }
}
