// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Guild Channel List Response: response of GET /guilds/{guild_id}/channels. */
public class GuildChannelListResponse {

    @SerializedName("channels")
    public List<Channel> channels;

    public GuildChannelListResponse() {
    }
}
