// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Guild List Response: response of GET /users/@me/guilds. */
public class GuildListResponse {

    @SerializedName("guilds")
    public List<GuildInfo> guilds;

    public GuildListResponse() {
    }
}
