// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Guild Api Permission Response: response of GET /guilds/{guild_id}/api_permission. */
public class GuildApiPermissionResponse {

    @SerializedName("apis")
    public List<ApiPermission> apis;

    public GuildApiPermissionResponse() {
    }
}
