// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Guild Role Members Response: response of GET /guilds/{guild_id}/roles/{role_id}/members. */
public class GuildRoleMembersResponse {

    @SerializedName("data")
    public List<GuildMember> data;

    @SerializedName("next")
    public String next;

    public GuildRoleMembersResponse() {
    }
}
