// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared ImageElem object from the official API v2 docs. */
public class ImageElem {

    @SerializedName("third_url")
    public String thirdUrl;

    @SerializedName("width_percent")
    public Double widthPercent;

    public ImageElem() {
    }
}
