// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared InputNotify object from the official API v2 docs. */
public class InputNotify {

    @SerializedName("input_type")
    public Long inputType;

    @SerializedName("input_second")
    public Long inputSecond;

    public InputNotify() {
    }
}
