// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared InteractionResolved object from the official API v2 docs. */
public class InteractionResolved {

    @SerializedName("button_data")
    public String buttonData;

    @SerializedName("button_id")
    public String buttonId;

    @SerializedName("user_id")
    public String userId;

    @SerializedName("feature_id")
    public String featureId;

    @SerializedName("message_id")
    public String messageId;

    @SerializedName("feedback_opt")
    public String feedbackOpt;

    @SerializedName("checked")
    public Long checked;

    @SerializedName("action")
    public String action;

    @SerializedName("message_scene")
    public InteractionMessageScene messageScene;

    @SerializedName("authorize_data")
    public AuthorizeData authorizeData;

    public InteractionResolved() {
    }
}
