// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared InteractionData object from the official API v2 docs. */
public class InteractionData {

    @SerializedName("type")
    public Long type;

    @SerializedName("resolved")
    public InteractionResolved resolved;

    public InteractionData() {
    }
}
