// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared JoinApprovalStrategy object from the official API v2 docs. */
public class JoinApprovalStrategy {

    @SerializedName("strategy_id")
    public String strategyId;

    @SerializedName("group_openids")
    public List<String> groupOpenids;

    @SerializedName("group_ids")
    public List<String> groupIds;

    @SerializedName("whitelist_user_count")
    public Long whitelistUserCount;

    @SerializedName("is_enable")
    public String isEnable;

    @SerializedName("expire_at")
    public String expireAt;

    @SerializedName("created_at")
    public String createdAt;

    @SerializedName("updated_at")
    public String updatedAt;

    @SerializedName("remark")
    public String remark;

    public JoinApprovalStrategy() {
    }
}
