// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Join Approval Strategy List Response: response of GET /v2/groups/join_approval_strategy. */
public class JoinApprovalStrategyListResponse {

    @SerializedName("strategies")
    public List<JoinApprovalStrategy> strategies;

    @SerializedName("next_cursor")
    public String nextCursor;

    public JoinApprovalStrategyListResponse() {
    }
}
