// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared JoinRequest object from the official API v2 docs. */
public class JoinRequest {

    @SerializedName("join_request_id")
    public String joinRequestId;

    @SerializedName("risk_tips")
    public String riskTips;

    @SerializedName("union_openid")
    public String unionOpenid;

    @SerializedName("member_openid")
    public String memberOpenid;

    @SerializedName("username")
    public String username;

    @SerializedName("apply_at")
    public String applyAt;

    @SerializedName("apply_source")
    public String applySource;

    @SerializedName("invited_by")
    public String invitedBy;

    @SerializedName("bot")
    public Boolean bot;

    @SerializedName("verify_info")
    public VerifyInfo verifyInfo;

    public JoinRequest() {
    }
}
