// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared Row object from the official API v2 docs. */
public class KeyboardRow {

    @SerializedName("buttons")
    public List<KeyboardButton> buttons;

    public KeyboardRow() {
    }
}
