// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared Keyboard object from the official API v2 docs. */
public class Keyboard {

    @SerializedName("id")
    public String id;

    @SerializedName("content")
    public KeyboardContent content;

    public Keyboard() {
    }
}
