// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared Button object from the official API v2 docs. */
public class KeyboardButton {

    @SerializedName("id")
    public String id;

    @SerializedName("render_data")
    public RenderData renderData;

    @SerializedName("action")
    public ButtonAction action;

    @SerializedName("group_id")
    public String groupId;

    public KeyboardButton() {
    }
}
