// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Media Upload Response: response of POST /v2/users/{user_openid}/files. */
public class MediaUploadResponse {

    @SerializedName("file_uuid")
    public String fileUuid;

    @SerializedName("file_info")
    public String fileInfo;

    @SerializedName("ttl")
    public Long ttl;

    @SerializedName("id")
    public String id;

    @SerializedName("raw_url")
    public String rawUrl;

    public MediaUploadResponse() {
    }
}
