// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared MemberMuteState object from the official API v2 docs. */
public class MemberMuteState {

    @SerializedName("member_openid")
    public String memberOpenid;

    @SerializedName("mute_expire_at")
    public String muteExpireAt;

    @SerializedName("username")
    public String username;

    @SerializedName("union_openid")
    public String unionOpenid;

    public MemberMuteState() {
    }
}
