// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Menu Response: response of GET /v2/menu. */
public class MenuResponse {

    @SerializedName("version")
    public Long version;

    @SerializedName("menu")
    public Menu menu;

    public MenuResponse() {
    }
}
