// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Menu Version Response: response of PUT /v2/menu. */
public class MenuVersionResponse {

    @SerializedName("version")
    public Long version;

    public MenuVersionResponse() {
    }
}
