// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared MenuItem object from the official API v2 docs. */
public class MenuItem {

    @SerializedName("name")
    public String name;

    @SerializedName("type")
    public String type;

    @SerializedName("sub_menu_items")
    public List<SubMenuItem> subMenuItems;

    @SerializedName("send_message")
    public String sendMessage;

    @SerializedName("link")
    public String link;

    @SerializedName("switch")
    public MenuSwitch switchValue;

    public MenuItem() {
    }
}
