// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared Switch object from the official API v2 docs. */
public class MenuSwitch {

    @SerializedName("switch_id")
    public String switchId;

    @SerializedName("default")
    public Boolean defaultValue;

    public MenuSwitch() {
    }
}
