// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared Menu object from the official API v2 docs. */
public class Menu {

    @SerializedName("items")
    public List<MenuItem> items;

    public Menu() {
    }
}
