// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared MessageEmbedField object from the official API v2 docs. */
public class MessageEmbedField {

    @SerializedName("name")
    public String name;

    public MessageEmbedField() {
    }
}
