// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared MessageDelete object from the official API v2 docs. */
public class MessageDelete {

    @SerializedName("message")
    public Message message;

    @SerializedName("op_user")
    public User opUser;

    public MessageDelete() {
    }
}
