// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared Message object from the official API v2 docs. */
public class Message {

    @SerializedName("id")
    public String id;

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("content")
    public String content;

    @SerializedName("timestamp")
    public String timestamp;

    @SerializedName("edited_timestamp")
    public String editedTimestamp;

    @SerializedName("mention_everyone")
    public Boolean mentionEveryone;

    @SerializedName("author")
    public User author;

    @SerializedName("attachments")
    public List<MessageAttachment> attachments;

    @SerializedName("embeds")
    public List<MessageEmbed> embeds;

    @SerializedName("mentions")
    public List<User> mentions;

    @SerializedName("member")
    public GuildMember member;

    @SerializedName("ark")
    public MessageArk ark;

    @SerializedName("seq")
    public Long seq;

    @SerializedName("seq_in_channel")
    public String seqInChannel;

    @SerializedName("message_reference")
    public MessageReference messageReference;

    public Message() {
    }
}
