// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared MessageArkObjKv object from the official API v2 docs. */
public class MessageArkObjKv {

    @SerializedName("key")
    public String key;

    @SerializedName("value")
    public String value;

    public MessageArkObjKv() {
    }
}
