// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared MessageSetting object from the official API v2 docs. */
public class MessageSetting {

    @SerializedName("disable_create_dm")
    public Boolean disableCreateDm;

    @SerializedName("disable_push_msg")
    public Boolean disablePushMsg;

    @SerializedName("channel_ids")
    public List<String> channelIds;

    @SerializedName("channel_push_max_num")
    public Long channelPushMaxNum;

    public MessageSetting() {
    }
}
