// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared MessageAudited object from the official API v2 docs. */
public class MessageAudited {

    @SerializedName("audit_id")
    public String auditId;

    @SerializedName("message_id")
    public String messageId;

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("audit_time")
    public String auditTime;

    @SerializedName("create_time")
    public String createTime;

    @SerializedName("seq_in_channel")
    public String seqInChannel;

    public MessageAudited() {
    }
}
