// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared MessageReference object from the official API v2 docs. */
public class MessageReference {

    @SerializedName("message_id")
    public String messageId;

    public MessageReference() {
    }
}
