// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared MessageMarkdown object from the official API v2 docs. */
public class MessageMarkdown {

    @SerializedName("template_id")
    public Long templateId;

    @SerializedName("content")
    public String content;

    @SerializedName("custom_template_id")
    public String customTemplateId;

    @SerializedName("force_verify_image_resource")
    public Boolean forceVerifyImageResource;

    public MessageMarkdown() {
    }
}
