// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared MessageEmbed object from the official API v2 docs. */
public class MessageEmbed {

    @SerializedName("title")
    public String title;

    @SerializedName("prompt")
    public String prompt;

    @SerializedName("thumbnail")
    public MessageEmbedThumbnail thumbnail;

    @SerializedName("fields")
    public List<MessageEmbedField> fields;

    public MessageEmbed() {
    }
}
