// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared MessageScene object from the official API v2 docs. */
public class MessageScene {

    @SerializedName("source")
    public String source;

    @SerializedName("ext")
    public List<String> ext;

    public MessageScene() {
    }
}
