// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared MessageArkObj object from the official API v2 docs. */
public class MessageArkObj {

    @SerializedName("obj_kv")
    public List<MessageArkObjKv> objKv;

    public MessageArkObj() {
    }
}
