// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared MessageExtInfo object from the official API v2 docs. */
public class MessageExtInfo {

    @SerializedName("ref_idx")
    public String refIdx;

    public MessageExtInfo() {
    }
}
