// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared MessageAttachment object from the official API v2 docs. */
public class MessageAttachment {

    @SerializedName("url")
    public String url;

    @SerializedName("filename")
    public String filename;

    @SerializedName("width")
    public Long width;

    @SerializedName("height")
    public Long height;

    @SerializedName("size")
    public Long size;

    @SerializedName("content_type")
    public String contentType;

    @SerializedName("voice_wav_url")
    public String voiceWavUrl;

    @SerializedName("asr_refer_text")
    public String asrReferText;

    public MessageAttachment() {
    }
}
