// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared MessageReaction object from the official API v2 docs. */
public class MessageReaction {

    @SerializedName("user_id")
    public String userId;

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("target")
    public ReactionTarget target;

    @SerializedName("emoji")
    public Emoji emoji;

    public MessageReaction() {
    }
}
