// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared MsgElement object from the official API v2 docs. */
public class MsgElement {

    @SerializedName("msg_idx")
    public String msgIdx;

    @SerializedName("author")
    public User author;

    @SerializedName("message_type")
    public Long messageType;

    @SerializedName("content")
    public String content;

    @SerializedName("attachments")
    public List<MessageAttachment> attachments;

    @SerializedName("ark_data")
    public ArkData arkData;

    @SerializedName("msg_elements")
    public List<MsgElement> msgElements;

    public MsgElement() {
    }
}
