// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared MuteScheduleRule object from the official API v2 docs. */
public class MuteScheduleRule {

    @SerializedName("task_id")
    public String taskId;

    @SerializedName("start_at")
    public String startAt;

    @SerializedName("end_at")
    public String endAt;

    @SerializedName("enabled")
    public Boolean enabled;

    public MuteScheduleRule() {
    }
}
