// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared MuteRecurringRule object from the official API v2 docs. */
public class MuteRecurringRule {

    @SerializedName("task_id")
    public String taskId;

    @SerializedName("weekdays")
    public List<Long> weekdays;

    @SerializedName("start_time")
    public String startTime;

    @SerializedName("end_time")
    public String endTime;

    @SerializedName("enabled")
    public Boolean enabled;

    public MuteRecurringRule() {
    }
}
