// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared PanelItem object from the official API v2 docs. */
public class PanelItem {

    @SerializedName("name")
    public String name;

    @SerializedName("desc")
    public String desc;

    @SerializedName("type")
    public String type;

    @SerializedName("only_admin")
    public Boolean onlyAdmin;

    @SerializedName("link")
    public String link;

    public PanelItem() {
    }
}
