// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Panel List Response: response of GET /v2/panels. */
public class PanelListResponse {

    @SerializedName("records")
    public List<PanelRecord> records;

    @SerializedName("next_cursor")
    public String nextCursor;

    @SerializedName("is_end")
    public Boolean isEnd;

    public PanelListResponse() {
    }
}
