// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared PanelRecord object from the official API v2 docs. */
public class PanelRecord {

    @SerializedName("panel_id")
    public String panelId;

    @SerializedName("scope")
    public String scope;

    @SerializedName("target_type")
    public String targetType;

    @SerializedName("panel")
    public Panel panel;

    @SerializedName("created_at")
    public String createdAt;

    @SerializedName("updated_at")
    public String updatedAt;

    @SerializedName("version")
    public Long version;

    public PanelRecord() {
    }
}
