// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared Panel object from the official API v2 docs. */
public class Panel {

    @SerializedName("items")
    public List<PanelItem> items;

    @SerializedName("remark")
    public String remark;

    @SerializedName("version")
    public Long version;

    public Panel() {
    }
}
