// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Panel Detail Response: response of GET /v2/panels/{panel_id}. */
public class PanelDetailResponse {

    @SerializedName("panel_id")
    public String panelId;

    @SerializedName("scope")
    public String scope;

    @SerializedName("target_type")
    public String targetType;

    @SerializedName("panel")
    public Panel panel;

    @SerializedName("created_at")
    public String createdAt;

    @SerializedName("updated_at")
    public String updatedAt;

    @SerializedName("version")
    public Long version;

    @SerializedName("user_openids")
    public List<String> userOpenids;

    @SerializedName("group_openids")
    public List<String> groupOpenids;

    public PanelDetailResponse() {
    }
}
