// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared ParagraphProps object from the official API v2 docs. */
public class ParagraphProps {

    @SerializedName("alignment")
    public Long alignment;

    public ParagraphProps() {
    }
}
