// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared PlatVideo object from the official API v2 docs. */
public class PlatVideo {

    @SerializedName("url")
    public String url;

    @SerializedName("width")
    public Long width;

    @SerializedName("height")
    public Long height;

    @SerializedName("video_id")
    public String videoId;

    @SerializedName("duration")
    public Long duration;

    @SerializedName("cover")
    public PlatImage cover;

    public PlatVideo() {
    }
}
