// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared PlatImage object from the official API v2 docs. */
public class PlatImage {

    @SerializedName("url")
    public String url;

    @SerializedName("width")
    public Long width;

    @SerializedName("height")
    public Long height;

    @SerializedName("image_id")
    public String imageId;

    public PlatImage() {
    }
}
