// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Reaction Users Response: response of GET /channels/{channel_id}/messages/{message_id}/reactions/{type}/{id}. */
public class ReactionUsersResponse {

    @SerializedName("users")
    public List<User> users;

    @SerializedName("cookie")
    public String cookie;

    @SerializedName("is_end")
    public Boolean isEnd;

    public ReactionUsersResponse() {
    }
}
