// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared RecommendChannel object from the official API v2 docs. */
public class RecommendChannel {

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("introduce")
    public String introduce;

    public RecommendChannel() {
    }
}
