// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared RenderData object from the official API v2 docs. */
public class RenderData {

    @SerializedName("label")
    public String label;

    @SerializedName("visited_label")
    public String visitedLabel;

    @SerializedName("style")
    public Long style;

    public RenderData() {
    }
}
