// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared Reply object from the official API v2 docs. */
public class Reply {

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("author_id")
    public String authorId;

    @SerializedName("reply_info")
    public ReplyInfo replyInfo;

    public Reply() {
    }
}
