// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared ReplyInfo object from the official API v2 docs. */
public class ReplyInfo {

    @SerializedName("thread_id")
    public String threadId;

    @SerializedName("post_id")
    public String postId;

    @SerializedName("reply_id")
    public String replyId;

    @SerializedName("content")
    public String content;

    @SerializedName("date_time")
    public String dateTime;

    public ReplyInfo() {
    }
}
