// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared Elem object from the official API v2 docs. */
public class RichTextElem {

    @SerializedName("text")
    public TextElem text;

    @SerializedName("image")
    public ImageElem image;

    @SerializedName("video")
    public VideoElem video;

    @SerializedName("url")
    public UrlElem url;

    @SerializedName("type")
    public Long type;

    public RichTextElem() {
    }
}
