// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared RichObject object from the official API v2 docs. */
public class RichObject {

    @SerializedName("type")
    public Long type;

    @SerializedName("text_info")
    public TextInfo textInfo;

    @SerializedName("at_info")
    public AtInfo atInfo;

    @SerializedName("url_info")
    public UrlElem urlInfo;

    @SerializedName("emoji_info")
    public EmojiInfo emojiInfo;

    @SerializedName("channel_info")
    public ChannelInfo channelInfo;

    public RichObject() {
    }
}
