// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared Role object from the official API v2 docs. */
public class Role {

    @SerializedName("id")
    public String id;

    @SerializedName("name")
    public String name;

    @SerializedName("color")
    public Long color;

    @SerializedName("hoist")
    public Long hoist;

    @SerializedName("number")
    public Long number;

    @SerializedName("member_limit")
    public Long memberLimit;

    public Role() {
    }
}
