// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared Schedule object from the official API v2 docs. */
public class Schedule {

    @SerializedName("id")
    public String id;

    @SerializedName("name")
    public String name;

    @SerializedName("description")
    public String description;

    @SerializedName("start_timestamp")
    public String startTimestamp;

    @SerializedName("end_timestamp")
    public String endTimestamp;

    @SerializedName("creator")
    public GroupMember creator;

    @SerializedName("jump_channel_id")
    public String jumpChannelId;

    @SerializedName("remind_type")
    public String remindType;

    public Schedule() {
    }
}
