// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Send Stream Message Response: response of POST /v2/users/{user_openid}/stream_messages. */
public class SendStreamMessageResponse {

    @SerializedName("id")
    public String id;

    @SerializedName("timestamp")
    public String timestamp;

    @SerializedName("ext_info")
    public MessageExtInfo extInfo;

    @SerializedName("remain_msg_len")
    public Long remainMsgLen;

    public SendStreamMessageResponse() {
    }
}
