// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Send Message Response: response of POST /v2/users/{user_openid}/messages. */
public class SendMessageResponse {

    @SerializedName("id")
    public String id;

    @SerializedName("timestamp")
    public String timestamp;

    @SerializedName("ext_info")
    public MessageExtInfo extInfo;

    public SendMessageResponse() {
    }
}
