// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared SetMemberMuteState object from the official API v2 docs. */
public class SetMemberMuteState {

    @SerializedName("op")
    public String op;

    @SerializedName("member_openid")
    public String memberOpenid;

    @SerializedName("mute_expire_at")
    public String muteExpireAt;

    public SetMemberMuteState() {
    }
}
