// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared SubscribeMsgTemplateResult object from the official API v2 docs. */
public class SubscribeMsgTemplateResult {

    @SerializedName("template_id")
    public Long templateId;

    @SerializedName("custom_template_id")
    public String customTemplateId;

    @SerializedName("op")
    public Long op;

    @SerializedName("subscribe_id")
    public String subscribeId;

    @SerializedName("subscribe_ts")
    public Long subscribeTs;

    @SerializedName("update_ts")
    public Long updateTs;

    public SubscribeMsgTemplateResult() {
    }
}
