// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared TextProps object from the official API v2 docs. */
public class TextProps {

    @SerializedName("font_bold")
    public Boolean fontBold;

    @SerializedName("italic")
    public Boolean italic;

    @SerializedName("underline")
    public Boolean underline;

    public TextProps() {
    }
}
