// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared TextElem object from the official API v2 docs. */
public class TextElem {

    @SerializedName("text")
    public String text;

    @SerializedName("props")
    public TextProps props;

    public TextElem() {
    }
}
