// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Thread Detail Response: response of GET /channels/{channel_id}/threads/{thread_id}. */
public class ThreadDetailResponse {

    @SerializedName("thread")
    public Thread thread;

    public ThreadDetailResponse() {
    }
}
