// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Thread List Response: response of GET /channels/{channel_id}/threads. */
public class ThreadListResponse {

    @SerializedName("threads")
    public List<Thread> threads;

    @SerializedName("is_finish")
    public Long isFinish;

    public ThreadListResponse() {
    }
}
