// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared ThreadInfo object from the official API v2 docs. */
public class ThreadInfo {

    @SerializedName("thread_id")
    public String threadId;

    @SerializedName("title")
    public String title;

    @SerializedName("content")
    public String content;

    @SerializedName("date_time")
    public String dateTime;

    public ThreadInfo() {
    }
}
