// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Thread Create Response: response of PUT /channels/{channel_id}/threads. */
public class ThreadCreateResponse {

    @SerializedName("task_id")
    public String taskId;

    @SerializedName("create_time")
    public String createTime;

    public ThreadCreateResponse() {
    }
}
