// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/**
 * Update Strategy Whitelist Response: response of POST
 * /v2/groups/join_approval_strategy/{strategy_id}/whitelist_users.
 */
public class UpdateStrategyWhitelistResponse {

    @SerializedName("strategy_id")
    public String strategyId;

    @SerializedName("whitelist_user_count")
    public Long whitelistUserCount;

    @SerializedName("updated_at")
    public String updatedAt;

    public UpdateStrategyWhitelistResponse() {
    }
}
