// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Update Join Approval Strategy Response: response of PATCH /v2/groups/join_approval_strategy/{strategy_id}. */
public class UpdateJoinApprovalStrategyResponse {

    @SerializedName("is_enable")
    public String isEnable;

    @SerializedName("expire_at")
    public String expireAt;

    public UpdateJoinApprovalStrategyResponse() {
    }
}
