// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Update Panel Response: response of PUT /v2/panels/{panel_id}. */
public class UpdatePanelResponse {

    @SerializedName("version")
    public Long version;

    public UpdatePanelResponse() {
    }
}
