// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Update Guild Role Response: response of PATCH /guilds/{guild_id}/roles/{role_id}. */
public class UpdateGuildRoleResponse {

    @SerializedName("guild_id")
    public String guildId;

    @SerializedName("role_id")
    public String roleId;

    @SerializedName("role")
    public Role role;

    public UpdateGuildRoleResponse() {
    }
}
