// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Upload Prepare Response: response of POST /v2/users/{user_id}/upload_prepare. */
public class UploadPrepareResponse {

    @SerializedName("upload_id")
    public String uploadId;

    @SerializedName("block_size")
    public String blockSize;

    @SerializedName("parts")
    public List<UploadPart> parts;

    @SerializedName("upload_config")
    public UploadConfig uploadConfig;

    public UploadPrepareResponse() {
    }
}
