// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared UploadPart object from the official API v2 docs. */
public class UploadPart {

    @SerializedName("index")
    public Long index;

    @SerializedName("presigned_url")
    public String presignedUrl;

    @SerializedName("block_size")
    public String blockSize;

    public UploadPart() {
    }
}
