// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared UploadConfig object from the official API v2 docs. */
public class UploadConfig {

    @SerializedName("concurrency")
    public Long concurrency;

    @SerializedName("retry_timeout")
    public Long retryTimeout;

    @SerializedName("retry_delay")
    public Long retryDelay;

    public UploadConfig() {
    }
}
