// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared URLInfo object from the official API v2 docs. */
public class URLInfo {

    @SerializedName("url")
    public String url;

    @SerializedName("display_text")
    public String displayText;

    public URLInfo() {
    }
}
