// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Url Link Response: response of POST /v2/generate_url_link. */
public class UrlLinkResponse {

    @SerializedName("data")
    public UrlLinkData data;

    public UrlLinkResponse() {
    }
}
