// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

/** Shared User object from the official API v2 docs. */
public class User {

    @SerializedName("id")
    public String id;

    @SerializedName("username")
    public String username;

    @SerializedName("bot")
    public Boolean bot;

    @SerializedName("union_openid")
    public String unionOpenid;

    @SerializedName("union_user_account")
    public String unionUserAccount;

    @SerializedName("user_openid")
    public String userOpenid;

    @SerializedName("member_openid")
    public String memberOpenid;

    @SerializedName("member_role")
    public String memberRole;

    public User() {
    }
}
