// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Shared VerifyInfo object from the official API v2 docs. */
public class VerifyInfo {

    @SerializedName("method")
    public String method;

    @SerializedName("verify_message")
    public String verifyMessage;

    @SerializedName("review_qa_list")
    public List<ReviewQA> reviewQaList;

    public VerifyInfo() {
    }
}
