// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.api.endpoint;

import io.github.skiesworld.qqbot.http.Endpoint;
import io.github.skiesworld.qqbot.model.Announces;
import io.github.skiesworld.qqbot.model.ApiPermissionDemand;
import io.github.skiesworld.qqbot.model.AudioControl;
import io.github.skiesworld.qqbot.model.BatchRemoveGroupMembersResponse;
import io.github.skiesworld.qqbot.model.BotProfile;
import io.github.skiesworld.qqbot.model.Channel;
import io.github.skiesworld.qqbot.model.ChannelMemberPermissionsResponse;
import io.github.skiesworld.qqbot.model.ChannelOnlineNumsResponse;
import io.github.skiesworld.qqbot.model.ChannelRolePermissionsResponse;
import io.github.skiesworld.qqbot.model.CreateGuildRoleResponse;
import io.github.skiesworld.qqbot.model.CreateJoinApprovalStrategyResponse;
import io.github.skiesworld.qqbot.model.CreatePanelResponse;
import io.github.skiesworld.qqbot.model.Dms;
import io.github.skiesworld.qqbot.model.GroupBlacklistOperationResponse;
import io.github.skiesworld.qqbot.model.GroupBlacklistResponse;
import io.github.skiesworld.qqbot.model.GroupBotState;
import io.github.skiesworld.qqbot.model.GroupInfo;
import io.github.skiesworld.qqbot.model.GroupJoinRequestListResponse;
import io.github.skiesworld.qqbot.model.GroupMember;
import io.github.skiesworld.qqbot.model.GroupMemberListResponse;
import io.github.skiesworld.qqbot.model.GroupMuteStateResponse;
import io.github.skiesworld.qqbot.model.Guild;
import io.github.skiesworld.qqbot.model.GuildApiPermissionResponse;
import io.github.skiesworld.qqbot.model.GuildChannelListResponse;
import io.github.skiesworld.qqbot.model.GuildListResponse;
import io.github.skiesworld.qqbot.model.GuildMember;
import io.github.skiesworld.qqbot.model.GuildRoleMembersResponse;
import io.github.skiesworld.qqbot.model.GuildRolesResponse;
import io.github.skiesworld.qqbot.model.JoinApprovalStrategyListResponse;
import io.github.skiesworld.qqbot.model.MediaUploadResponse;
import io.github.skiesworld.qqbot.model.MenuResponse;
import io.github.skiesworld.qqbot.model.MenuVersionResponse;
import io.github.skiesworld.qqbot.model.Message;
import io.github.skiesworld.qqbot.model.MessageSetting;
import io.github.skiesworld.qqbot.model.PanelDetailResponse;
import io.github.skiesworld.qqbot.model.PanelListResponse;
import io.github.skiesworld.qqbot.model.PinsMessage;
import io.github.skiesworld.qqbot.model.ReactionUsersResponse;
import io.github.skiesworld.qqbot.model.Schedule;
import io.github.skiesworld.qqbot.model.SendMessageResponse;
import io.github.skiesworld.qqbot.model.SendStreamMessageResponse;
import io.github.skiesworld.qqbot.model.ThreadCreateResponse;
import io.github.skiesworld.qqbot.model.ThreadDetailResponse;
import io.github.skiesworld.qqbot.model.ThreadListResponse;
import io.github.skiesworld.qqbot.model.UpdateGuildRoleResponse;
import io.github.skiesworld.qqbot.model.UpdateJoinApprovalStrategyResponse;
import io.github.skiesworld.qqbot.model.UpdatePanelResponse;
import io.github.skiesworld.qqbot.model.UpdateStrategyWhitelistResponse;
import io.github.skiesworld.qqbot.model.UploadPrepareResponse;
import io.github.skiesworld.qqbot.model.UrlLinkResponse;
import io.github.skiesworld.qqbot.model.request.AcknowledgeInteractionRequest;
import io.github.skiesworld.qqbot.model.request.ApproveGroupJoinRequestRequest;
import io.github.skiesworld.qqbot.model.request.BatchRemoveGroupMembersRequest;
import io.github.skiesworld.qqbot.model.request.CompleteUploadPartRequest;
import io.github.skiesworld.qqbot.model.request.CreateApiPermissionDemandRequest;
import io.github.skiesworld.qqbot.model.request.CreateChannelRequest;
import io.github.skiesworld.qqbot.model.request.CreateDmsRequest;
import io.github.skiesworld.qqbot.model.request.CreateGuildAnnounceRequest;
import io.github.skiesworld.qqbot.model.request.CreateGuildRoleRequest;
import io.github.skiesworld.qqbot.model.request.CreateJoinApprovalStrategyRequest;
import io.github.skiesworld.qqbot.model.request.CreatePanelRequest;
import io.github.skiesworld.qqbot.model.request.GenerateUrlLinkRequest;
import io.github.skiesworld.qqbot.model.request.GuildMemberRoleRequest;
import io.github.skiesworld.qqbot.model.request.PrepareUploadRequest;
import io.github.skiesworld.qqbot.model.request.PublishThreadRequest;
import io.github.skiesworld.qqbot.model.request.ScheduleRequest;
import io.github.skiesworld.qqbot.model.request.SendC2CMessageRequest;
import io.github.skiesworld.qqbot.model.request.SendC2CStreamMessageRequest;
import io.github.skiesworld.qqbot.model.request.SendChannelMessageRequest;
import io.github.skiesworld.qqbot.model.request.SendGroupMessageRequest;
import io.github.skiesworld.qqbot.model.request.SetGroupMemberMuteRequest;
import io.github.skiesworld.qqbot.model.request.SetGuildMemberMuteRequest;
import io.github.skiesworld.qqbot.model.request.SetGuildMembersMuteRequest;
import io.github.skiesworld.qqbot.model.request.SetGuildMuteRequest;
import io.github.skiesworld.qqbot.model.request.UpdateChannelMemberPermissionsRequest;
import io.github.skiesworld.qqbot.model.request.UpdateChannelRequest;
import io.github.skiesworld.qqbot.model.request.UpdateChannelRolePermissionsRequest;
import io.github.skiesworld.qqbot.model.request.UpdateGlobalMenuRequest;
import io.github.skiesworld.qqbot.model.request.UpdateGroupBlacklistRequest;
import io.github.skiesworld.qqbot.model.request.UpdateGuildRoleRequest;
import io.github.skiesworld.qqbot.model.request.UpdateJoinApprovalStrategyRequest;
import io.github.skiesworld.qqbot.model.request.UpdatePanelRequest;
import io.github.skiesworld.qqbot.model.request.UpdatePanelTargetRequest;
import io.github.skiesworld.qqbot.model.request.UpdateStrategyWhitelistRequest;
import io.github.skiesworld.qqbot.model.request.UploadMediaRequest;

import java.util.List;

/** One constant per documented operation; they are the vocabulary of the API classes. */
public final class Endpoints {

    private Endpoints() {
    }

    // ---- MeApi ----
    public static final Endpoint<BotProfile> GET_BOT_PROFILE = Endpoint.of(Endpoint.Method.GET, "/users/@me", BotProfile.class);
    public static final Endpoint<Dms> CREATE_DIRECT_MESSAGE_SESSION = Endpoint.of(Endpoint.Method.POST, "/users/@me/dms", Dms.class);
    public static final Endpoint<GuildListResponse> LIST_BOT_GUILDS = Endpoint.of(Endpoint.Method.GET, "/users/@me/guilds", GuildListResponse.class);

    // ---- C2CApi ----
    public static final Endpoint<Void> COMPLETE_C2C_UPLOAD_PART = Endpoint.of(Endpoint.Method.POST, "/v2/users/{user_id}/upload_part_finish", Void.class);
    public static final Endpoint<UploadPrepareResponse> PREPARE_C2C_MEDIA_UPLOAD = Endpoint.of(Endpoint.Method.POST, "/v2/users/{user_id}/upload_prepare", UploadPrepareResponse.class);
    public static final Endpoint<MediaUploadResponse> UPLOAD_C2C_MEDIA = Endpoint.of(Endpoint.Method.POST, "/v2/users/{user_openid}/files", MediaUploadResponse.class);
    public static final Endpoint<SendMessageResponse> SEND_C2C_MESSAGE = Endpoint.of(Endpoint.Method.POST, "/v2/users/{user_openid}/messages", SendMessageResponse.class);
    public static final Endpoint<Void> RECALL_C2C_MESSAGE = Endpoint.of(Endpoint.Method.DELETE, "/v2/users/{user_openid}/messages/{message_id}", Void.class);
    public static final Endpoint<SendStreamMessageResponse> SEND_C2C_STREAM_MESSAGE = Endpoint.of(Endpoint.Method.POST, "/v2/users/{user_openid}/stream_messages", SendStreamMessageResponse.class);

    // ---- GroupApi ----
    public static final Endpoint<UrlLinkResponse> GENERATE_URL_LINK = Endpoint.of(Endpoint.Method.POST, "/v2/generate_url_link", UrlLinkResponse.class);
    public static final Endpoint<JoinApprovalStrategyListResponse> LIST_JOIN_APPROVAL_STRATEGIES = Endpoint.of(Endpoint.Method.GET, "/v2/groups/join_approval_strategy", JoinApprovalStrategyListResponse.class);
    public static final Endpoint<CreateJoinApprovalStrategyResponse> CREATE_JOIN_APPROVAL_STRATEGY = Endpoint.of(Endpoint.Method.POST, "/v2/groups/join_approval_strategy", CreateJoinApprovalStrategyResponse.class);
    public static final Endpoint<Void> DELETE_JOIN_APPROVAL_STRATEGY = Endpoint.of(Endpoint.Method.DELETE, "/v2/groups/join_approval_strategy/{strategy_id}", Void.class);
    public static final Endpoint<UpdateJoinApprovalStrategyResponse> UPDATE_JOIN_APPROVAL_STRATEGY = Endpoint.of(Endpoint.Method.PATCH, "/v2/groups/join_approval_strategy/{strategy_id}", UpdateJoinApprovalStrategyResponse.class);
    public static final Endpoint<Void> EXECUTE_JOIN_APPROVAL_STRATEGY = Endpoint.of(Endpoint.Method.POST, "/v2/groups/join_approval_strategy/{strategy_id}/execute", Void.class);
    public static final Endpoint<UpdateStrategyWhitelistResponse> UPDATE_JOIN_APPROVAL_STRATEGY_WHITELIST = Endpoint.of(Endpoint.Method.POST, "/v2/groups/join_approval_strategy/{strategy_id}/whitelist_users", UpdateStrategyWhitelistResponse.class);
    public static final Endpoint<Void> COMPLETE_GROUP_UPLOAD_PART = Endpoint.of(Endpoint.Method.POST, "/v2/groups/{group_id}/upload_part_finish", Void.class);
    public static final Endpoint<UploadPrepareResponse> PREPARE_GROUP_MEDIA_UPLOAD = Endpoint.of(Endpoint.Method.POST, "/v2/groups/{group_id}/upload_prepare", UploadPrepareResponse.class);
    public static final Endpoint<Void> APPROVE_GROUP_JOIN_REQUEST = Endpoint.of(Endpoint.Method.POST, "/v2/groups/{group_openid}/approval_join_request/{member_openid}", Void.class);
    public static final Endpoint<BatchRemoveGroupMembersResponse> BATCH_REMOVE_GROUP_MEMBERS = Endpoint.of(Endpoint.Method.POST, "/v2/groups/{group_openid}/batch_remove_members", BatchRemoveGroupMembersResponse.class);
    public static final Endpoint<GroupBotState> GET_GROUP_BOT_STATE = Endpoint.of(Endpoint.Method.GET, "/v2/groups/{group_openid}/bot_state", GroupBotState.class);
    public static final Endpoint<MediaUploadResponse> UPLOAD_GROUP_MEDIA = Endpoint.of(Endpoint.Method.POST, "/v2/groups/{group_openid}/files", MediaUploadResponse.class);
    public static final Endpoint<GroupInfo> GET_GROUP_INFO = Endpoint.of(Endpoint.Method.GET, "/v2/groups/{group_openid}/info", GroupInfo.class);
    public static final Endpoint<GroupJoinRequestListResponse> LIST_GROUP_JOIN_REQUESTS = Endpoint.of(Endpoint.Method.GET, "/v2/groups/{group_openid}/join_request_list", GroupJoinRequestListResponse.class);
    public static final Endpoint<GroupBlacklistResponse> LIST_GROUP_BLACKLIST = Endpoint.of(Endpoint.Method.GET, "/v2/groups/{group_openid}/member_blacklist", GroupBlacklistResponse.class);
    public static final Endpoint<GroupBlacklistOperationResponse> UPDATE_GROUP_BLACKLIST = Endpoint.of(Endpoint.Method.POST, "/v2/groups/{group_openid}/member_blacklist", GroupBlacklistOperationResponse.class);
    public static final Endpoint<GroupMemberListResponse> LIST_GROUP_MEMBERS = Endpoint.of(Endpoint.Method.GET, "/v2/groups/{group_openid}/members", GroupMemberListResponse.class);
    public static final Endpoint<GroupMember> GET_GROUP_MEMBER = Endpoint.of(Endpoint.Method.GET, "/v2/groups/{group_openid}/members/{member_openid}", GroupMember.class);
    public static final Endpoint<SendMessageResponse> SEND_GROUP_MESSAGE = Endpoint.of(Endpoint.Method.POST, "/v2/groups/{group_openid}/messages", SendMessageResponse.class);
    public static final Endpoint<Void> RECALL_GROUP_MESSAGE = Endpoint.of(Endpoint.Method.DELETE, "/v2/groups/{group_openid}/messages/{message_id}", Void.class);
    public static final Endpoint<GroupMuteStateResponse> GET_GROUP_MUTE_STATE = Endpoint.of(Endpoint.Method.GET, "/v2/groups/{group_openid}/restrict_chat_setting", GroupMuteStateResponse.class);
    public static final Endpoint<Void> SET_GROUP_MEMBER_MUTE = Endpoint.of(Endpoint.Method.POST, "/v2/groups/{group_openid}/restrict_chat_setting", Void.class);

    // ---- GuildApi ----
    public static final Endpoint<Guild> GET_GUILD = Endpoint.of(Endpoint.Method.GET, "/guilds/{guild_id}", Guild.class);
    public static final Endpoint<GuildApiPermissionResponse> LIST_GUILD_API_PERMISSIONS = Endpoint.of(Endpoint.Method.GET, "/guilds/{guild_id}/api_permission", GuildApiPermissionResponse.class);
    public static final Endpoint<ApiPermissionDemand> CREATE_API_PERMISSION_DEMAND = Endpoint.of(Endpoint.Method.POST, "/guilds/{guild_id}/api_permission/demand", ApiPermissionDemand.class);
    public static final Endpoint<List<GuildMember>> LIST_GUILD_MEMBERS = Endpoint.of(Endpoint.Method.GET, "/guilds/{guild_id}/members", Endpoint.listOf(GuildMember.class));
    public static final Endpoint<Void> REMOVE_GUILD_MEMBER = Endpoint.of(Endpoint.Method.DELETE, "/guilds/{guild_id}/members/{user_id}", Void.class);
    public static final Endpoint<GuildMember> GET_GUILD_MEMBER = Endpoint.of(Endpoint.Method.GET, "/guilds/{guild_id}/members/{user_id}", GuildMember.class);
    public static final Endpoint<Void> SET_GUILD_MEMBER_MUTE = Endpoint.of(Endpoint.Method.PATCH, "/guilds/{guild_id}/members/{user_id}/mute", Void.class);
    public static final Endpoint<MessageSetting> GET_GUILD_MESSAGE_SETTING = Endpoint.of(Endpoint.Method.GET, "/guilds/{guild_id}/message/setting", MessageSetting.class);
    public static final Endpoint<Void> SET_GUILD_MUTE = Endpoint.of(Endpoint.Method.PATCH, "/guilds/{guild_id}/mute", Void.class);
    public static final Endpoint<Void> SET_GUILD_MEMBERS_MUTE = Endpoint.of(Endpoint.Method.PATCH, "/guilds/{guild_id}/mute", Void.class);

    // ---- ChannelApi ----
    public static final Endpoint<Void> DELETE_CHANNEL = Endpoint.of(Endpoint.Method.DELETE, "/channels/{channel_id}", Void.class);
    public static final Endpoint<Channel> GET_CHANNEL = Endpoint.of(Endpoint.Method.GET, "/channels/{channel_id}", Channel.class);
    public static final Endpoint<Channel> UPDATE_CHANNEL = Endpoint.of(Endpoint.Method.PATCH, "/channels/{channel_id}", Channel.class);
    public static final Endpoint<ChannelOnlineNumsResponse> GET_CHANNEL_ONLINE_NUMS = Endpoint.of(Endpoint.Method.GET, "/channels/{channel_id}/online_nums", ChannelOnlineNumsResponse.class);
    public static final Endpoint<GuildChannelListResponse> LIST_CHANNELS = Endpoint.of(Endpoint.Method.GET, "/guilds/{guild_id}/channels", GuildChannelListResponse.class);
    public static final Endpoint<Channel> CREATE_CHANNEL = Endpoint.of(Endpoint.Method.POST, "/guilds/{guild_id}/channels", Channel.class);

    // ---- ChannelMessageApi ----
    public static final Endpoint<Message> SEND_CHANNEL_MESSAGE = Endpoint.of(Endpoint.Method.POST, "/channels/{channel_id}/messages", Message.class);
    public static final Endpoint<Void> RECALL_CHANNEL_MESSAGE = Endpoint.of(Endpoint.Method.DELETE, "/channels/{channel_id}/messages/{message_id}", Void.class);
    public static final Endpoint<Void> DELETE_MESSAGE_REACTION = Endpoint.of(Endpoint.Method.DELETE, "/channels/{channel_id}/messages/{message_id}/reactions/{type}/{id}", Void.class);
    public static final Endpoint<ReactionUsersResponse> LIST_MESSAGE_REACTION_USERS = Endpoint.of(Endpoint.Method.GET, "/channels/{channel_id}/messages/{message_id}/reactions/{type}/{id}", ReactionUsersResponse.class);
    public static final Endpoint<Void> ADD_MESSAGE_REACTION = Endpoint.of(Endpoint.Method.PUT, "/channels/{channel_id}/messages/{message_id}/reactions/{type}/{id}", Void.class);
    public static final Endpoint<Message> SEND_DIRECT_MESSAGE = Endpoint.of(Endpoint.Method.POST, "/dms/{guild_id}/messages", Message.class);
    public static final Endpoint<Void> RECALL_DIRECT_MESSAGE = Endpoint.of(Endpoint.Method.DELETE, "/dms/{guild_id}/messages/{message_id}", Void.class);

    // ---- ChannelContentApi ----
    public static final Endpoint<Void> CONTROL_CHANNEL_AUDIO = Endpoint.of(Endpoint.Method.POST, "/channels/{channel_id}/audio", Void.class);
    public static final Endpoint<Void> STOP_CHANNEL_MIC = Endpoint.of(Endpoint.Method.DELETE, "/channels/{channel_id}/mic", Void.class);
    public static final Endpoint<Void> START_CHANNEL_MIC = Endpoint.of(Endpoint.Method.PUT, "/channels/{channel_id}/mic", Void.class);
    public static final Endpoint<PinsMessage> GET_PINNED_MESSAGES = Endpoint.of(Endpoint.Method.GET, "/channels/{channel_id}/pins", PinsMessage.class);
    public static final Endpoint<Void> UNPIN_MESSAGE = Endpoint.of(Endpoint.Method.DELETE, "/channels/{channel_id}/pins/{message_id}", Void.class);
    public static final Endpoint<PinsMessage> PIN_MESSAGE = Endpoint.of(Endpoint.Method.PUT, "/channels/{channel_id}/pins/{message_id}", PinsMessage.class);
    public static final Endpoint<List<Schedule>> LIST_SCHEDULES = Endpoint.of(Endpoint.Method.GET, "/channels/{channel_id}/schedules", Endpoint.listOf(Schedule.class));
    public static final Endpoint<Schedule> CREATE_SCHEDULE = Endpoint.of(Endpoint.Method.POST, "/channels/{channel_id}/schedules", Schedule.class);
    public static final Endpoint<Void> DELETE_SCHEDULE = Endpoint.of(Endpoint.Method.DELETE, "/channels/{channel_id}/schedules/{schedule_id}", Void.class);
    public static final Endpoint<Schedule> GET_SCHEDULE = Endpoint.of(Endpoint.Method.GET, "/channels/{channel_id}/schedules/{schedule_id}", Schedule.class);
    public static final Endpoint<Schedule> UPDATE_SCHEDULE = Endpoint.of(Endpoint.Method.PATCH, "/channels/{channel_id}/schedules/{schedule_id}", Schedule.class);
    public static final Endpoint<ThreadListResponse> LIST_THREADS = Endpoint.of(Endpoint.Method.GET, "/channels/{channel_id}/threads", ThreadListResponse.class);
    public static final Endpoint<ThreadCreateResponse> PUBLISH_THREAD = Endpoint.of(Endpoint.Method.PUT, "/channels/{channel_id}/threads", ThreadCreateResponse.class);
    public static final Endpoint<Void> DELETE_THREAD = Endpoint.of(Endpoint.Method.DELETE, "/channels/{channel_id}/threads/{thread_id}", Void.class);
    public static final Endpoint<ThreadDetailResponse> GET_THREAD = Endpoint.of(Endpoint.Method.GET, "/channels/{channel_id}/threads/{thread_id}", ThreadDetailResponse.class);
    public static final Endpoint<Announces> CREATE_GUILD_ANNOUNCE = Endpoint.of(Endpoint.Method.POST, "/guilds/{guild_id}/announces", Announces.class);
    public static final Endpoint<Void> DELETE_GUILD_ANNOUNCE = Endpoint.of(Endpoint.Method.DELETE, "/guilds/{guild_id}/announces/{message_id}", Void.class);

    // ---- ChannelPermissionApi ----
    public static final Endpoint<ChannelMemberPermissionsResponse> GET_CHANNEL_MEMBER_PERMISSIONS = Endpoint.of(Endpoint.Method.GET, "/channels/{channel_id}/members/{user_id}/permissions", ChannelMemberPermissionsResponse.class);
    public static final Endpoint<Void> UPDATE_CHANNEL_MEMBER_PERMISSIONS = Endpoint.of(Endpoint.Method.PUT, "/channels/{channel_id}/members/{user_id}/permissions", Void.class);
    public static final Endpoint<ChannelRolePermissionsResponse> GET_CHANNEL_ROLE_PERMISSIONS = Endpoint.of(Endpoint.Method.GET, "/channels/{channel_id}/roles/{role_id}/permissions", ChannelRolePermissionsResponse.class);
    public static final Endpoint<Void> UPDATE_CHANNEL_ROLE_PERMISSIONS = Endpoint.of(Endpoint.Method.PUT, "/channels/{channel_id}/roles/{role_id}/permissions", Void.class);
    public static final Endpoint<Void> REMOVE_GUILD_MEMBER_ROLE = Endpoint.of(Endpoint.Method.DELETE, "/guilds/{guild_id}/members/{user_id}/roles/{role_id}", Void.class);
    public static final Endpoint<Void> ADD_GUILD_MEMBER_ROLE = Endpoint.of(Endpoint.Method.PUT, "/guilds/{guild_id}/members/{user_id}/roles/{role_id}", Void.class);
    public static final Endpoint<GuildRolesResponse> LIST_GUILD_ROLES = Endpoint.of(Endpoint.Method.GET, "/guilds/{guild_id}/roles", GuildRolesResponse.class);
    public static final Endpoint<CreateGuildRoleResponse> CREATE_GUILD_ROLE = Endpoint.of(Endpoint.Method.POST, "/guilds/{guild_id}/roles", CreateGuildRoleResponse.class);
    public static final Endpoint<Void> DELETE_GUILD_ROLE = Endpoint.of(Endpoint.Method.DELETE, "/guilds/{guild_id}/roles/{role_id}", Void.class);
    public static final Endpoint<UpdateGuildRoleResponse> UPDATE_GUILD_ROLE = Endpoint.of(Endpoint.Method.PATCH, "/guilds/{guild_id}/roles/{role_id}", UpdateGuildRoleResponse.class);
    public static final Endpoint<GuildRoleMembersResponse> LIST_GUILD_ROLE_MEMBERS = Endpoint.of(Endpoint.Method.GET, "/guilds/{guild_id}/roles/{role_id}/members", GuildRoleMembersResponse.class);

    // ---- MenuApi ----
    public static final Endpoint<MenuResponse> GET_GLOBAL_MENU = Endpoint.of(Endpoint.Method.GET, "/v2/menu", MenuResponse.class);
    public static final Endpoint<MenuVersionResponse> UPDATE_GLOBAL_MENU = Endpoint.of(Endpoint.Method.PUT, "/v2/menu", MenuVersionResponse.class);

    // ---- PanelApi ----
    public static final Endpoint<PanelListResponse> LIST_PANELS = Endpoint.of(Endpoint.Method.GET, "/v2/panels", PanelListResponse.class);
    public static final Endpoint<CreatePanelResponse> CREATE_PANEL = Endpoint.of(Endpoint.Method.POST, "/v2/panels", CreatePanelResponse.class);
    public static final Endpoint<Void> DELETE_PANEL = Endpoint.of(Endpoint.Method.DELETE, "/v2/panels/{panel_id}", Void.class);
    public static final Endpoint<PanelDetailResponse> GET_PANEL = Endpoint.of(Endpoint.Method.GET, "/v2/panels/{panel_id}", PanelDetailResponse.class);
    public static final Endpoint<UpdatePanelResponse> UPDATE_PANEL = Endpoint.of(Endpoint.Method.PUT, "/v2/panels/{panel_id}", UpdatePanelResponse.class);
    public static final Endpoint<Void> UPDATE_PANEL_TARGET = Endpoint.of(Endpoint.Method.PUT, "/v2/panels/{panel_id}/target", Void.class);

    // ---- InteractionApi ----
    public static final Endpoint<Void> ACKNOWLEDGE_INTERACTION = Endpoint.of(Endpoint.Method.PUT, "/interactions/{interaction_id}", Void.class);

    // ---- GatewayApi ----
    public static final Endpoint<io.github.skiesworld.qqbot.websocket.GatewayInfo> FETCH_GATEWAY = Endpoint.of(Endpoint.Method.GET, "/gateway", io.github.skiesworld.qqbot.websocket.GatewayInfo.class);
    public static final Endpoint<io.github.skiesworld.qqbot.websocket.GatewayInfo> FETCH_BOT_GATEWAY = Endpoint.of(Endpoint.Method.GET, "/gateway/bot", io.github.skiesworld.qqbot.websocket.GatewayInfo.class);

}
