// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.api;

import io.github.skiesworld.qqbot.http.HttpTransport;

import java.util.Objects;

/** Typed entry point to every REST operation of the QQ Open Platform v2 API. */
public final class Api {

    private final HttpTransport http;

    private final MeApi me;
    private final C2CApi c2c;
    private final GroupApi group;
    private final GuildApi guild;
    private final ChannelApi channel;
    private final ChannelMessageApi channelMessages;
    private final ChannelContentApi channelContent;
    private final ChannelPermissionApi channelPermissions;
    private final MenuApi menu;
    private final PanelApi panels;
    private final InteractionApi interactions;
    private final GatewayApi gateway;

    public Api(HttpTransport http) {
        this.http = Objects.requireNonNull(http, "http");
        me = new MeApi(http);
        c2c = new C2CApi(http);
        group = new GroupApi(http);
        guild = new GuildApi(http);
        channel = new ChannelApi(http);
        channelMessages = new ChannelMessageApi(http);
        channelContent = new ChannelContentApi(http);
        channelPermissions = new ChannelPermissionApi(http);
        menu = new MenuApi(http);
        panels = new PanelApi(http);
        interactions = new InteractionApi(http);
        gateway = new GatewayApi(http);
    }

    /** Me operations. */
    public MeApi me() {
        return me;
    }

    /** C2C operations. */
    public C2CApi c2c() {
        return c2c;
    }

    /** Group operations. */
    public GroupApi group() {
        return group;
    }

    /** Guild operations. */
    public GuildApi guild() {
        return guild;
    }

    /** Channel operations. */
    public ChannelApi channel() {
        return channel;
    }

    /** Channel Message operations. */
    public ChannelMessageApi channelMessages() {
        return channelMessages;
    }

    /** Channel Content operations. */
    public ChannelContentApi channelContent() {
        return channelContent;
    }

    /** Channel Permission operations. */
    public ChannelPermissionApi channelPermissions() {
        return channelPermissions;
    }

    /** Menu operations. */
    public MenuApi menu() {
        return menu;
    }

    /** Panel operations. */
    public PanelApi panels() {
        return panels;
    }

    /** Interaction operations. */
    public InteractionApi interactions() {
        return interactions;
    }

    /** Gateway operations. */
    public GatewayApi gateway() {
        return gateway;
    }

    /** The transport every group class shares. */
    public HttpTransport http() {
        return http;
    }

}
