// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.api;

import io.github.skiesworld.qqbot.api.endpoint.Endpoints;
import io.github.skiesworld.qqbot.http.HttpTransport;
import io.github.skiesworld.qqbot.http.Params;
import io.github.skiesworld.qqbot.model.MediaUploadResponse;
import io.github.skiesworld.qqbot.model.SendMessageResponse;
import io.github.skiesworld.qqbot.model.SendStreamMessageResponse;
import io.github.skiesworld.qqbot.model.UploadPrepareResponse;
import io.github.skiesworld.qqbot.model.request.CompleteUploadPartRequest;
import io.github.skiesworld.qqbot.model.request.PrepareUploadRequest;
import io.github.skiesworld.qqbot.model.request.SendC2CMessageRequest;
import io.github.skiesworld.qqbot.model.request.SendC2CStreamMessageRequest;
import io.github.skiesworld.qqbot.model.request.UploadMediaRequest;

import java.util.Objects;

/** One-to-one chat with a user: messages, streaming replies and rich media uploads. */
public final class C2CApi {

    private final HttpTransport http;

    public C2CApi(HttpTransport http) {
        this.http = Objects.requireNonNull(http, "http");
    }

    /**
     * Report one finished chunk of a C2C upload; call uploadC2CMedia with the upload_id once every part is
     * done.
     */
    public void completeC2CUploadPart(String userId, CompleteUploadPartRequest request) {
        http.execute(Endpoints.COMPLETE_C2C_UPLOAD_PART, Params.of().pathValue("user_id", userId), request);
    }

    /**
     * Start a chunked C2C upload and receive the upload_id, the presigned part urls and the upload
     * configuration.
     */
    public UploadPrepareResponse prepareC2CMediaUpload(String userId, PrepareUploadRequest request) {
        return http.execute(Endpoints.PREPARE_C2C_MEDIA_UPLOAD, Params.of().pathValue("user_id", userId), request);
    }

    /**
     * Upload an image, video, voice or file to a C2C chat by url or by merging a chunked upload; the returned
     * file_info feeds the media field of sendC2CMessage and is valid for ttl seconds.
     */
    public MediaUploadResponse uploadC2CMedia(String userOpenid, UploadMediaRequest request) {
        return http.execute(Endpoints.UPLOAD_C2C_MEDIA, Params.of().pathValue("user_openid", userOpenid), request);
    }

    /**
     * Send a C2C message; passive replies must carry msg_id (from C2C_MESSAGE_CREATE) or event_id, are limited
     * to 4 answers per message and expire 5 minutes after the original event.
     */
    public SendMessageResponse sendC2CMessage(String userOpenid, SendC2CMessageRequest request) {
        return http.execute(Endpoints.SEND_C2C_MESSAGE, Params.of().pathValue("user_openid", userOpenid), request);
    }

    /**
     * Recall a C2C message the bot sent; messages older than 2 minutes cannot be recalled and the bot may only
     * recall its own messages.
     */
    public void recallC2CMessage(String userOpenid, String messageId) {
        http.execute(Endpoints.RECALL_C2C_MESSAGE,
                Params.of().pathValue("user_openid", userOpenid).pathValue("message_id", messageId),
                null);
    }

    /**
     * Push one chunk of a streamed C2C answer; keep stream_msg_id from the first response and increase index
     * from 0, finishing with input_state 10.
     */
    public SendStreamMessageResponse sendC2CStreamMessage(String userOpenid, SendC2CStreamMessageRequest request) {
        return http.execute(Endpoints.SEND_C2C_STREAM_MESSAGE, Params.of().pathValue("user_openid", userOpenid), request);
    }

}
