// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.api;

import io.github.skiesworld.qqbot.api.endpoint.Endpoints;
import io.github.skiesworld.qqbot.http.HttpTransport;
import io.github.skiesworld.qqbot.http.Params;
import io.github.skiesworld.qqbot.model.Announces;
import io.github.skiesworld.qqbot.model.AudioControl;
import io.github.skiesworld.qqbot.model.PinsMessage;
import io.github.skiesworld.qqbot.model.Schedule;
import io.github.skiesworld.qqbot.model.ThreadCreateResponse;
import io.github.skiesworld.qqbot.model.ThreadDetailResponse;
import io.github.skiesworld.qqbot.model.ThreadListResponse;
import io.github.skiesworld.qqbot.model.request.CreateGuildAnnounceRequest;
import io.github.skiesworld.qqbot.model.request.PublishThreadRequest;
import io.github.skiesworld.qqbot.model.request.ScheduleRequest;

import java.util.List;
import java.util.Objects;

/** Content of a sub-channel: pins, schedules, forum threads, audio, announces. */
public final class ChannelContentApi {

    private final HttpTransport http;

    public ChannelContentApi(HttpTransport http) {
        this.http = Objects.requireNonNull(http, "http");
    }

    /** Drive the voice bot of a sub-channel: play a url, pause, resume or stop, with optional text-to-speech. */
    public void controlChannelAudio(String channelId, AudioControl audioControl) {
        http.execute(Endpoints.CONTROL_CHANNEL_AUDIO, Params.of().pathValue("channel_id", channelId), audioControl);
    }

    /** Make the bot leave the microphone of a voice sub-channel. */
    public void stopChannelMic(String channelId) {
        http.execute(Endpoints.STOP_CHANNEL_MIC, Params.of().pathValue("channel_id", channelId), null);
    }

    /** Make the bot join the microphone of a voice sub-channel. */
    public void startChannelMic(String channelId) {
        http.execute(Endpoints.START_CHANNEL_MIC, Params.of().pathValue("channel_id", channelId), null);
    }

    /** List the pinned messages of a sub-channel. */
    public PinsMessage getPinnedMessages(String channelId) {
        return http.execute(Endpoints.GET_PINNED_MESSAGES, Params.of().pathValue("channel_id", channelId), null);
    }

    /** Remove a message pin from a sub-channel. */
    public void unpinMessage(String channelId, String messageId) {
        http.execute(Endpoints.UNPIN_MESSAGE,
                Params.of().pathValue("channel_id", channelId).pathValue("message_id", messageId),
                null);
    }

    /** Pin a message to the top of a sub-channel and return the new pin list. */
    public PinsMessage pinMessage(String channelId, String messageId) {
        return http.execute(Endpoints.PIN_MESSAGE,
                Params.of().pathValue("channel_id", channelId).pathValue("message_id", messageId),
                null);
    }

    /** List the schedules of a sub-channel from a start timestamp onwards. */
    public List<Schedule> listSchedules(String channelId, Long since) {
        return http.execute(Endpoints.LIST_SCHEDULES,
                Params.of().pathValue("channel_id", channelId).queryValue("since", since),
                null);
    }

    /** Create a schedule in a sub-channel; the id inside the schedule object is ignored. */
    public Schedule createSchedule(String channelId, ScheduleRequest request) {
        return http.execute(Endpoints.CREATE_SCHEDULE, Params.of().pathValue("channel_id", channelId), request);
    }

    /** Delete a schedule from a sub-channel. */
    public void deleteSchedule(String channelId, String scheduleId) {
        http.execute(Endpoints.DELETE_SCHEDULE,
                Params.of().pathValue("channel_id", channelId).pathValue("schedule_id", scheduleId),
                null);
    }

    /** Fetch one schedule of a sub-channel. */
    public Schedule getSchedule(String channelId, String scheduleId) {
        return http.execute(Endpoints.GET_SCHEDULE,
                Params.of().pathValue("channel_id", channelId).pathValue("schedule_id", scheduleId),
                null);
    }

    /** Replace a schedule in a sub-channel; the schedule object must not carry an id. */
    public Schedule updateSchedule(String channelId, String scheduleId, ScheduleRequest request) {
        return http.execute(Endpoints.UPDATE_SCHEDULE,
                Params.of().pathValue("channel_id", channelId).pathValue("schedule_id", scheduleId),
                request);
    }

    /** Page through the threads of a forum sub-channel until is_finish is set. */
    public ThreadListResponse listThreads(String channelId) {
        return http.execute(Endpoints.LIST_THREADS, Params.of().pathValue("channel_id", channelId), null);
    }

    /**
     * Publish a thread into a forum sub-channel; the content format follows Format and the result is audited
     * asynchronously.
     */
    public ThreadCreateResponse publishThread(String channelId, PublishThreadRequest request) {
        return http.execute(Endpoints.PUBLISH_THREAD, Params.of().pathValue("channel_id", channelId), request);
    }

    /** Delete a thread from a forum sub-channel. */
    public void deleteThread(String channelId, String threadId) {
        http.execute(Endpoints.DELETE_THREAD,
                Params.of().pathValue("channel_id", channelId).pathValue("thread_id", threadId),
                null);
    }

    /** Fetch one thread of a forum sub-channel. */
    public ThreadDetailResponse getThread(String channelId, String threadId) {
        return http.execute(Endpoints.GET_THREAD,
                Params.of().pathValue("channel_id", channelId).pathValue("thread_id", threadId),
                null);
    }

    /**
     * Publish a message as guild announce or welcome announce, or replace the recommended channel list in one
     * call.
     */
    public Announces createGuildAnnounce(String guildId, CreateGuildAnnounceRequest request) {
        return http.execute(Endpoints.CREATE_GUILD_ANNOUNCE, Params.of().pathValue("guild_id", guildId), request);
    }

    /** Delete a guild announcement. */
    public void deleteGuildAnnounce(String guildId, String messageId) {
        http.execute(Endpoints.DELETE_GUILD_ANNOUNCE,
                Params.of().pathValue("guild_id", guildId).pathValue("message_id", messageId),
                null);
    }

}
