// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.api;

import io.github.skiesworld.qqbot.api.endpoint.Endpoints;
import io.github.skiesworld.qqbot.http.HttpTransport;
import io.github.skiesworld.qqbot.http.Params;
import io.github.skiesworld.qqbot.model.Channel;
import io.github.skiesworld.qqbot.model.ChannelOnlineNumsResponse;
import io.github.skiesworld.qqbot.model.GuildChannelListResponse;
import io.github.skiesworld.qqbot.model.request.CreateChannelRequest;
import io.github.skiesworld.qqbot.model.request.UpdateChannelRequest;

import java.util.Objects;

/** Sub-channels: read, create, update, delete and live member counts. */
public final class ChannelApi {

    private final HttpTransport http;

    public ChannelApi(HttpTransport http) {
        this.http = Objects.requireNonNull(http, "http");
    }

    /** Delete a sub-channel. */
    public void deleteChannel(String channelId) {
        http.execute(Endpoints.DELETE_CHANNEL, Params.of().pathValue("channel_id", channelId), null);
    }

    /** Fetch one sub-channel. */
    public Channel getChannel(String channelId) {
        return http.execute(Endpoints.GET_CHANNEL, Params.of().pathValue("channel_id", channelId), null);
    }

    /** Rename, reorder, move or change the visibility and speak permission of a sub-channel. */
    public Channel updateChannel(String channelId, UpdateChannelRequest request) {
        return http.execute(Endpoints.UPDATE_CHANNEL, Params.of().pathValue("channel_id", channelId), request);
    }

    /** Fetch how many members are online in a voice sub-channel. */
    public ChannelOnlineNumsResponse getChannelOnlineNums(String channelId) {
        return http.execute(Endpoints.GET_CHANNEL_ONLINE_NUMS, Params.of().pathValue("channel_id", channelId), null);
    }

    /** List the sub-channels of a guild. */
    public GuildChannelListResponse listChannels(String guildId) {
        return http.execute(Endpoints.LIST_CHANNELS, Params.of().pathValue("guild_id", guildId), null);
    }

    /** Create a sub-channel in a guild; private channels must also list their members via private_user_ids. */
    public Channel createChannel(String guildId, CreateChannelRequest request) {
        return http.execute(Endpoints.CREATE_CHANNEL, Params.of().pathValue("guild_id", guildId), request);
    }

}
