// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.api;

import io.github.skiesworld.qqbot.api.endpoint.Endpoints;
import io.github.skiesworld.qqbot.http.HttpTransport;
import io.github.skiesworld.qqbot.http.Params;
import io.github.skiesworld.qqbot.model.Message;
import io.github.skiesworld.qqbot.model.ReactionUsersResponse;
import io.github.skiesworld.qqbot.model.request.SendChannelMessageRequest;

import java.util.Objects;

/** Messages inside sub-channels and inside direct message sessions. */
public final class ChannelMessageApi {

    private final HttpTransport http;

    public ChannelMessageApi(HttpTransport http) {
        this.http = Objects.requireNonNull(http, "http");
    }

    /**
     * Send a message into a sub-channel; passive replies must carry msg_id or event_id and are only accepted
     * for 5 minutes after the original event.
     */
    public Message sendChannelMessage(String channelId, SendChannelMessageRequest request) {
        return http.execute(Endpoints.SEND_CHANNEL_MESSAGE, Params.of().pathValue("channel_id", channelId), request);
    }

    /** Recall a sub-channel message, optionally hiding the grey hint line. */
    public void recallChannelMessage(String channelId, String messageId, Boolean hidetip) {
        http.execute(Endpoints.RECALL_CHANNEL_MESSAGE,
                Params.of()
                        .pathValue("channel_id", channelId)
                        .pathValue("message_id", messageId)
                        .queryValue("hidetip", hidetip),
                null);
    }

    /** Remove the bot's own emoji reaction from a message. */
    public void deleteMessageReaction(String channelId, String messageId, String type, String id) {
        http.execute(Endpoints.DELETE_MESSAGE_REACTION,
                Params.of()
                        .pathValue("channel_id", channelId)
                        .pathValue("message_id", messageId)
                        .pathValue("type", type)
                        .pathValue("id", id),
                null);
    }

    /**
     * List who reacted with a given emoji; limit applies to the first call only and later pages continue with
     * the returned cookie.
     */
    public ReactionUsersResponse listMessageReactionUsers(
            String channelId,
            String messageId,
            String type,
            String id,
            String cookie,
            Long limit) {
        return http.execute(Endpoints.LIST_MESSAGE_REACTION_USERS,
                Params.of()
                        .pathValue("channel_id", channelId)
                        .pathValue("message_id", messageId)
                        .pathValue("type", type)
                        .pathValue("id", id)
                        .queryValue("cookie", cookie)
                        .queryValue("limit", limit),
                null);
    }

    /** Add the bot's emoji reaction to a message; type follows EmojiType and id an entry of the emoji list. */
    public void addMessageReaction(String channelId, String messageId, String type, String id) {
        http.execute(Endpoints.ADD_MESSAGE_REACTION,
                Params.of()
                        .pathValue("channel_id", channelId)
                        .pathValue("message_id", messageId)
                        .pathValue("type", type)
                        .pathValue("id", id),
                null);
    }

    /**
     * Send a message into a direct message session created with createDirectMessageSession; passive replies
     * must carry msg_id or event_id.
     */
    public Message sendDirectMessage(String guildId, SendChannelMessageRequest request) {
        return http.execute(Endpoints.SEND_DIRECT_MESSAGE, Params.of().pathValue("guild_id", guildId), request);
    }

    /** Recall a message from a direct message session, optionally hiding the grey hint line. */
    public void recallDirectMessage(String guildId, String messageId, Boolean hidetip) {
        http.execute(Endpoints.RECALL_DIRECT_MESSAGE,
                Params.of()
                        .pathValue("guild_id", guildId)
                        .pathValue("message_id", messageId)
                        .queryValue("hidetip", hidetip),
                null);
    }

}
