// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.api;

import io.github.skiesworld.qqbot.api.endpoint.Endpoints;
import io.github.skiesworld.qqbot.http.HttpTransport;
import io.github.skiesworld.qqbot.http.Params;
import io.github.skiesworld.qqbot.model.ChannelMemberPermissionsResponse;
import io.github.skiesworld.qqbot.model.ChannelRolePermissionsResponse;
import io.github.skiesworld.qqbot.model.CreateGuildRoleResponse;
import io.github.skiesworld.qqbot.model.GuildRoleMembersResponse;
import io.github.skiesworld.qqbot.model.GuildRolesResponse;
import io.github.skiesworld.qqbot.model.UpdateGuildRoleResponse;
import io.github.skiesworld.qqbot.model.request.CreateGuildRoleRequest;
import io.github.skiesworld.qqbot.model.request.GuildMemberRoleRequest;
import io.github.skiesworld.qqbot.model.request.UpdateChannelMemberPermissionsRequest;
import io.github.skiesworld.qqbot.model.request.UpdateChannelRolePermissionsRequest;
import io.github.skiesworld.qqbot.model.request.UpdateGuildRoleRequest;

import java.util.Objects;

/** Roles and the sub-channel permission bit maps of members and roles. */
public final class ChannelPermissionApi {

    private final HttpTransport http;

    public ChannelPermissionApi(HttpTransport http) {
        this.http = Objects.requireNonNull(http, "http");
    }

    /** Read the permission bit map a member holds in a sub-channel. */
    public ChannelMemberPermissionsResponse getChannelMemberPermissions(String channelId, String userId) {
        return http.execute(Endpoints.GET_CHANNEL_MEMBER_PERMISSIONS,
                Params.of().pathValue("channel_id", channelId).pathValue("user_id", userId),
                null);
    }

    /** Grant and revoke sub-channel permissions for one member with decimal bit map strings. */
    public void updateChannelMemberPermissions(String channelId, String userId, String add, String remove) {
        UpdateChannelMemberPermissionsRequest request = new UpdateChannelMemberPermissionsRequest();
        request.add = add;
        request.remove = remove;
        http.execute(Endpoints.UPDATE_CHANNEL_MEMBER_PERMISSIONS,
                Params.of().pathValue("channel_id", channelId).pathValue("user_id", userId),
                request);
    }

    /** Read the permission bit map a role holds in a sub-channel. */
    public ChannelRolePermissionsResponse getChannelRolePermissions(String channelId, String roleId) {
        return http.execute(Endpoints.GET_CHANNEL_ROLE_PERMISSIONS,
                Params.of().pathValue("channel_id", channelId).pathValue("role_id", roleId),
                null);
    }

    /** Grant and revoke sub-channel permissions for one role with decimal bit map strings. */
    public void updateChannelRolePermissions(String channelId, String roleId, String add, String remove) {
        UpdateChannelRolePermissionsRequest request = new UpdateChannelRolePermissionsRequest();
        request.add = add;
        request.remove = remove;
        http.execute(Endpoints.UPDATE_CHANNEL_ROLE_PERMISSIONS,
                Params.of().pathValue("channel_id", channelId).pathValue("role_id", roleId),
                request);
    }

    /**
     * Revoke a role from a guild member; pass a channel object with only the id filled to scope the role to a
     * sub-channel.
     */
    public void removeGuildMemberRole(
            String guildId,
            String userId,
            String roleId,
            GuildMemberRoleRequest request) {
        http.execute(Endpoints.REMOVE_GUILD_MEMBER_ROLE,
                Params.of().pathValue("guild_id", guildId).pathValue("user_id", userId).pathValue("role_id", roleId),
                request);
    }

    /**
     * Grant a role to a guild member; pass a channel object with only the id filled to scope the role to a
     * sub-channel.
     */
    public void addGuildMemberRole(String guildId, String userId, String roleId, GuildMemberRoleRequest request) {
        http.execute(Endpoints.ADD_GUILD_MEMBER_ROLE,
                Params.of().pathValue("guild_id", guildId).pathValue("user_id", userId).pathValue("role_id", roleId),
                request);
    }

    /** List the roles of a guild together with the role quota. */
    public GuildRolesResponse listGuildRoles(String guildId) {
        return http.execute(Endpoints.LIST_GUILD_ROLES, Params.of().pathValue("guild_id", guildId), null);
    }

    /** Create a role in a guild; color is the decimal value of the ARGB hex colour. */
    public CreateGuildRoleResponse createGuildRole(String guildId, CreateGuildRoleRequest request) {
        return http.execute(Endpoints.CREATE_GUILD_ROLE, Params.of().pathValue("guild_id", guildId), request);
    }

    /** Delete a role from a guild. */
    public void deleteGuildRole(String guildId, String roleId) {
        http.execute(Endpoints.DELETE_GUILD_ROLE,
                Params.of().pathValue("guild_id", guildId).pathValue("role_id", roleId),
                null);
    }

    /** Rename a role or change its colour and whether it is shown separately. */
    public UpdateGuildRoleResponse updateGuildRole(String guildId, String roleId, UpdateGuildRoleRequest request) {
        return http.execute(Endpoints.UPDATE_GUILD_ROLE,
                Params.of().pathValue("guild_id", guildId).pathValue("role_id", roleId),
                request);
    }

    /** Page through the members holding a role with start_index and a limit of 1-400. */
    public GuildRoleMembersResponse listGuildRoleMembers(
            String guildId,
            String roleId,
            String startIndex,
            Long limit) {
        return http.execute(Endpoints.LIST_GUILD_ROLE_MEMBERS,
                Params.of()
                        .pathValue("guild_id", guildId)
                        .pathValue("role_id", roleId)
                        .queryValue("start_index", startIndex)
                        .queryValue("limit", limit),
                null);
    }

}
