// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.api;

import io.github.skiesworld.qqbot.api.endpoint.Endpoints;
import io.github.skiesworld.qqbot.http.HttpTransport;
import io.github.skiesworld.qqbot.http.Params;

import java.util.Objects;

/** WebSocket gateway urls. */
public final class GatewayApi {

    private final HttpTransport http;

    public GatewayApi(HttpTransport http) {
        this.http = Objects.requireNonNull(http, "http");
    }

    /** Fetch the WebSocket endpoint the bot should connect to. */
    public io.github.skiesworld.qqbot.websocket.GatewayInfo fetchGateway() {
        return http.execute(Endpoints.FETCH_GATEWAY, Params.of(), null);
    }

    /** Fetch the WebSocket endpoint plus the recommended shard count and the session start quota. */
    public io.github.skiesworld.qqbot.websocket.GatewayInfo fetchBotGateway() {
        return http.execute(Endpoints.FETCH_BOT_GATEWAY, Params.of(), null);
    }

}
