// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.api;

import io.github.skiesworld.qqbot.api.endpoint.Endpoints;
import io.github.skiesworld.qqbot.http.HttpTransport;
import io.github.skiesworld.qqbot.http.Params;
import io.github.skiesworld.qqbot.model.BatchRemoveGroupMembersResponse;
import io.github.skiesworld.qqbot.model.CreateJoinApprovalStrategyResponse;
import io.github.skiesworld.qqbot.model.GroupBlacklistOperationResponse;
import io.github.skiesworld.qqbot.model.GroupBlacklistResponse;
import io.github.skiesworld.qqbot.model.GroupBotState;
import io.github.skiesworld.qqbot.model.GroupInfo;
import io.github.skiesworld.qqbot.model.GroupJoinRequestListResponse;
import io.github.skiesworld.qqbot.model.GroupMember;
import io.github.skiesworld.qqbot.model.GroupMemberListResponse;
import io.github.skiesworld.qqbot.model.GroupMuteStateResponse;
import io.github.skiesworld.qqbot.model.JoinApprovalStrategyListResponse;
import io.github.skiesworld.qqbot.model.MediaUploadResponse;
import io.github.skiesworld.qqbot.model.SendMessageResponse;
import io.github.skiesworld.qqbot.model.UpdateJoinApprovalStrategyResponse;
import io.github.skiesworld.qqbot.model.UpdateStrategyWhitelistResponse;
import io.github.skiesworld.qqbot.model.UploadPrepareResponse;
import io.github.skiesworld.qqbot.model.UrlLinkResponse;
import io.github.skiesworld.qqbot.model.request.ApproveGroupJoinRequestRequest;
import io.github.skiesworld.qqbot.model.request.BatchRemoveGroupMembersRequest;
import io.github.skiesworld.qqbot.model.request.CompleteUploadPartRequest;
import io.github.skiesworld.qqbot.model.request.CreateJoinApprovalStrategyRequest;
import io.github.skiesworld.qqbot.model.request.GenerateUrlLinkRequest;
import io.github.skiesworld.qqbot.model.request.PrepareUploadRequest;
import io.github.skiesworld.qqbot.model.request.SendGroupMessageRequest;
import io.github.skiesworld.qqbot.model.request.SetGroupMemberMuteRequest;
import io.github.skiesworld.qqbot.model.request.UpdateGroupBlacklistRequest;
import io.github.skiesworld.qqbot.model.request.UpdateJoinApprovalStrategyRequest;
import io.github.skiesworld.qqbot.model.request.UpdateStrategyWhitelistRequest;
import io.github.skiesworld.qqbot.model.request.UploadMediaRequest;

import java.util.Objects;

/** QQ group chats: messages, members, mutes, join requests and approval strategies. */
public final class GroupApi {

    private final HttpTransport http;

    public GroupApi(HttpTransport http) {
        this.http = Objects.requireNonNull(http, "http");
    }

    /** Generate the bot's group share link, optionally echoing callback_data back to the visitor. */
    public UrlLinkResponse generateUrlLink(GenerateUrlLinkRequest request) {
        return http.execute(Endpoints.GENERATE_URL_LINK, Params.of(), request);
    }

    /** Page through the automatic join approval strategies of the bot. */
    public JoinApprovalStrategyListResponse listJoinApprovalStrategies(String cursor, Long limit) {
        return http.execute(Endpoints.LIST_JOIN_APPROVAL_STRATEGIES,
                Params.of().queryValue("cursor", cursor).queryValue("limit", limit),
                null);
    }

    /** Create an automatic join approval strategy for the given groups with an optional expiry. */
    public CreateJoinApprovalStrategyResponse createJoinApprovalStrategy(CreateJoinApprovalStrategyRequest request) {
        return http.execute(Endpoints.CREATE_JOIN_APPROVAL_STRATEGY, Params.of(), request);
    }

    /** Delete an automatic join approval strategy. */
    public void deleteJoinApprovalStrategy(String strategyId) {
        http.execute(Endpoints.DELETE_JOIN_APPROVAL_STRATEGY,
                Params.of().pathValue("strategy_id", strategyId),
                null);
    }

    /** Enable or disable a strategy, move its expiry, or add and remove the groups it covers. */
    public UpdateJoinApprovalStrategyResponse updateJoinApprovalStrategy(
            String strategyId,
            UpdateJoinApprovalStrategyRequest request) {
        return http.execute(Endpoints.UPDATE_JOIN_APPROVAL_STRATEGY,
                Params.of().pathValue("strategy_id", strategyId),
                request);
    }

    /** Run an automatic join approval strategy against the pending join requests right now. */
    public void executeJoinApprovalStrategy(String strategyId) {
        http.execute(Endpoints.EXECUTE_JOIN_APPROVAL_STRATEGY,
                Params.of().pathValue("strategy_id", strategyId),
                null);
    }

    /** Add or remove the QQ numbers exempt from an automatic join approval strategy. */
    public UpdateStrategyWhitelistResponse updateJoinApprovalStrategyWhitelist(
            String strategyId,
            UpdateStrategyWhitelistRequest request) {
        return http.execute(Endpoints.UPDATE_JOIN_APPROVAL_STRATEGY_WHITELIST,
                Params.of().pathValue("strategy_id", strategyId),
                request);
    }

    /**
     * Report one finished chunk of a group upload; call uploadGroupMedia with the upload_id once every part is
     * done.
     */
    public void completeGroupUploadPart(String groupId, CompleteUploadPartRequest request) {
        http.execute(Endpoints.COMPLETE_GROUP_UPLOAD_PART, Params.of().pathValue("group_id", groupId), request);
    }

    /**
     * Start a chunked group upload and receive the upload_id, the presigned part urls and the upload
     * configuration.
     */
    public UploadPrepareResponse prepareGroupMediaUpload(String groupId, PrepareUploadRequest request) {
        return http.execute(Endpoints.PREPARE_GROUP_MEDIA_UPLOAD, Params.of().pathValue("group_id", groupId), request);
    }

    /** Approve or decline a join request with op approve/decline; the bot must be a group administrator. */
    public void approveGroupJoinRequest(
            String groupOpenid,
            String memberOpenid,
            ApproveGroupJoinRequestRequest request) {
        http.execute(Endpoints.APPROVE_GROUP_JOIN_REQUEST,
                Params.of().pathValue("group_openid", groupOpenid).pathValue("member_openid", memberOpenid),
                request);
    }

    /** Kick several members out of a group in one call; the bot must be the owner or an administrator. */
    public BatchRemoveGroupMembersResponse batchRemoveGroupMembers(
            String groupOpenid,
            BatchRemoveGroupMembersRequest request) {
        return http.execute(Endpoints.BATCH_REMOVE_GROUP_MEMBERS,
                Params.of().pathValue("group_openid", groupOpenid),
                request);
    }

    /** Fetch the bot's own state inside a group, including whether proactive messages are allowed. */
    public GroupBotState getGroupBotState(String groupOpenid) {
        return http.execute(Endpoints.GET_GROUP_BOT_STATE, Params.of().pathValue("group_openid", groupOpenid), null);
    }

    /**
     * Upload an image, video, voice or file to a group by url or by merging a chunked upload; the returned
     * file_info feeds the media field of sendGroupMessage and is valid for ttl seconds.
     */
    public MediaUploadResponse uploadGroupMedia(String groupOpenid, UploadMediaRequest request) {
        return http.execute(Endpoints.UPLOAD_GROUP_MEDIA, Params.of().pathValue("group_openid", groupOpenid), request);
    }

    /** Fetch a group's name, memo, tags and member count. */
    public GroupInfo getGroupInfo(String groupOpenid) {
        return http.execute(Endpoints.GET_GROUP_INFO, Params.of().pathValue("group_openid", groupOpenid), null);
    }

    /** Page through pending join requests of a group. */
    public GroupJoinRequestListResponse listGroupJoinRequests(String groupOpenid, String cursor, Long limit) {
        return http.execute(Endpoints.LIST_GROUP_JOIN_REQUESTS,
                Params.of()
                        .pathValue("group_openid", groupOpenid)
                        .queryValue("cursor", cursor)
                        .queryValue("limit", limit),
                null);
    }

    /** Page through the members a group has blacklisted. */
    public GroupBlacklistResponse listGroupBlacklist(String groupOpenid, String cursor, Long limit) {
        return http.execute(Endpoints.LIST_GROUP_BLACKLIST,
                Params.of()
                        .pathValue("group_openid", groupOpenid)
                        .queryValue("cursor", cursor)
                        .queryValue("limit", limit),
                null);
    }

    /** Add members to or remove them from the group blacklist, returning the openids the operation failed for. */
    public GroupBlacklistOperationResponse updateGroupBlacklist(
            String groupOpenid,
            UpdateGroupBlacklistRequest request) {
        return http.execute(Endpoints.UPDATE_GROUP_BLACKLIST, Params.of().pathValue("group_openid", groupOpenid), request);
    }

    /** Page through a group's members with the cursor returned by the previous call. */
    public GroupMemberListResponse listGroupMembers(String groupOpenid, String cursor) {
        return http.execute(Endpoints.LIST_GROUP_MEMBERS,
                Params.of().pathValue("group_openid", groupOpenid).queryValue("cursor", cursor),
                null);
    }

    /** Fetch one group member's profile and role. */
    public GroupMember getGroupMember(String groupOpenid, String memberOpenid) {
        return http.execute(Endpoints.GET_GROUP_MEMBER,
                Params.of().pathValue("group_openid", groupOpenid).pathValue("member_openid", memberOpenid),
                null);
    }

    /**
     * Send a group message; passive replies must carry msg_id (from GROUP_AT_MESSAGE_CREATE or
     * GROUP_MESSAGE_CREATE) or event_id, are limited to 5 answers within 5 minutes, and group messages do not
     * support streaming fields.
     */
    public SendMessageResponse sendGroupMessage(String groupOpenid, SendGroupMessageRequest request) {
        return http.execute(Endpoints.SEND_GROUP_MESSAGE, Params.of().pathValue("group_openid", groupOpenid), request);
    }

    /**
     * Recall a group message; messages older than 2 minutes cannot be recalled, and a bot that is not an
     * administrator may only recall its own messages.
     */
    public void recallGroupMessage(String groupOpenid, String messageId) {
        http.execute(Endpoints.RECALL_GROUP_MESSAGE,
                Params.of().pathValue("group_openid", groupOpenid).pathValue("message_id", messageId),
                null);
    }

    /** Read the whole-group mute rule and the per-member mute list; the bot must be a group administrator. */
    public GroupMuteStateResponse getGroupMuteState(String groupOpenid) {
        return http.execute(Endpoints.GET_GROUP_MUTE_STATE, Params.of().pathValue("group_openid", groupOpenid), null);
    }

    /**
     * Mute, update or unmute group members, at most 20 per call and at most 30 days long; the bot must be a
     * group administrator.
     */
    public void setGroupMemberMute(String groupOpenid, SetGroupMemberMuteRequest request) {
        http.execute(Endpoints.SET_GROUP_MEMBER_MUTE, Params.of().pathValue("group_openid", groupOpenid), request);
    }

}
