// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.api;

import io.github.skiesworld.qqbot.api.endpoint.Endpoints;
import io.github.skiesworld.qqbot.http.HttpTransport;
import io.github.skiesworld.qqbot.http.Params;
import io.github.skiesworld.qqbot.model.ApiPermissionDemand;
import io.github.skiesworld.qqbot.model.Guild;
import io.github.skiesworld.qqbot.model.GuildApiPermissionResponse;
import io.github.skiesworld.qqbot.model.GuildMember;
import io.github.skiesworld.qqbot.model.MessageSetting;
import io.github.skiesworld.qqbot.model.request.CreateApiPermissionDemandRequest;
import io.github.skiesworld.qqbot.model.request.SetGuildMemberMuteRequest;
import io.github.skiesworld.qqbot.model.request.SetGuildMembersMuteRequest;
import io.github.skiesworld.qqbot.model.request.SetGuildMuteRequest;

import java.util.List;
import java.util.Objects;

/** Guilds the bot serves: profile, members, mutes and API permissions. */
public final class GuildApi {

    private final HttpTransport http;

    public GuildApi(HttpTransport http) {
        this.http = Objects.requireNonNull(http, "http");
    }

    /** Fetch one guild the bot has joined. */
    public Guild getGuild(String guildId) {
        return http.execute(Endpoints.GET_GUILD, Params.of().pathValue("guild_id", guildId), null);
    }

    /** List the API permissions of a guild with the authorization status of each one. */
    public GuildApiPermissionResponse listGuildApiPermissions(String guildId) {
        return http.execute(Endpoints.LIST_GUILD_API_PERMISSIONS, Params.of().pathValue("guild_id", guildId), null);
    }

    /**
     * Send an authorization request link into a sub-channel so a guild administrator can grant the bot an API
     * permission.
     */
    public ApiPermissionDemand createApiPermissionDemand(String guildId, CreateApiPermissionDemandRequest request) {
        return http.execute(Endpoints.CREATE_API_PERMISSION_DEMAND, Params.of().pathValue("guild_id", guildId), request);
    }

    /** Page through a guild's members with the last member id of the previous page and a limit of 1-400. */
    public List<GuildMember> listGuildMembers(String guildId, String after, Long limit) {
        return http.execute(Endpoints.LIST_GUILD_MEMBERS,
                Params.of().pathValue("guild_id", guildId).queryValue("after", after).queryValue("limit", limit),
                null);
    }

    /** Kick a guild member, optionally blacklisting them and recalling their messages of the last N days. */
    public void removeGuildMember(String guildId, String userId, Boolean addBlacklist, Long deleteHistoryMsgDays) {
        http.execute(Endpoints.REMOVE_GUILD_MEMBER,
                Params.of()
                        .pathValue("guild_id", guildId)
                        .pathValue("user_id", userId)
                        .queryValue("add_blacklist", addBlacklist)
                        .queryValue("delete_history_msg_days", deleteHistoryMsgDays),
                null);
    }

    /** Fetch one guild member with the user profile, nickname and role ids. */
    public GuildMember getGuildMember(String guildId, String userId) {
        return http.execute(Endpoints.GET_GUILD_MEMBER,
                Params.of().pathValue("guild_id", guildId).pathValue("user_id", userId),
                null);
    }

    /**
     * Mute one guild member for a number of seconds or until an absolute timestamp; when both are sent the
     * timestamp wins.
     */
    public void setGuildMemberMute(String guildId, String userId, String muteEndTimestamp, String muteSeconds) {
        SetGuildMemberMuteRequest request = new SetGuildMemberMuteRequest();
        request.muteEndTimestamp = muteEndTimestamp;
        request.muteSeconds = muteSeconds;
        http.execute(Endpoints.SET_GUILD_MEMBER_MUTE,
                Params.of().pathValue("guild_id", guildId).pathValue("user_id", userId),
                request);
    }

    /** Read whether the bot may create direct messages and push messages, and the per-channel push quota. */
    public MessageSetting getGuildMessageSetting(String guildId) {
        return http.execute(Endpoints.GET_GUILD_MESSAGE_SETTING, Params.of().pathValue("guild_id", guildId), null);
    }

    /**
     * Mute a whole guild for a number of seconds or until an absolute timestamp; when both are sent the
     * timestamp wins.
     */
    public void setGuildMute(String guildId, String muteEndTimestamp, String muteSeconds) {
        SetGuildMuteRequest request = new SetGuildMuteRequest();
        request.muteEndTimestamp = muteEndTimestamp;
        request.muteSeconds = muteSeconds;
        http.execute(Endpoints.SET_GUILD_MUTE, Params.of().pathValue("guild_id", guildId), request);
    }

    /**
     * Mute a batch of guild members (non-admins); send mute_end_timestamp or mute_seconds, and the string "0"
     * to lift the mute. At most 20 members per call and 30 days long.
     */
    public void setGuildMembersMute(String guildId, SetGuildMembersMuteRequest request) {
        http.execute(Endpoints.SET_GUILD_MEMBERS_MUTE, Params.of().pathValue("guild_id", guildId), request);
    }

}
