// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.api;

import io.github.skiesworld.qqbot.api.endpoint.Endpoints;
import io.github.skiesworld.qqbot.http.HttpTransport;
import io.github.skiesworld.qqbot.http.Params;
import io.github.skiesworld.qqbot.model.request.AcknowledgeInteractionRequest;

import java.util.Objects;

/** Responses to INTERACTION_CREATE events. */
public final class InteractionApi {

    private final HttpTransport http;

    public InteractionApi(HttpTransport http) {
        this.http = Objects.requireNonNull(http, "http");
    }

    /**
     * Acknowledge an INTERACTION_CREATE event; only button (type 11) and shortcut menu (type 12) interactions
     * need it, and each interaction_id can be answered once before it expires.
     */
    public void acknowledgeInteraction(String interactionId, Long code) {
        AcknowledgeInteractionRequest request = new AcknowledgeInteractionRequest();
        request.code = code;
        http.execute(Endpoints.ACKNOWLEDGE_INTERACTION,
                Params.of().pathValue("interaction_id", interactionId),
                request);
    }

}
