// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.api;

import io.github.skiesworld.qqbot.api.endpoint.Endpoints;
import io.github.skiesworld.qqbot.http.HttpTransport;
import io.github.skiesworld.qqbot.http.Params;
import io.github.skiesworld.qqbot.model.BotProfile;
import io.github.skiesworld.qqbot.model.Dms;
import io.github.skiesworld.qqbot.model.GuildListResponse;
import io.github.skiesworld.qqbot.model.request.CreateDmsRequest;

import java.util.Objects;

/** Bot identity: its own profile, the guilds it joined and direct message sessions. */
public final class MeApi {

    private final HttpTransport http;

    public MeApi(HttpTransport http) {
        this.http = Objects.requireNonNull(http, "http");
    }

    /** Fetch the bot's own profile, including the union ids and the group share link. */
    public BotProfile getBotProfile() {
        return http.execute(Endpoints.GET_BOT_PROFILE, Params.of(), null);
    }

    /** Open (or reuse) a private chat session with a user in a guild before sending direct messages. */
    public Dms createDirectMessageSession(CreateDmsRequest request) {
        return http.execute(Endpoints.CREATE_DIRECT_MESSAGE_SESSION, Params.of(), request);
    }

    /** List the guilds the bot has joined; page with before/after ids and a limit of 1-100. */
    public GuildListResponse listBotGuilds(String before, String after, Long limit) {
        return http.execute(Endpoints.LIST_BOT_GUILDS,
                Params.of().queryValue("before", before).queryValue("after", after).queryValue("limit", limit),
                null);
    }

}
