// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.api;

import io.github.skiesworld.qqbot.api.endpoint.Endpoints;
import io.github.skiesworld.qqbot.http.HttpTransport;
import io.github.skiesworld.qqbot.http.Params;
import io.github.skiesworld.qqbot.model.MenuResponse;
import io.github.skiesworld.qqbot.model.MenuVersionResponse;
import io.github.skiesworld.qqbot.model.request.UpdateGlobalMenuRequest;

import java.util.Objects;

/** The bot global custom menu. */
public final class MenuApi {

    private final HttpTransport http;

    public MenuApi(HttpTransport http) {
        this.http = Objects.requireNonNull(http, "http");
    }

    /** Fetch the bot's global custom menu together with its version. */
    public MenuResponse getGlobalMenu() {
        return http.execute(Endpoints.GET_GLOBAL_MENU, Params.of(), null);
    }

    /** Replace the whole global custom menu; the returned version increments on success. */
    public MenuVersionResponse updateGlobalMenu(UpdateGlobalMenuRequest request) {
        return http.execute(Endpoints.UPDATE_GLOBAL_MENU, Params.of(), request);
    }

}
