// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.api;

import io.github.skiesworld.qqbot.api.endpoint.Endpoints;
import io.github.skiesworld.qqbot.http.HttpTransport;
import io.github.skiesworld.qqbot.http.Params;
import io.github.skiesworld.qqbot.model.CreatePanelResponse;
import io.github.skiesworld.qqbot.model.PanelDetailResponse;
import io.github.skiesworld.qqbot.model.PanelListResponse;
import io.github.skiesworld.qqbot.model.UpdatePanelResponse;
import io.github.skiesworld.qqbot.model.request.CreatePanelRequest;
import io.github.skiesworld.qqbot.model.request.UpdatePanelRequest;
import io.github.skiesworld.qqbot.model.request.UpdatePanelTargetRequest;

import java.util.Objects;

/** Command panels and the users or groups they are bound to. */
public final class PanelApi {

    private final HttpTransport http;

    public PanelApi(HttpTransport http) {
        this.http = Objects.requireNonNull(http, "http");
    }

    /** List command panels for a scope (c2c, group, channel or dm), paginated with cursor and limit. */
    public PanelListResponse listPanels(String scope, String cursor, Long limit) {
        return http.execute(Endpoints.LIST_PANELS,
                Params.of().queryValue("scope", scope).queryValue("cursor", cursor).queryValue("limit", limit),
                null);
    }

    /** Create a command panel and bind it to all users or to the listed user/group openids. */
    public CreatePanelResponse createPanel(CreatePanelRequest request) {
        return http.execute(Endpoints.CREATE_PANEL, Params.of(), request);
    }

    /** Delete a command panel. */
    public void deletePanel(String panelId) {
        http.execute(Endpoints.DELETE_PANEL, Params.of().pathValue("panel_id", panelId), null);
    }

    /** Fetch one command panel with its items and its bound users and groups. */
    public PanelDetailResponse getPanel(String panelId) {
        return http.execute(Endpoints.GET_PANEL, Params.of().pathValue("panel_id", panelId), null);
    }

    /** Replace the items of a command panel; the returned version is the new panel version. */
    public UpdatePanelResponse updatePanel(String panelId, UpdatePanelRequest request) {
        return http.execute(Endpoints.UPDATE_PANEL, Params.of().pathValue("panel_id", panelId), request);
    }

    /**
     * Add or remove the users (c2c scope) or groups (group scope) a panel is bound to, at most 20 openids per
     * call; channel and dm scopes are global and do not support this.
     */
    public void updatePanelTarget(String panelId, UpdatePanelTargetRequest request) {
        http.execute(Endpoints.UPDATE_PANEL_TARGET, Params.of().pathValue("panel_id", panelId), request);
    }

}
