// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.event;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Routing facts docgen writes from naming.json's eventRoles: the envelope each event name is built into, and
 * the payload keys that name the people taking part in it. A handler parameter type means one of these
 * envelopes, so adding an event is a row here rather than a guess somewhere in the bus.
 */
public final class EventRouting {

    /** The envelope a dispatch is built into. */
    public enum Envelope {

        /** Carries message text and an author, so it reads as one turn in a conversation. */
        MESSAGE,

        /** Something happened somewhere: no text here, and no answer owed to it. */
        NOTICE,

        /** Something happened that the bot owes an answer to, and the platform stops waiting. */
        REQUEST,

        /** Session lifecycle plus anything this table does not place: the bare envelope. */
        PLAIN
    }

/** One event: its envelope plus the payload keys that name the people taking part. */
    public static final class Row {

        static final Row UNKNOWN = new Row("UNKNOWN", Envelope.PLAIN, List.of(), List.of());

        private final String name;
        private final Envelope envelope;
        private final List<String> actorKeys;
        private final List<String> subjectKeys;

        Row(String name, Envelope envelope, List<String> actorKeys, List<String> subjectKeys) {
            this.name = name;
            this.envelope = envelope;
            this.actorKeys = actorKeys;
            this.subjectKeys = subjectKeys;
        }

        /** The {@code t} value of this row, or {@code UNKNOWN} for a name the table does not place. */
        public String name() {
            return name;
        }

        public Envelope envelope() {
            return envelope;
        }

        /** Who set the event off, by payload key in preference order; empty when no key names one. */
        public List<String> actorKeys() {
            return actorKeys;
        }

        /** Who the event happened to, by payload key in preference order; empty when no key names one. */
        public List<String> subjectKeys() {
            return subjectKeys;
        }
    }

    private static final Map<String, Row> BY_NAME = rows();

    private static Map<String, Row> rows() {
        Map<String, Row> rows = new LinkedHashMap<>();
        // PLAIN the session opening; nothing happened somewhere
        rows.put("READY", new Row("READY", Envelope.PLAIN, List.of(), List.of()));
        // PLAIN the session resumed; nothing happened somewhere
        rows.put("RESUMED", new Row("RESUMED", Envelope.PLAIN, List.of(), List.of()));
        // MESSAGE
        rows.put("C2C_MESSAGE_CREATE", new Row("C2C_MESSAGE_CREATE", Envelope.MESSAGE, List.of(), List.of()));
        // MESSAGE
        rows.put("GROUP_AT_MESSAGE_CREATE", new Row("GROUP_AT_MESSAGE_CREATE", Envelope.MESSAGE, List.of(), List.of()));
        // MESSAGE
        rows.put("GROUP_MESSAGE_CREATE", new Row("GROUP_MESSAGE_CREATE", Envelope.MESSAGE, List.of(), List.of()));
        // MESSAGE
        rows.put("AT_MESSAGE_CREATE", new Row("AT_MESSAGE_CREATE", Envelope.MESSAGE, List.of(), List.of()));
        // MESSAGE
        rows.put("MESSAGE_CREATE", new Row("MESSAGE_CREATE", Envelope.MESSAGE, List.of(), List.of()));
        // MESSAGE
        rows.put("DIRECT_MESSAGE_CREATE", new Row("DIRECT_MESSAGE_CREATE", Envelope.MESSAGE, List.of(), List.of()));
        // REQUEST the applicant waits on approve()/deny()
        rows.put("GROUP_JOIN_REQUEST", new Row("GROUP_JOIN_REQUEST", Envelope.REQUEST, List.of("member_openid"), List.of()));
        // REQUEST the button stays pending until acknowledgeInteraction answers it
        rows.put("INTERACTION_CREATE", new Row("INTERACTION_CREATE", Envelope.REQUEST, List.of("user_openid", "group_member_openid"), List.of()));
        // NOTICE
        rows.put("FRIEND_ADD", new Row("FRIEND_ADD", Envelope.NOTICE, List.of("openid"), List.of()));
        // NOTICE
        rows.put("FRIEND_DEL", new Row("FRIEND_DEL", Envelope.NOTICE, List.of("openid"), List.of()));
        // NOTICE
        rows.put("C2C_MSG_REJECT", new Row("C2C_MSG_REJECT", Envelope.NOTICE, List.of("openid"), List.of()));
        // NOTICE
        rows.put("C2C_MSG_RECEIVE", new Row("C2C_MSG_RECEIVE", Envelope.NOTICE, List.of("openid"), List.of()));
        // NOTICE the member who pulled the bot in; nobody is acted upon
        rows.put("GROUP_ADD_ROBOT", new Row("GROUP_ADD_ROBOT", Envelope.NOTICE, List.of("op_member_openid"), List.of()));
        // NOTICE
        rows.put("GROUP_DEL_ROBOT", new Row("GROUP_DEL_ROBOT", Envelope.NOTICE, List.of("op_member_openid"), List.of()));
        // NOTICE
        rows.put("GROUP_MSG_REJECT", new Row("GROUP_MSG_REJECT", Envelope.NOTICE, List.of("op_member_openid"), List.of()));
        // NOTICE
        rows.put("GROUP_MSG_RECEIVE", new Row("GROUP_MSG_RECEIVE", Envelope.NOTICE, List.of("op_member_openid"), List.of()));
        // NOTICE
        rows.put("SUBSCRIBE_MESSAGE_STATUS", new Row("SUBSCRIBE_MESSAGE_STATUS", Envelope.NOTICE, List.of("openid"), List.of()));
        // NOTICE member_openid is the member; nothing evidences an operator
        rows.put("GROUP_MEMBER_ADD", new Row("GROUP_MEMBER_ADD", Envelope.NOTICE, List.of(), List.of("member_openid")));
        // NOTICE
        rows.put("GROUP_MEMBER_REMOVE", new Row("GROUP_MEMBER_REMOVE", Envelope.NOTICE, List.of(), List.of("member_openid")));
        // NOTICE owner_id/op_user_id are guild-space ids, not openids
        rows.put("GUILD_CREATE", new Row("GUILD_CREATE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("GUILD_UPDATE", new Row("GUILD_UPDATE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("GUILD_DELETE", new Row("GUILD_DELETE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("CHANNEL_CREATE", new Row("CHANNEL_CREATE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("CHANNEL_UPDATE", new Row("CHANNEL_UPDATE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("CHANNEL_DELETE", new Row("CHANNEL_DELETE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE the member object reports a nick, not an id
        rows.put("GUILD_MEMBER_ADD", new Row("GUILD_MEMBER_ADD", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("GUILD_MEMBER_UPDATE", new Row("GUILD_MEMBER_UPDATE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("GUILD_MEMBER_REMOVE", new Row("GUILD_MEMBER_REMOVE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE no text left to read, so not a message envelope
        rows.put("MESSAGE_DELETE", new Row("MESSAGE_DELETE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("PUBLIC_MESSAGE_DELETE", new Row("PUBLIC_MESSAGE_DELETE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("DIRECT_MESSAGE_DELETE", new Row("DIRECT_MESSAGE_DELETE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE user_id is a guild-space id, not an openid
        rows.put("MESSAGE_REACTION_ADD", new Row("MESSAGE_REACTION_ADD", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("MESSAGE_REACTION_REMOVE", new Row("MESSAGE_REACTION_REMOVE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE a verdict on the bot's own send; nothing is owed back for it
        rows.put("MESSAGE_AUDIT_PASS", new Row("MESSAGE_AUDIT_PASS", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("MESSAGE_AUDIT_REJECT", new Row("MESSAGE_AUDIT_REJECT", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("FORUM_THREAD_CREATE", new Row("FORUM_THREAD_CREATE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("FORUM_THREAD_UPDATE", new Row("FORUM_THREAD_UPDATE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("FORUM_THREAD_DELETE", new Row("FORUM_THREAD_DELETE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("FORUM_POST_CREATE", new Row("FORUM_POST_CREATE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("FORUM_POST_DELETE", new Row("FORUM_POST_DELETE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("FORUM_REPLY_CREATE", new Row("FORUM_REPLY_CREATE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("FORUM_REPLY_DELETE", new Row("FORUM_REPLY_DELETE", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE a verdict about a publish, but nothing is owed back for it
        rows.put("FORUM_PUBLISH_AUDIT_RESULT", new Row("FORUM_PUBLISH_AUDIT_RESULT", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE a text-to-speech job started; no answer is owed
        rows.put("AUDIO_START", new Row("AUDIO_START", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("AUDIO_FINISH", new Row("AUDIO_FINISH", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE someone spoke up in the channel
        rows.put("AUDIO_ON_MIC", new Row("AUDIO_ON_MIC", Envelope.NOTICE, List.of(), List.of()));
        // NOTICE
        rows.put("AUDIO_OFF_MIC", new Row("AUDIO_OFF_MIC", Envelope.NOTICE, List.of(), List.of()));
        return Collections.unmodifiableMap(rows);
    }

    /** {@code eventName}'s row; a {@link Envelope#PLAIN} row for names newer than this table. */
    public static Row of(String eventName) {
        return eventName == null ? Row.UNKNOWN : BY_NAME.getOrDefault(eventName, Row.UNKNOWN);
    }

    /** The modelled events built into {@code envelope}, in the order this table lists them. */
    public static List<EventType> eventTypes(Envelope envelope) {
        List<EventType> types = new ArrayList<>();
        for (Row row : BY_NAME.values()) {
            if (row.envelope == envelope) {
                EventType type = EventType.from(row.name);
                if (type != EventType.UNKNOWN) {
                    types.add(type);
                }
            }
        }
        return List.copyOf(types);
    }

    private EventRouting() {
    }
}
