// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

/** Request body of PUT /interactions/{interaction_id}. */
public class AcknowledgeInteractionRequest {

    @SerializedName("code")
    public Long code;

    public AcknowledgeInteractionRequest() {
    }
}
