// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

/** Request body of POST /v2/groups/{group_openid}/approval_join_request/{member_openid}. */
public class ApproveGroupJoinRequestRequest {

    @SerializedName("op")
    public String op;

    @SerializedName("join_request_id")
    public String joinRequestId;

    @SerializedName("reject_reason")
    public String rejectReason;

    @SerializedName("add_to_member_blacklist")
    public Boolean addToMemberBlacklist;

    public ApproveGroupJoinRequestRequest() {
    }
}
