// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Request body of POST /v2/groups/{group_openid}/batch_remove_members. */
public class BatchRemoveGroupMembersRequest {

    @SerializedName("member_openids")
    public List<String> memberOpenids;

    @SerializedName("add_to_member_blacklist")
    public Boolean addToMemberBlacklist;

    public BatchRemoveGroupMembersRequest() {
    }
}
