// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

/** Request body of POST /v2/users/{user_id}/upload_part_finish. */
public class CompleteUploadPartRequest {

    @SerializedName("upload_id")
    public String uploadId;

    @SerializedName("part_index")
    public Long partIndex;

    @SerializedName("block_size")
    public String blockSize;

    @SerializedName("md5")
    public String md5;

    public CompleteUploadPartRequest() {
    }
}
