// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Request body of POST /guilds/{guild_id}/channels. */
public class CreateChannelRequest {

    @SerializedName("name")
    public String name;

    @SerializedName("type")
    public Long type;

    @SerializedName("sub_type")
    public Long subType;

    @SerializedName("position")
    public Long position;

    @SerializedName("parent_id")
    public String parentId;

    @SerializedName("private_type")
    public Long privateType;

    @SerializedName("private_user_ids")
    public List<String> privateUserIds;

    @SerializedName("speak_permission")
    public Long speakPermission;

    @SerializedName("application_id")
    public String applicationId;

    public CreateChannelRequest() {
    }
}
