// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.ApiPermissionDemandIdentify;

/** Request body of POST /guilds/{guild_id}/api_permission/demand. */
public class CreateApiPermissionDemandRequest {

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("api_identify")
    public ApiPermissionDemandIdentify apiIdentify;

    @SerializedName("desc")
    public String desc;

    public CreateApiPermissionDemandRequest() {
    }
}
