// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.Panel;

import java.util.List;

/** Request body of POST /v2/panels. */
public class CreatePanelRequest {

    @SerializedName("scope")
    public String scope;

    @SerializedName("target_type")
    public String targetType;

    @SerializedName("user_openids")
    public List<String> userOpenids;

    @SerializedName("group_openids")
    public List<String> groupOpenids;

    @SerializedName("panel")
    public Panel panel;

    public CreatePanelRequest() {
    }
}
