// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

/** Request body of POST /guilds/{guild_id}/roles. */
public class CreateGuildRoleRequest {

    @SerializedName("name")
    public String name;

    @SerializedName("color")
    public Long color;

    @SerializedName("hoist")
    public Long hoist;

    public CreateGuildRoleRequest() {
    }
}
