// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

/** Request body of POST /users/@me/dms. */
public class CreateDmsRequest {

    @SerializedName("recipient_id")
    public String recipientId;

    @SerializedName("source_guild_id")
    public String sourceGuildId;

    public CreateDmsRequest() {
    }
}
