// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.RecommendChannel;

import java.util.List;

/** Request body of POST /guilds/{guild_id}/announces. */
public class CreateGuildAnnounceRequest {

    @SerializedName("message_id")
    public String messageId;

    @SerializedName("channel_id")
    public String channelId;

    @SerializedName("announces_type")
    public Long announcesType;

    @SerializedName("recommend_channels")
    public List<RecommendChannel> recommendChannels;

    public CreateGuildAnnounceRequest() {
    }
}
