// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Request body of POST /v2/groups/join_approval_strategy. */
public class CreateJoinApprovalStrategyRequest {

    @SerializedName("group_openids")
    public List<String> groupOpenids;

    @SerializedName("group_ids")
    public List<String> groupIds;

    @SerializedName("is_enable")
    public String isEnable;

    @SerializedName("expire_at")
    public String expireAt;

    @SerializedName("remark")
    public String remark;

    public CreateJoinApprovalStrategyRequest() {
    }
}
