// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

/** Request body of POST /v2/generate_url_link. */
public class GenerateUrlLinkRequest {

    @SerializedName("callback_data")
    public String callbackData;

    public GenerateUrlLinkRequest() {
    }
}
