// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.Channel;

/** Request body of DELETE /guilds/{guild_id}/members/{user_id}/roles/{role_id}. */
public class GuildMemberRoleRequest {

    @SerializedName("channel")
    public Channel channel;

    public GuildMemberRoleRequest() {
    }
}
