// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

/** Request body of POST /v2/users/{user_id}/upload_prepare. */
public class PrepareUploadRequest {

    @SerializedName("file_type")
    public Long fileType;

    @SerializedName("file_size")
    public String fileSize;

    @SerializedName("file_name")
    public String fileName;

    @SerializedName("md5")
    public String md5;

    @SerializedName("sha1")
    public String sha1;

    @SerializedName("md5_10m")
    public String md510m;

    public PrepareUploadRequest() {
    }
}
