// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

/** Request body of PUT /channels/{channel_id}/threads. */
public class PublishThreadRequest {

    @SerializedName("title")
    public String title;

    @SerializedName("content")
    public String content;

    @SerializedName("format")
    public Long format;

    public PublishThreadRequest() {
    }
}
