// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.Schedule;

/** Request body of POST /channels/{channel_id}/schedules. */
public class ScheduleRequest {

    @SerializedName("schedule")
    public Schedule schedule;

    public ScheduleRequest() {
    }
}
