// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.MessageArk;
import io.github.skiesworld.qqbot.model.MessageEmbed;
import io.github.skiesworld.qqbot.model.MessageMarkdown;
import io.github.skiesworld.qqbot.model.MessageReference;

/** Request body of POST /channels/{channel_id}/messages. */
public class SendChannelMessageRequest {

    @SerializedName("content")
    public String content;

    @SerializedName("embed")
    public MessageEmbed embed;

    @SerializedName("ark")
    public MessageArk ark;

    @SerializedName("message_reference")
    public MessageReference messageReference;

    @SerializedName("image")
    public String image;

    @SerializedName("msg_id")
    public String msgId;

    @SerializedName("event_id")
    public String eventId;

    @SerializedName("markdown")
    public MessageMarkdown markdown;

    public SendChannelMessageRequest() {
    }
}
