// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.Keyboard;
import io.github.skiesworld.qqbot.model.MediaInfo;
import io.github.skiesworld.qqbot.model.MessageMarkdown;
import io.github.skiesworld.qqbot.model.MessageReference;

/** Request body of POST /v2/groups/{group_openid}/messages. */
public class SendGroupMessageRequest {

    @SerializedName("msg_type")
    public Long msgType;

    @SerializedName("content")
    public String content;

    @SerializedName("markdown")
    public MessageMarkdown markdown;

    @SerializedName("keyboard")
    public Keyboard keyboard;

    @SerializedName("msg_id")
    public String msgId;

    @SerializedName("event_id")
    public String eventId;

    @SerializedName("msg_seq")
    public Long msgSeq;

    @SerializedName("media")
    public MediaInfo media;

    @SerializedName("message_reference")
    public MessageReference messageReference;

    public SendGroupMessageRequest() {
    }
}
