// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

/** Request body of POST /v2/users/{user_openid}/stream_messages. */
public class SendC2CStreamMessageRequest {

    @SerializedName("input_mode")
    public String inputMode;

    @SerializedName("input_state")
    public Long inputState;

    @SerializedName("index")
    public Long index;

    @SerializedName("content_type")
    public String contentType;

    @SerializedName("content_raw")
    public String contentRaw;

    @SerializedName("event_id")
    public String eventId;

    @SerializedName("msg_id")
    public String msgId;

    @SerializedName("stream_msg_id")
    public String streamMsgId;

    @SerializedName("msg_seq")
    public Long msgSeq;

    @SerializedName("is_wakeup")
    public Boolean isWakeup;

    public SendC2CStreamMessageRequest() {
    }
}
