// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.SetMemberMuteState;

import java.util.List;

/** Request body of POST /v2/groups/{group_openid}/restrict_chat_setting. */
public class SetGroupMemberMuteRequest {

    @SerializedName("members")
    public List<SetMemberMuteState> members;

    public SetGroupMemberMuteRequest() {
    }
}
