// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

/** Request body of PATCH /guilds/{guild_id}/members/{user_id}/mute. */
public class SetGuildMemberMuteRequest {

    @SerializedName("mute_end_timestamp")
    public String muteEndTimestamp;

    @SerializedName("mute_seconds")
    public String muteSeconds;

    public SetGuildMemberMuteRequest() {
    }
}
