// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.Menu;

/** Request body of PUT /v2/menu. */
public class UpdateGlobalMenuRequest {

    @SerializedName("menu")
    public Menu menu;

    public UpdateGlobalMenuRequest() {
    }
}
