// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

/** Request body of PUT /channels/{channel_id}/roles/{role_id}/permissions. */
public class UpdateChannelRolePermissionsRequest {

    @SerializedName("add")
    public String add;

    @SerializedName("remove")
    public String remove;

    public UpdateChannelRolePermissionsRequest() {
    }
}
