// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Request body of POST /v2/groups/join_approval_strategy/{strategy_id}/whitelist_users. */
public class UpdateStrategyWhitelistRequest {

    @SerializedName("op")
    public String op;

    @SerializedName("whitelist_users")
    public List<String> whitelistUsers;

    public UpdateStrategyWhitelistRequest() {
    }
}
