// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.GroupAction;

/** Request body of PATCH /v2/groups/join_approval_strategy/{strategy_id}. */
public class UpdateJoinApprovalStrategyRequest {

    @SerializedName("is_enable")
    public String isEnable;

    @SerializedName("expire_at")
    public String expireAt;

    @SerializedName("group_action")
    public GroupAction groupAction;

    @SerializedName("remark")
    public String remark;

    public UpdateJoinApprovalStrategyRequest() {
    }
}
