// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

/** Request body of PATCH /guilds/{guild_id}/roles/{role_id}. */
public class UpdateGuildRoleRequest {

    @SerializedName("name")
    public String name;

    @SerializedName("color")
    public Long color;

    @SerializedName("hoist")
    public Long hoist;

    public UpdateGuildRoleRequest() {
    }
}
