// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

/** Request body of PATCH /channels/{channel_id}. */
public class UpdateChannelRequest {

    @SerializedName("name")
    public String name;

    @SerializedName("position")
    public Long position;

    @SerializedName("parent_id")
    public String parentId;

    @SerializedName("private_type")
    public Long privateType;

    @SerializedName("speak_permission")
    public Long speakPermission;

    public UpdateChannelRequest() {
    }
}
