// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/** Request body of PUT /v2/panels/{panel_id}/target. */
public class UpdatePanelTargetRequest {

    @SerializedName("op")
    public String op;

    @SerializedName("user_openids")
    public List<String> userOpenids;

    @SerializedName("group_openids")
    public List<String> groupOpenids;

    public UpdatePanelTargetRequest() {
    }
}
