// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;
import io.github.skiesworld.qqbot.model.Panel;

/** Request body of PUT /v2/panels/{panel_id}. */
public class UpdatePanelRequest {

    @SerializedName("panel")
    public Panel panel;

    public UpdatePanelRequest() {
    }
}
