// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.request;

import com.google.gson.annotations.SerializedName;

/** Request body of POST /v2/users/{user_openid}/files. */
public class UploadMediaRequest {

    @SerializedName("file_type")
    public Long fileType;

    @SerializedName("url")
    public String url;

    @SerializedName("srv_send_msg")
    public Boolean srvSendMsg;

    @SerializedName("file_name")
    public String fileName;

    @SerializedName("upload_id")
    public String uploadId;

    public UploadMediaRequest() {
    }
}
