package io.github.skiesworld.qqbot.handler;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import io.github.skiesworld.qqbot.QQBotClient;
import io.github.skiesworld.qqbot.api.Api;
import io.github.skiesworld.qqbot.event.EventBus;
import io.github.skiesworld.qqbot.event.EventEnvelopes;
import io.github.skiesworld.qqbot.event.EventModels;
import io.github.skiesworld.qqbot.event.EventType;
import io.github.skiesworld.qqbot.event.QQEvent;
import io.github.skiesworld.qqbot.event.QQMessageEvent;
import io.github.skiesworld.qqbot.util.Json;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.ServiceLoader;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.Supplier;

/**
 * Turns {@link On} methods into event routes, so a bot can be a class instead of a lambda pile.
 *
 * <p>Every parameter is filled by type:
 * <table border="1">
 *   <caption>bindable parameter types</caption>
 *   <tr><td>{@link QQEvent} and the envelopes under it</td>
 *       <td>the dispatch, as the shape that event has; a parameter narrower than the events the method listens to
 *       is refused at registration, and one the dispatch cannot answer skips it</td></tr>
 *   <tr><td>{@link OnContext}</td><td>the command match, and only on a method that declared a command</td></tr>
 *   <tr><td>{@link EventType}</td><td>the resolved event type</td></tr>
 *   <tr><td>{@link JsonObject} / {@link JsonElement}</td><td>the raw {@code d} member</td></tr>
 *   <tr><td>{@link Api} / {@link QQBotClient}</td><td>needs a registry obtained from
 *       {@link QQBotClient#handlers()}; {@link EventBus#register(Object)} has no client to hand out</td></tr>
 *   <tr><td>any other reference type</td><td>the payload, deserialized into that type</td></tr>
 * </table>
 *
 * <p>Registration is strict so mistakes surface at startup rather than on the first matching event: a routed
 * method that listens to nothing, a primitive or array parameter, a command on an event with no text, an
 * {@code Api} parameter on a client-less registry all fail there. A gate that cannot be built fails there too.
 * A payload that will not bind, an envelope the dispatch is not, a command whose text does not match and a gate
 * that denies all skip that one invocation, and exceptions from user code never reach the receiving thread.
 *
 * <p>Assembly has two paths and they share this class: call {@link #register(Object)} with an instance, or
 * implement {@link BotHandler} and let {@link #registerDiscovered()} find it through {@link ServiceLoader} — the
 * manifest that makes discovery work is generated by the optional annotation processor.
 */
public final class HandlerRegistry {

    private static final Logger log = LoggerFactory.getLogger(HandlerRegistry.class);

    private final EventBus bus;
    private final QQBotClient client;
    private final Map<Class<? extends Permission>, Supplier<? extends Permission>> permissionFactories =
            new ConcurrentHashMap<>();
    private final List<CommandMatcher> matchers = new CopyOnWriteArrayList<>();
    private volatile List<String> prefixes = List.of("");

    public HandlerRegistry(EventBus bus) {
        this(bus, null);
    }

    public HandlerRegistry(EventBus bus, QQBotClient client) {
        this.bus = Objects.requireNonNull(bus, "bus");
        this.client = client;
    }

    /**
     * Prefixes a message may start with, for every command registered from now on. The empty string means "no
     * prefix needed"; a bot that must be addressed can drop it. Commands already registered keep what they got.
     */
    public HandlerRegistry usePrefixes(String... prefixes) {
        List<String> copy = new ArrayList<>();
        for (String prefix : prefixes) {
            copy.add(prefix == null ? "" : prefix);
        }
        this.prefixes = List.copyOf(copy.isEmpty() ? List.of("") : copy);
        return this;
    }

    /**
     * Teach a gate how to build a rule that needs configuration, e.g.
     * {@code bot.handlers().permission(MySuperUsers.class, () -> new MySuperUsers(loadedIds))}. Rules with a
     * public no-arg constructor need nothing here.
     */
    public HandlerRegistry permission(Class<? extends Permission> type, Supplier<? extends Permission> factory) {
        permissionFactories.put(Objects.requireNonNull(type, "type"),
                Objects.requireNonNull(factory, "factory"));
        return this;
    }

    /** Register every {@link On} method of {@code handler}. */
    public EventBus.Subscription register(Object handler) {
        List<Route> planned = new ArrayList<>();
        for (Method method : candidateMethods(handler.getClass())) {
            if (method.isAnnotationPresent(On.class)) {
                planned.add(plan(handler, method));
            }
        }
        if (planned.isEmpty()) {
            throw new IllegalArgumentException("nothing to register on " + handler.getClass().getName()
                    + "; annotate at least one method with @On or add a listener directly");
        }
        List<EventBus.Subscription> subs = new ArrayList<>();
        for (Route route : planned) {
            subs.add(route.attach());
        }
        return () -> {
            for (EventBus.Subscription s : subs) {
                s.close();
            }
        };
    }

    /** Register every {@link BotHandler} visible to the current thread's context class loader. */
    public int registerDiscovered() {
        return registerDiscovered(Thread.currentThread().getContextClassLoader());
    }

    /**
     * Register discovered handlers, returning how many took part. A handler that fails to bind is logged and
     * skipped: one broken class in a jar must not stop the bot from starting.
     */
    public int registerDiscovered(ClassLoader loader) {
        int n = 0;
        for (BotHandler handler : ServiceLoader.load(BotHandler.class, loader)) {
            try {
                register(handler);
                n++;
            } catch (RuntimeException | LinkageError e) {
                log.error("skipping discovered handler {}", handler.getClass().getName(), e);
            }
        }
        return n;
    }

    /** One line per registered command, for a {@code /help} answer or a startup log. */
    public List<String> describe() {
        return matchers.stream().map(CommandMatcher::describe).toList();
    }

    private Route plan(Object handler, Method method) {
        On on = method.getAnnotation(On.class);
        String name = describe(handler, method);
        if (method.getReturnType() != void.class) {
            throw new IllegalArgumentException(name + " is routed but returns "
                    + method.getReturnType().getSimpleName() + "; its result would be discarded. Make it void, or"
                    + " mark it @Check if it is a gate");
        }
        List<Class<?>> envelopes = envelopeParams(method);
        CommandMatcher matcher = on.command().length == 0 ? null : new CommandMatcher(on, name, prefixes);
        List<EventType> types = new ArrayList<>(Arrays.asList(on.value()));
        List<String> names = Arrays.asList(on.name());
        boolean any = false;

        if (types.isEmpty() && names.isEmpty()) {
            types.addAll(inferred(envelopes));
            if (types.isEmpty() && matcher != null) {
                types.addAll(QQMessageEvent.eventTypes());
            }
            if (types.isEmpty()) {
                if (envelopes.contains(QQEvent.class)) {
                    any = true;
                } else {
                    throw new IllegalArgumentException(name + " listens to no event; name one in @On, or take a"
                            + " QQEvent or envelope parameter and it is inferred from it");
                }
            }
        }
        if (matcher != null) {
            requireCommandEvents(name, types, names);
        }
        if (!names.isEmpty()) {
            for (Class<?> envelope : envelopes) {
                if (EventEnvelopes.eventTypes(envelope) != null) {
                    throw new IllegalArgumentException(name + " takes a " + envelope.getSimpleName()
                            + " parameter but @On.name() routes unmodelled events, which are never built as one;"
                            + " take QQEvent or JsonObject instead");
                }
            }
        }
        for (Class<?> envelope : envelopes) {
            List<EventType> covered = EventEnvelopes.eventTypes(envelope);
            if (covered != null && types.stream().noneMatch(covered::contains) && !any) {
                throw new IllegalArgumentException(name + " takes a " + envelope.getSimpleName()
                        + " parameter but none of the events it listens to is built as one, so it could never run");
            }
        }
        if (takesParam(method, OnContext.class) && matcher == null) {
            throw new IllegalArgumentException(name + " asks for an OnContext but declares no command; give @On a"
                    + " command() or take the envelope parameter you want to read");
        }
        method.setAccessible(true);
        return new Route(handler, method, on, types, names, any, binders(handler, method, matcher),
                gateFor(handler, method, on), matcher);
    }

    /** The events the method's envelope parameters stand for, deduplicated in parameter order. */
    private static List<EventType> inferred(List<Class<?>> envelopes) {
        Set<EventType> types = new LinkedHashSet<>();
        for (Class<?> envelope : envelopes) {
            List<EventType> covered = EventEnvelopes.eventTypes(envelope);
            if (covered != null) {
                types.addAll(covered);
            }
        }
        return new ArrayList<>(types);
    }

    private static void requireCommandEvents(String name, List<EventType> types, List<String> names) {
        if (!names.isEmpty()) {
            throw new IllegalArgumentException(name + " is a command on raw event names " + names + ", which carry"
                    + " no text to match");
        }
        List<EventType> messages = QQMessageEvent.eventTypes();
        for (EventType type : types) {
            if (!messages.contains(type)) {
                throw new IllegalArgumentException(name + " is a command on " + type + ", which carries no message"
                        + " text; a command there could never match");
            }
        }
    }

    private static List<Class<?>> envelopeParams(Method method) {
        List<Class<?>> found = new ArrayList<>();
        for (Class<?> type : method.getParameterTypes()) {
            if (QQEvent.class.isAssignableFrom(type) && type != JsonObject.class) {
                found.add(type);
            }
        }
        return found;
    }

    private static boolean takesParam(Method method, Class<?> type) {
        for (Class<?> parameter : method.getParameterTypes()) {
            if (parameter == type) {
                return true;
            }
        }
        return false;
    }

    /**
     * One planned {@link On} method: what it listens to, how its arguments are filled, and the gates in front of
     * it. {@link #attach()} is the only thing that reaches the bus, so nothing half-planned can run.
     */
    private final class Route {

        private final Object handler;
        private final Method method;
        private final On on;
        private final List<EventType> types;
        private final List<String> names;
        private final boolean any;
        private final Function<QQEvent, Object>[] binders;
        private final Predicate<QQEvent> gate;
        private final CommandMatcher matcher;

        Route(Object handler, Method method, On on, List<EventType> types, List<String> names, boolean any,
                Function<QQEvent, Object>[] binders, Predicate<QQEvent> gate, CommandMatcher matcher) {
            this.handler = handler;
            this.method = method;
            this.on = on;
            this.types = List.copyOf(types);
            this.names = List.copyOf(names);
            this.any = any;
            this.binders = binders;
            this.gate = gate;
            this.matcher = matcher;
        }

        EventBus.Subscription attach() {
            EventBus.Subscription subscription = bus.add(this::dispatch, types, names, any, on.priority(),
                    on.block());
            if (matcher != null) {
                matchers.add(matcher);
                return () -> {
                    matchers.remove(matcher);
                    subscription.close();
                };
            }
            return subscription;
        }

        /** True is what tells the bus this route took the dispatch, which is what {@code block} decides with. */
        boolean dispatch(QQEvent event) {
            Object[] args = new Object[binders.length];
            for (int i = 0; i < binders.length; i++) {
                args[i] = binders[i].apply(event);
                if (args[i] == null) {
                    log.debug("skipping {} for {}: argument {} of type {} could not be bound",
                            describe(handler, method), event.name(), i, method.getParameterTypes()[i].getName());
                    return false;
                }
            }
            if (gate != null && !gate.test(event)) {
                log.debug("check denied {} for {}", describe(handler, method), event.name());
                return false;
            }
            try {
                method.invoke(handler, args);
                return true;
            } catch (InvocationTargetException e) {
                log.error("handler {} threw for {}", describe(handler, method), event.name(), e.getCause());
            } catch (ReflectiveOperationException | RuntimeException e) {
                log.error("handler {} could not run for {}", describe(handler, method), event.name(), e);
            }
            return false;
        }
    }

    /**
     * The gates in front of {@code method}: the names and types its {@link Check} gives, plus the rule types its
     * {@link On#requires()} lists. Built here so a typo or an unbuildable rule fails at registration instead of
     * leaving the action ungated at runtime.
     */
    private Predicate<QQEvent> gateFor(Object handler, Method method, On on) {
        Check check = method.getAnnotation(Check.class);
        List<Predicate<QQEvent>> gates = new ArrayList<>();
        for (String name : check == null ? new String[0] : check.value()) {
            gates.add(namedCheck(handler, method, name));
        }
        List<Class<? extends Permission>> types = new ArrayList<>();
        if (check != null) {
            types.addAll(Arrays.asList(check.type()));
        }
        types.addAll(Arrays.asList(on.requires()));
        for (Class<? extends Permission> type : types) {
            gates.add(typedCheck(handler, method, type));
        }
        if (gates.isEmpty()) {
            return null;
        }
        return event -> gates.stream().allMatch(gate -> gate.test(event));
    }

    private Predicate<QQEvent> namedCheck(Object handler, Method gated, String name) {
        List<Method> found = new ArrayList<>();
        for (Method candidate : candidateMethods(handler.getClass())) {
            if (!candidate.getName().equals(name) || candidate.equals(gated)) {
                continue;
            }
            if (candidate.getAnnotation(Check.class) == null) {
                continue;
            }
            if (candidate.getReturnType() != boolean.class && candidate.getReturnType() != Boolean.class) {
                throw new IllegalArgumentException("check \"" + name + "\" on " + handler.getClass().getName()
                        + " returns " + candidate.getReturnType().getSimpleName() + "; a check returns boolean");
            }
            found.add(candidate);
        }
        if (found.isEmpty()) {
            throw new IllegalArgumentException(describe(handler, gated) + " requires check \"" + name
                    + "\", which no @Check method on " + handler.getClass().getName() + " provides");
        }
        if (found.size() > 1) {
            throw new IllegalArgumentException("check \"" + name + "\" is overloaded on "
                    + handler.getClass().getName() + "; give the variants distinct names so it is clear which runs");
        }
        Method check = found.get(0);
        check.setAccessible(true);
        Function<QQEvent, Object>[] binders = binders(handler, check, null);
        return event -> {
            Object[] args = new Object[binders.length];
            for (int i = 0; i < binders.length; i++) {
                args[i] = binders[i].apply(event);
                if (args[i] == null) {
                    log.debug("check {} denied {}: argument {} could not be bound", name, event.name(), i);
                    return false;
                }
            }
            try {
                return Boolean.TRUE.equals(check.invoke(handler, args));
            } catch (InvocationTargetException e) {
                log.error("check {} threw for {}, denying", name, event.name(), e.getCause());
                return false;
            } catch (ReflectiveOperationException | RuntimeException e) {
                log.error("check {} could not run for {}, denying", name, event.name(), e);
                return false;
            }
        };
    }

    private Predicate<QQEvent> typedCheck(Object handler, Method gated, Class<? extends Permission> type) {
        Permission rule = permissionFactories.containsKey(type)
                ? permissionFactories.get(type).get()
                : instantiate(type);
        if (rule == null) {
            throw new IllegalArgumentException(describe(handler, gated) + " requires " + type.getName()
                    + ", which has no public no-arg constructor; register one with"
                    + " bot.handlers().permission(" + type.getSimpleName() + ".class, () -> new ...)");
        }
        Method check = boundCheck(rule);
        if (check == null) {
            return event -> {
                try {
                    return rule.allows(event, client);
                } catch (RuntimeException e) {
                    log.error("check {} threw for {}, denying", type.getSimpleName(), event.name(), e);
                    return false;
                }
            };
        }
        check.setAccessible(true);
        Function<QQEvent, Object>[] binders = binders(rule, check, null);
        return event -> {
            Object[] args = new Object[binders.length];
            for (int i = 0; i < binders.length; i++) {
                args[i] = binders[i].apply(event);
                if (args[i] == null) {
                    return false;
                }
            }
            try {
                return Boolean.TRUE.equals(check.invoke(rule, args));
            } catch (InvocationTargetException e) {
                log.error("check {} threw for {}, denying", type.getSimpleName(), event.name(), e.getCause());
                return false;
            } catch (ReflectiveOperationException | RuntimeException e) {
                log.error("check {} could not run for {}, denying", type.getSimpleName(), event.name(), e);
                return false;
            }
        };
    }

    /**
     * The rule's own question, when it asks one: a single {@code boolean} method other than
     * {@link Permission#allows}, whose parameters are filled exactly like a handler's. A rule with none is asked
     * through {@code allows}, which is also what a lambda rule answers.
     */
    private static Method boundCheck(Permission rule) {
        List<Method> found = new ArrayList<>();
        for (Method candidate : candidateMethods(rule.getClass())) {
            if (candidate.getReturnType() == boolean.class && !candidate.getName().equals("allows")) {
                found.add(candidate);
            }
        }
        if (found.size() > 1) {
            throw new IllegalArgumentException(rule.getClass().getName() + " declares " + found.size()
                    + " boolean methods, so it is not clear which one decides; keep one and make the rest private");
        }
        return found.isEmpty() ? null : found.get(0);
    }

    private static Permission instantiate(Class<? extends Permission> type) {
        try {
            return type.getConstructor().newInstance();
        } catch (ReflectiveOperationException | RuntimeException e) {
            return null;
        }
    }

    @SuppressWarnings("unchecked")
    private Function<QQEvent, Object>[] binders(Object owner, Method method, CommandMatcher matcher) {
        Class<?>[] paramTypes = method.getParameterTypes();
        Function[] binders = new Function[paramTypes.length];
        String name = describe(owner, method);
        for (int i = 0; i < paramTypes.length; i++) {
            Class<?> paramType = paramTypes[i];
            if (paramType.isPrimitive() || paramType.isArray()) {
                throw new IllegalArgumentException(name + " parameter " + i + " of type " + paramType.getName()
                        + " cannot be bound; use an envelope, a payload type, Api or QQBotClient");
            }
            if (paramType == OnContext.class) {
                Function<QQEvent, Object> context = e -> matcher == null ? null : matcher.context(e);
                binders[i] = context;
                continue;
            }
            binders[i] = binderFor(paramType, owner, method, i);
        }
        return binders;
    }

    private Function<QQEvent, Object> binderFor(Class<?> paramType, Object owner, Method method, int index) {
        String name = describe(owner, method);
        if (paramType == QQEvent.class) {
            return e -> e;
        }
        if (QQEvent.class.isAssignableFrom(paramType)) {
            return e -> EventEnvelopes.accepts(paramType, e) ? e : null;
        }
        if (paramType == EventType.class) {
            return e -> e.type();
        }
        if (paramType == JsonObject.class) {
            return e -> e.raw() instanceof JsonObject o ? o : new JsonObject();
        }
        if (JsonElement.class.isAssignableFrom(paramType)) {
            return e -> e.raw();
        }
        if (paramType == EventBus.class) {
            return e -> bus;
        }
        if (paramType == QQBotClient.class) {
            requireClient(paramType, name, index);
            return e -> client;
        }
        if (paramType == Api.class) {
            requireClient(paramType, name, index);
            return e -> client.api();
        }
        return e -> payload(e, paramType);
    }

    private void requireClient(Class<?> paramType, String name, int index) {
        if (client == null) {
            throw new IllegalArgumentException(name + " parameter " + index + " of type " + paramType.getName()
                    + " needs a client; register it through bot.handlers() instead of events().register(...)");
        }
    }

    private static Object payload(QQEvent event, Class<?> paramType) {
        Class<?> model = EventModels.dataClass(event.type(), event.name());
        if (model != null && model != Void.class && !paramType.isAssignableFrom(model)) {
            log.debug("{} carries a {} payload, which is not a {}", event.name(), model.getName(),
                    paramType.getName());
            return null;
        }
        JsonElement data = event.raw();
        if (data == null || !data.isJsonObject()) {
            log.debug("payload of {} is not an object, cannot bind {}", event.name(), paramType.getName());
            return null;
        }
        try {
            return Json.GSON.fromJson(data, paramType);
        } catch (RuntimeException e) {
            log.debug("payload of {} does not bind to {}", event.name(), paramType.getName(), e);
            return null;
        }
    }

    private static String describe(Object owner, Method method) {
        return owner.getClass().getName() + "#" + method.getName();
    }

    /**
     * Declared methods of {@code type} and its superclasses, nearest class first, skipping static and synthetic
     * ones. An override that drops the annotation still gets its parent's route, and because the call is
     * reflective, virtual dispatch runs the override.
     */
    public static List<Method> candidateMethods(Class<?> type) {
        Map<String, Method> seen = new LinkedHashMap<>();
        Set<Class<?>> walked = new LinkedHashSet<>();
        for (Class<?> c = type; c != null && c != Object.class && walked.add(c); c = c.getSuperclass()) {
            for (Method m : c.getDeclaredMethods()) {
                if (m.isSynthetic() || m.isBridge() || Modifier.isStatic(m.getModifiers())) {
                    continue;
                }
                seen.putIfAbsent(signature(m), m);
            }
        }
        return new ArrayList<>(seen.values());
    }

    private static String signature(Method m) {
        StringBuilder sb = new StringBuilder(m.getName()).append('(');
        for (Class<?> p : m.getParameterTypes()) {
            sb.append(p.getName()).append(',');
        }
        return sb.append(')').toString();
    }
}
