package io.github.skiesworld.qqbot.handler;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import io.github.skiesworld.qqbot.QQBotClient;
import io.github.skiesworld.qqbot.api.Api;
import io.github.skiesworld.qqbot.event.EventBus;
import io.github.skiesworld.qqbot.event.EventType;
import io.github.skiesworld.qqbot.event.QQEvent;
import io.github.skiesworld.qqbot.util.Json;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.ServiceLoader;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.Supplier;

/**
 * Turns annotated methods into event listeners, so a bot can be a class instead of a lambda pile.
 *
 * <p>Every parameter is filled by type:
 * <table border="1">
 *   <caption>bindable parameter types</caption>
 *   <tr><td>{@link QQEvent}</td><td>the dispatch envelope</td></tr>
 *   <tr><td>{@link EventType}</td><td>the resolved event type</td></tr>
 *   <tr><td>{@link JsonObject} / {@link JsonElement}</td><td>the raw {@code d} member</td></tr>
 *   <tr><td>{@link Api} / {@link QQBotClient}</td><td>needs a registry obtained from
 *       {@link QQBotClient#handlers()}; {@link EventBus#register(Object)} has no client to hand out</td></tr>
 *   <tr><td>any other reference type</td><td>the payload, deserialized into that type</td></tr>
 * </table>
 *
 * <p>Registration is strict so mistakes surface at startup rather than on the first matching event: an
 * annotated method with no event, a primitive or array parameter, or an {@code Api} parameter on a
 * client-less registry all fail there. A payload that cannot be deserialized into the declared type, or a
 * dispatch whose {@code d} is absent, skips that one invocation with a debug log. Exceptions from user code
 * never reach the gateway reader thread.
 *
 * <p>Assembly has two paths and they share this class: call {@link #register(Object)} with an instance, or
 * implement {@link BotHandler} and let {@link #registerDiscovered()} find it through {@link ServiceLoader} —
 * the manifest that makes discovery work is generated by the optional annotation processor.
 */
public final class HandlerRegistry {

    /** One annotated method and the events it asked for. */
    public static final class Route {

        private final Method method;
        private final EventType[] types;
        private final String[] names;

        public Route(Method method, EventType[] types, String[] names) {
            this.method = Objects.requireNonNull(method, "method");
            this.types = types == null ? new EventType[0] : types;
            this.names = names == null ? new String[0] : names;
        }

        public Method method() {
            return method;
        }
    }

    /**
     * Extra parameter bindings for a registration, used by layers built on top of events — notably
     * {@link io.github.skiesworld.qqbot.command.CommandRegistry}, which supplies the
     * {@link io.github.skiesworld.qqbot.command.CommandContext} a {@code @Command} method asks for. A binding
     * that returns null makes the engine skip that dispatch, which is how a non-matching message is dropped.
     */
    public static final class RouteSpec {

        private static final RouteSpec NONE = new RouteSpec(Map.of());

        private final Map<Class<?>, Function<QQEvent, Object>> bindings;

        private RouteSpec(Map<Class<?>, Function<QQEvent, Object>> bindings) {
            this.bindings = bindings;
        }

        public static RouteSpec of(Map<Class<?>, Function<QQEvent, Object>> bindings) {
            return new RouteSpec(bindings == null ? Map.of() : Map.copyOf(bindings));
        }

        /** A spec that binds nothing beyond the type rules. */
        public static RouteSpec plain() {
            return NONE;
        }
    }

    private static final Logger log = LoggerFactory.getLogger(HandlerRegistry.class);

    private final EventBus bus;
    private final QQBotClient client;
    private final Map<Class<? extends Permission>, Supplier<? extends Permission>> permissionFactories =
            new ConcurrentHashMap<>();

    public HandlerRegistry(EventBus bus) {
        this(bus, null);
    }

    public HandlerRegistry(EventBus bus, QQBotClient client) {
        this.bus = Objects.requireNonNull(bus, "bus");
        this.client = client;
    }

    /** Register every {@link BotEvent} method of {@code handler}. */
    public EventBus.Subscription register(Object handler) {
        return register(handler, RouteSpec.NONE);
    }

    /** Register every {@link BotEvent} method of {@code handler} through {@code spec}. */
    public EventBus.Subscription register(Object handler, RouteSpec spec) {
        return register(handler, eventRoutes(handler), spec);
    }

    /**
     * Register pre-computed routes for {@code handler}'s methods; each {@link Route#method()} must be declared
     * by {@code handler} or one of its superclasses.
     */
    public EventBus.Subscription register(Object handler, List<Route> routes, RouteSpec spec) {
        List<EventBus.Subscription> subs = new ArrayList<>();
        for (Route route : routes) {
            if (!route.method.getDeclaringClass().isAssignableFrom(handler.getClass())) {
                throw new IllegalArgumentException(route.method + " is not declared by " + handler.getClass());
            }
            subs.addAll(bind(handler, route, spec));
        }
        if (subs.isEmpty()) {
            throw new IllegalArgumentException("nothing to register on " + handler.getClass().getName()
                    + "; annotate at least one method or add a listener directly");
        }
        return () -> {
            for (EventBus.Subscription s : subs) {
                s.close();
            }
        };
    }

    /** Register every {@link BotHandler} visible to the current thread's context class loader. */
    public int registerDiscovered() {
        return registerDiscovered(Thread.currentThread().getContextClassLoader());
    }

    /**
     * Register discovered handlers, returning how many took part. A handler that fails to bind is logged and
     * skipped: one broken class in a jar must not stop the bot from starting.
     */
    public int registerDiscovered(ClassLoader loader) {
        int n = 0;
        for (BotHandler handler : ServiceLoader.load(BotHandler.class, loader)) {
            try {
                register(handler);
                n++;
            } catch (RuntimeException | LinkageError e) {
                log.error("skipping discovered handler {}", handler.getClass().getName(), e);
            }
        }
        return n;
    }

    /**
     * Teach the {@link Check#type()} side of a gate how to build a rule that needs configuration, e.g.
     * {@code bot.handlers().permission(MySuperUsers.class, () -> new MySuperUsers(loadedIds))}. Rules with a
     * public no-arg constructor need nothing here.
     */
    public HandlerRegistry permission(Class<? extends Permission> type, Supplier<? extends Permission> factory) {
        permissionFactories.put(Objects.requireNonNull(type, "type"),
                Objects.requireNonNull(factory, "factory"));
        return this;
    }

    /** {@code handler}'s {@link BotEvent} methods, class before superclass. */
    public static List<Route> eventRoutes(Object handler) {
        List<Route> routes = new ArrayList<>();
        for (Method m : candidateMethods(handler.getClass())) {
            BotEvent annotation = m.getAnnotation(BotEvent.class);
            if (annotation != null) {
                routes.add(new Route(m, annotation.value(), annotation.name()));
            }
        }
        return routes;
    }

    private List<EventBus.Subscription> bind(Object handler, Route route, RouteSpec spec) {
        Method method = route.method;
        if (route.types.length == 0 && route.names.length == 0) {
            throw new IllegalArgumentException(describe(handler, method) + " listens to no event;"
                    + " set value() or name()");
        }
        if (method.getReturnType() != void.class) {
            throw new IllegalArgumentException(describe(handler, method) + " is a routed method but returns "
                    + method.getReturnType().getSimpleName() + "; its result would be discarded."
                    + " Make it void, or mark it @Check if it is a gate");
        }
        Function<QQEvent, Object>[] binders = binders(handler, method, spec);
        Predicate<QQEvent> gate = gateFor(handler, method, spec);
        method.setAccessible(true);

        List<EventBus.Subscription> subs = new ArrayList<>();
        for (EventType type : route.types) {
            subs.add(bus.on(type, event -> invoke(handler, method, binders, gate, event)));
        }
        for (String name : route.names) {
            subs.add(bus.onName(name, event -> invoke(handler, method, binders, gate, event)));
        }
        return subs;
    }

    /**
     * The gate {@code method} asked for, or null. Built here so a typo or an unbuildable rule fails at
     * registration instead of leaving the action ungated at runtime.
     */
    private Predicate<QQEvent> gateFor(Object handler, Method method, RouteSpec spec) {
        Check check = method.getAnnotation(Check.class);
        if (check == null || (check.value().length == 0 && check.type().length == 0)) {
            return null;
        }
        List<Predicate<QQEvent>> gates = new ArrayList<>();
        for (String name : check.value()) {
            gates.add(namedCheck(handler, method, name, spec));
        }
        for (Class<? extends Permission> type : check.type()) {
            gates.add(typedCheck(handler, method, type));
        }
        return event -> {
            for (Predicate<QQEvent> gate : gates) {
                if (!gate.test(event)) {
                    return false;
                }
            }
            return true;
        };
    }

    private Predicate<QQEvent> namedCheck(Object handler, Method gated, String name, RouteSpec spec) {
        List<Method> found = new ArrayList<>();
        for (Method candidate : candidateMethods(handler.getClass())) {
            if (!candidate.getName().equals(name) || candidate.equals(gated)) {
                continue;
            }
            if (candidate.getAnnotation(Check.class) == null) {
                continue;
            }
            if (candidate.getReturnType() != boolean.class && candidate.getReturnType() != Boolean.class) {
                throw new IllegalArgumentException("check \"" + name + "\" on " + handler.getClass().getName()
                        + " returns " + candidate.getReturnType().getSimpleName() + "; a check returns boolean");
            }
            found.add(candidate);
        }
        if (found.isEmpty()) {
            throw new IllegalArgumentException(describe(handler, gated) + " requires check \"" + name
                    + "\", which no @Check method on " + handler.getClass().getName() + " provides");
        }
        if (found.size() > 1) {
            throw new IllegalArgumentException("check \"" + name + "\" is overloaded on "
                    + handler.getClass().getName() + "; give the variants distinct names so it is clear which runs");
        }
        Method check = found.get(0);
        check.setAccessible(true);
        Function<QQEvent, Object>[] binders = binders(handler, check, spec);
        return event -> {
            Object[] args = new Object[binders.length];
            for (int i = 0; i < binders.length; i++) {
                args[i] = binders[i].apply(event);
                if (args[i] == null) {
                    log.debug("check {} denied {}: argument {} could not be bound", name, event.name(), i);
                    return false;
                }
            }
            try {
                return Boolean.TRUE.equals(check.invoke(handler, args));
            } catch (InvocationTargetException e) {
                log.error("check {} threw for {}, denying", name, event.name(), e.getCause());
                return false;
            } catch (ReflectiveOperationException | RuntimeException e) {
                log.error("check {} could not run for {}, denying", name, event.name(), e);
                return false;
            }
        };
    }

    private Predicate<QQEvent> typedCheck(Object handler, Method gated, Class<? extends Permission> type) {
        Permission permission = permissionFactories.containsKey(type)
                ? permissionFactories.get(type).get()
                : instantiate(type);
        if (permission == null) {
            throw new IllegalArgumentException(describe(handler, gated) + " requires " + type.getName()
                    + ", which has no public no-arg constructor; register one with"
                    + " bot.handlers().permission(" + type.getSimpleName() + ".class, () -> new ...)");
        }
        return event -> {
            try {
                return permission.allows(event, client);
            } catch (RuntimeException e) {
                log.error("check {} threw for {}, denying", type.getSimpleName(), event.name(), e);
                return false;
            }
        };
    }

    private static Permission instantiate(Class<? extends Permission> type) {
        try {
            return type.getConstructor().newInstance();
        } catch (ReflectiveOperationException | RuntimeException e) {
            return null;
        }
    }

    @SuppressWarnings("unchecked")
    private Function<QQEvent, Object>[] binders(Object handler, Method method, RouteSpec spec) {
        Class<?>[] paramTypes = method.getParameterTypes();
        Function[] binders = new Function[paramTypes.length];
        for (int i = 0; i < paramTypes.length; i++) {
            Class<?> paramType = paramTypes[i];
            if (paramType.isPrimitive() || paramType.isArray()) {
                throw new IllegalArgumentException(describe(handler, method) + " parameter " + i
                        + " of type " + paramType.getName()
                        + " cannot be bound; use QQEvent, a payload type, Api or QQBotClient");
            }
            Function<QQEvent, Object> bound = spec.bindings.get(paramType);
            binders[i] = bound != null ? bound : binderFor(paramType, handler, method, i);
        }
        return binders;
    }

    private Function<QQEvent, Object> binderFor(Class<?> paramType, Object handler, Method method, int index) {
        if (paramType == QQEvent.class) {
            return e -> e;
        }
        if (paramType == EventType.class) {
            return e -> e.type();
        }
        if (paramType == JsonObject.class) {
            return e -> e.raw() instanceof JsonObject o ? o : new JsonObject();
        }
        if (JsonElement.class.isAssignableFrom(paramType)) {
            return e -> e.raw();
        }
        if (paramType == EventBus.class) {
            return e -> bus;
        }
        if (paramType == QQBotClient.class) {
            requireClient(paramType, handler, method, index);
            return e -> client;
        }
        if (paramType == Api.class) {
            requireClient(paramType, handler, method, index);
            return e -> client.api();
        }
        return e -> payload(e, paramType);
    }

    private void requireClient(Class<?> paramType, Object handler, Method method, int index) {
        if (client == null) {
            throw new IllegalArgumentException(describe(handler, method) + " parameter " + index + " of type "
                    + paramType.getName() + " needs a client; register it through bot.handlers() instead of"
                    + " events().register(...)");
        }
    }

    private static Object payload(QQEvent event, Class<?> paramType) {
        JsonElement data = event.raw();
        if (data == null || !data.isJsonObject()) {
            log.debug("payload of {} is not an object, cannot bind {}", event.name(), paramType.getName());
            return null;
        }
        try {
            return Json.GSON.fromJson(data, paramType);
        } catch (RuntimeException e) {
            log.debug("payload of {} does not bind to {}", event.name(), paramType.getName(), e);
            return null;
        }
    }

    private void invoke(Object handler, Method method, Function<QQEvent, Object>[] binders,
            Predicate<QQEvent> gate, QQEvent event) {
        Object[] args = new Object[binders.length];
        for (int i = 0; i < binders.length; i++) {
            args[i] = binders[i].apply(event);
            if (args[i] == null) {
                log.debug("skipping {} for {}: argument {} could not be bound",
                        describe(handler, method), event.name(), i);
                return;
            }
        }
        if (gate != null && !gate.test(event)) {
            log.debug("check denied {} for {}", describe(handler, method), event.name());
            return;
        }
        try {
            method.invoke(handler, args);
        } catch (InvocationTargetException e) {
            log.error("handler {} threw for {}", describe(handler, method), event.name(), e.getCause());
        } catch (ReflectiveOperationException | RuntimeException e) {
            log.error("handler {} could not run for {}", describe(handler, method), event.name(), e);
        }
    }

    private static String describe(Object handler, Method method) {
        return handler.getClass().getName() + "#" + method.getName();
    }

    /**
     * Declared methods of {@code type} and its superclasses, nearest class first, skipping static and synthetic
     * ones. An override that drops the annotation still gets its parent's route, and because the call is
     * reflective, virtual dispatch runs the override.
     */
    public static List<Method> candidateMethods(Class<?> type) {
        Map<String, Method> seen = new LinkedHashMap<>();
        Set<Class<?>> walked = new LinkedHashSet<>();
        for (Class<?> c = type; c != null && c != Object.class && walked.add(c); c = c.getSuperclass()) {
            for (Method m : c.getDeclaredMethods()) {
                if (m.isSynthetic() || m.isBridge() || Modifier.isStatic(m.getModifiers())) {
                    continue;
                }
                seen.putIfAbsent(signature(m), m);
            }
        }
        return new ArrayList<>(seen.values());
    }

    private static String signature(Method m) {
        StringBuilder sb = new StringBuilder(m.getName()).append('(');
        for (Class<?> p : m.getParameterTypes()) {
            sb.append(p.getName()).append(',');
        }
        return sb.append(')').toString();
    }
}
