// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Rich text paragraph alignment values (docs type Alignment); the wire carries the raw int. */
public final class Alignment {

    public static final int ALIGNMENT_LEFT = 0;

    public static final int ALIGNMENT_MIDDLE = 1;

    public static final int ALIGNMENT_RIGHT = 2;

    private Alignment() {
    }
}
