// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Elements that can be mentioned with At (docs type AtType); the wire carries the raw int. */
public final class AtType {

    public static final int AT_EXPLICIT_USER = 1;

    public static final int AT_ROLE_GROUP = 2;

    public static final int AT_GUILD = 3;

    private AtType() {
    }
}
