// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Forum audit result types (docs type AuditType); the wire carries the raw int. */
public final class AuditType {

    public static final int PUBLISH_THREAD = 1;

    public static final int PUBLISH_POST = 2;

    public static final int PUBLISH_REPLY = 3;

    private AuditType() {
    }
}
