// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Audio playback states for the sub-channel bot (docs type STATUS); the wire carries the raw int. */
public final class AudioPlayStatus {

    public static final int START = 0;

    public static final int PAUSE = 1;

    public static final int RESUME = 2;

    public static final int STOP = 3;

    private AudioPlayStatus() {
    }
}
