// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Sub-channel types (docs type ChannelType); the wire carries the raw int. */
public final class ChannelType {

    public static final int TEXT = 0;

    public static final int RESERVED_1 = 1;

    public static final int VOICE = 2;

    public static final int RESERVED_3 = 3;

    public static final int CATEGORY = 4;

    public static final int LIVE = 10005;

    public static final int APP = 10006;

    public static final int FORUM = 10007;

    private ChannelType() {
    }
}
