// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Sub-channel permission bit map (docs type Permissions); the wire carries a decimal string of the bit map. */
public final class ChannelPermissions {

    public static final int VIEW = 1;

    public static final int MANAGE = 2;

    public static final int SPEAK = 4;

    private ChannelPermissions() {
    }
}
