// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Sub-channel sub types (docs type ChannelSubType); the wire carries the raw int. */
public final class ChannelSubType {

    public static final int CHAT = 0;

    public static final int NOTICE = 1;

    public static final int STRATEGY = 2;

    public static final int OPEN_BLACK = 3;

    private ChannelSubType() {
    }
}
