// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Default guild role ids (docs type DefaultRoleIDsID); the wire carries the raw id as a string. */
public final class DefaultRoleIds {

    public static final int EVERYONE = 1;

    public static final int ADMIN = 2;

    public static final int OWNER = 4;

    public static final int SUBCHANNEL_ADMIN = 5;

    private DefaultRoleIds() {
    }
}
