// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Rich text element types (docs type ElemType); the wire carries the raw int. */
public final class ElemType {

    public static final int ELEM_TYPE_TEXT = 1;

    public static final int ELEM_TYPE_IMAGE = 2;

    public static final int ELEM_TYPE_VIDEO = 3;

    public static final int ELEM_TYPE_URL = 4;

    private ElemType() {
    }
}
