// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Reaction emoji types (docs type EmojiType); the wire carries the raw int. */
public final class EmojiType {

    public static final int SYSTEM = 1;

    public static final int EMOJI = 2;

    private EmojiType() {
    }
}
