// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Forum thread content formats (docs type Format); the wire carries the raw int. */
public final class Format {

    public static final int FORMAT_TEXT = 1;

    public static final int FORMAT_HTML = 2;

    public static final int FORMAT_MARKDOWN = 3;

    public static final int FORMAT_JSON = 4;

    private Format() {
    }
}
