// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Visibility of a private sub-channel (docs type PrivateType); the wire carries the raw int. */
public final class PrivateType {

    public static final int PUBLIC = 0;

    public static final int OWNER_ADMIN = 1;

    public static final int OWNER_ADMIN_SPECIFIED = 2;

    private PrivateType() {
    }
}
