// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Targets a reaction can be attached to (docs type ReactionTargetType); the wire carries the raw int. */
public final class ReactionTargetType {

    public static final int MESSAGE = 0;

    public static final int THREAD = 1;

    public static final int POST = 2;

    public static final int REPLY = 3;

    private ReactionTargetType() {
    }
}
