// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Schedule reminder offsets (docs type RemindType); the wire carries the raw id as a string. */
public final class RemindType {

    public static final int NONE = 0;

    public static final int AT_START = 1;

    public static final int MINUS_5 = 2;

    public static final int MINUS_15 = 3;

    public static final int MINUS_30 = 4;

    public static final int MINUS_60 = 5;

    private RemindType() {
    }
}
