// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Rich text element payloads (docs type RichType); the wire carries the raw int. */
public final class RichType {

    public static final int TEXT = 1;

    public static final int AT = 2;

    public static final int URL = 3;

    public static final int EMOJI = 4;

    public static final int CHANNEL = 5;

    public static final int VIDEO = 10;

    public static final int IMAGE = 11;

    private RichType() {
    }
}
