// Generated by tools/docgen/gen_java.py from tools/docgen/spec.json.
// Regenerate instead of editing.
package io.github.skiesworld.qqbot.model.constant;

/** Who may speak in a sub-channel (docs type SpeakPermission); the wire carries the raw int. */
public final class SpeakPermission {

    public static final int INVALID = 0;

    public static final int ALL = 1;

    public static final int OWNER_ADMIN_SPECIFIED = 2;

    private SpeakPermission() {
    }
}
